### ISSUE TITLE
CNN refinement yields decreasing affinity and score

### ISSUE THREAD

**Issue by wquc** [gnina/gnina#100]
#### CNN refinement yields decreasing affinity and score

I am using version `gnina Jul 21 2019` with the following for refinement:
```
gnina -r prot.pdb -l lig.pdbqt --autobox_ligand lig.pdbqt -o refine.pdbqt --cnn_refinement --gpu --log outp-refine.txt
```

1. Are the CNN affinity and score supposed to decrease during refinement as shown below?

```

              _
             (_)
   __ _ _ __  _ _ __   __ _
  / _` | '_ \| | '_ \ / _` |
 | (_| | | | | | | | | (_| |
  \__, |_| |_|_|_| |_|\__,_|
   __/ |
  |___/

gnina is based on smina and AutoDock Vina.
Please cite appropriately.

*** IMPORTANT: Use of CNN scoring while docking is not recommended. ***
***     CNN scoring is best used with --minimize or --score_only    ***

Weights      Terms
-0.035579    gauss(o=0,_w=0.5,_c=8)
-0.005156    gauss(o=3,_w=2,_c=8)
0.840245     repulsion(o=0,_c=8)
-0.035069    hydrophobic(g=0.5,_b=1.5,_c=8)
-0.587439    non_dir_h_bond(g=-0.7,_b=0,_c=8)
1.923        num_tors_div

Using random seed: 617300398
CNNscore: 0.9114680886
CNNaffinity: 6.2475423813
CNNscore: 0.7921536565
CNNaffinity: 6.0033826828
CNNscore: 0.7712228298
CNNaffinity: 6.1471071243
CNNscore: 0.0040464709
CNNaffinity: 5.2708115578
CNNscore: 0.4218868911
CNNaffinity: 5.4078488350
CNNscore: 0.5019182563
CNNaffinity: 6.1058492661
CNNscore: 0.2703747153
CNNaffinity: 4.9184708595
CNNscore: 0.0012346902
CNNaffinity: 4.3380570412
CNNscore: 0.0020727473
CNNaffinity: 4.8777580261
CNNscore: 0.0004754360
CNNaffinity: 4.3021750450
CNNscore: 0.0015913198
CNNaffinity: 4.9182715416
CNNscore: 0.1185201555
CNNaffinity: 4.7961802483
CNNscore: 0.0006804905
CNNaffinity: 4.2967181206
CNNscore: 0.0004343929
CNNaffinity: 4.0752868652
CNNscore: 0.0010188936
CNNaffinity: 4.9657959938
CNNscore: 0.0002310632
CNNaffinity: 4.1413888931
CNNscore: 0.0003256369
CNNaffinity: 4.6696615219
CNNscore: 0.0011818660
CNNaffinity: 4.7335619926
CNNscore: 0.0002052060
CNNaffinity: 4.2882466316
CNNscore: 0.0000663921
CNNaffinity: 3.3440413475

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
1       0.1        0.000      0.000
2       0.2        1.473      1.852
3       0.3        1.218      1.909
4       0.4        1.998      2.973
5       0.4        2.997      4.773
6       0.7        3.089      5.069
7       0.8        3.075      5.206
```

2. Moreover, based on the help information, specifying `--cnn_refinement` will "Use a **convolutional neural network** for final **minimization** of docked poses", how does this differentiate from specifying `--cnn_score --minimize` instead?

3. If refinement and minimization with CNN are different, which should be done first, or they are totally independent without any order preference?

**Comment by dkoes** [comment]
You are docking, which will generate multiple poses, some of which will have different scores. I recommend updating your version since improvements have been made with the docking code.

Minimization optimizes the provided pose.  Docking (cnn_refinement) generates entirely new poses.  Docking consists of two phases - a stochastic search and a local refinement.  cnn_refinement will use CNN scoring for the second phase.

**Comment by wquc** [comment]
Thank you for the clarification. That makes more sense. 
To use the latest docking code, should I reinstall gnina from scratch? It seems the Docker container has not been updated for 10 months.

**Comment by dkoes** [comment]
I've pushed an update to the gnina docker container.  Give it a try.

**Comment by bellstwohearted** [comment]
> 
> 
> I've pushed an update to the gnina docker container. Give it a try.

Where can I find this docker container? Thanks~

**Comment by RMeli** [comment]
@bellstwohearted this looks like it: https://hub.docker.com/r/dkoes/gnina

**Comment by bellstwohearted** [comment]
> 
> 
> @bellstwohearted this looks like it: https://hub.docker.com/r/dkoes/gnina

Got it!

**Comment by bellstwohearted** [comment]
> 
> 
> @bellstwohearted this looks like it: https://hub.docker.com/r/dkoes/gnina

When I try to start the container, I got the error:
```
[root@gpu /data]# docker run -i -t --name gnina dkoes/gnina /bin/bash
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:407: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: cuda error: no cuda-capable device is detected\\\\n\\\"\"": unknown.
```

It seems that my CUDA version is not supported. I am using CUDA9.0 but my device is
```
NVIDIA-SMI 440.64.00    Driver Version: 440.64.00    CUDA Version: 10.2   
```

Which CUDA is required to start this container, is it CUDA10.2?

**Comment by dkoes** [comment]
It is built with CUDA 10.2, but your driver is new enough to support that so I suspect a different issue.

**Comment by bellstwohearted** [comment]
> 
> 
> It is built with CUDA 10.2, but your driver is new enough to support that so I suspect a different issue.

What should I do to fix this? I can run `nvidia-smi` and other programs are running in a good order with this CUDA version.

**Comment by dkoes** [comment]
Can you run other GPU dependent docker containers?

**Comment by bellstwohearted** [comment]
> 
> 
> Can you run other GPU dependent docker containers?

I am not sure bacause I am pretty new to cocker. However, I actually built gnina in a Ubuntu container while my host is CentOS 7.

**Comment by dkoes** [comment]
That really looks like a generic running docker on a GPU issue to me.  Make sure you can run the default nvidia image.

**Comment by bellstwohearted** [comment]
> 
> 
> That really looks like a generic running docker on a GPU issue to me. Make sure you can run the default nvidia image.

I have managed to start this docker container. However, it seems not using the GPU card,`nvidia-smi` does not produce any output, and `caffe` can not be loaded.
```
root@66ecb79bcb42:/# nvidia-smi
root@66ecb79bcb42:/# python3
Python 3.6.9 (default, Apr 18 2020, 01:56:04)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import caffe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
  File "/usr/local/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: libopenbabel.so.7: cannot open shared object file: No such file or directory
>>>

```

I know that some settings, but am not sure how to do so.
```
[root@localhost base]# docker ps -a
CONTAINER ID        IMAGE                  COMMAND             CREATED             STATUS                     PORTS                  NAMES
66ecb79bcb42        dkoes/gnina            "/bin/bash"         44 minutes ago      Exited (0) 4 seconds ago                          gnina
```

Any suggestions? Thank you very much~

**Comment by dkoes** [comment]
Are you using nvidia docker? https://github.com/NVIDIA/nvidia-docker

**Comment by bellstwohearted** [comment]
@dkoes  I'm a bit confused. Are you suggesting that I should start the nvidia docker first, and then start dkoes/gnina? In other words. gnina docker can only be run when nvidia docker is already running?

**Comment by dkoes** [comment]
I'm saying you need to make sure you can launch a container that can properly access the gpu.

**Comment by bellstwohearted** [comment]
> 
> 
> I'm saying you need to make sure you can launch a container that can properly access the gpu.

Yes, I already have one container which I used for compiling gnina.
I also managed to start the dkoes/gnina container by specifying `--gpus all`.
