### ISSUE TITLE
Output with docking

### ISSUE THREAD

**Issue by RMeli** [gnina/gnina#102]
### Issue summary

When performing docking with flexible residues using `gnina`, the following is printed out for every pose:

```
CNNscore: -1.0000000000
CNNaffinity: 0.0000000000
```

### Steps to reproduce

```
gnina -r ${receptor} -l ${ligand} \
    --flexdist_ligand ${ligand} --flexdist 3 \
    --autobox_ligand ${ligand} --autobox_add 4 \
    --exhaustiveness 8 --num_modes 20 --cpu ${SLURM_TASKS_PER_NODE} \
    --out ${ligout} --out_flex ${recout} \
```

### Your system configuration
Operating system: Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-99-generic x86_64)
Compiler: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CUDA version (if applicable): 10.1
CUDNN version (if applicable):
Python version: Python 3.6.9

**Comment by dkoes** [comment]
I'm 99% my latest commits removed this extraneous output (unless verbose is on).
