### ISSUE TITLE
Build failure on Ubuntu 18.04 under Docker

### ISSUE THREAD

**Issue by glesica** [gnina/gnina#103]
### Issue summary

I've been putting together a Docker image to make it easier for us to run gnina on different machines. In the process of doing this, I ran into a build error in the tests that I wasn't able to work around. As a result, my Docker image just bypasses the tests entirely, which seems to work fine but is obviously not a long term solution.

The Dockerfile can be found at <https://github.com/TravisWheelerLab/gnina-image/blob/master/Dockerfile>. Note that the `RUN sed ...` line is where I disable the tests, so that line must be commented out (with a "#") to reproduce the failure. The nvcc warning that shows up below appears to be unrelated as it pops up a number of times, presumably because I'm running the build on a machine without a GPU.

```
[ 91%] Building CUDA object test/gnina/CMakeFiles/gninacheck.dir/test_cache.cu.o
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
In file included from /gnina/gnina/test/../gninasrc/lib/atom_type.h:26:0,
                 from /gnina/gnina/test/../gninasrc/lib/atom_base.h:26,
                 from /gnina/gnina/test/../gninasrc/lib/result_components.h:10,
                 from /gnina/gnina/test/../gninasrc/lib/grid.h:29,
                 from /gnina/gnina/test/../gninasrc/lib/igrid.h:27,
                 from /gnina/gnina/test/../gninasrc/lib/cache.h:27,
                 from /gnina/gnina/test/../gninasrc/lib/cache_gpu.h:3,
                 from /gnina/gnina/test/gnina/test_cache.cu:5:
/gnina/gnina/test/../gninasrc/lib/atom_constants.h:27:10: fatal error: openbabel/atom.h: No such file or directory
 #include <openbabel/atom.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [test/gnina/CMakeFiles/gninacheck.dir/test_cache.cu.o] Error 1
test/gnina/CMakeFiles/gninacheck.dir/build.make:82: recipe for target 'test/gnina/CMakeFiles/gninacheck.dir/test_cache.cu.o' failed
CMakeFiles/Makefile2:2091: recipe for target 'test/gnina/CMakeFiles/gninacheck.dir/all' failed
make[1]: *** [test/gnina/CMakeFiles/gninacheck.dir/all] Error 2
```

### Steps to reproduce

Attempt to build based on the Dockerfile above after having commented out the `RUN sed...` line.

### Your system configuration

Operating system: Ubuntu 18.04 (Docker)
Compiler: GCC 7.5.0 / nvcc
CUDA version (if applicable): 11.0
CUDNN version (if applicable):
Python version: 3.6.9

**Comment by dkoes** [comment]
This successfully built for me (with docker build).  Can I assume you fixed the issue in your git fork?

**Comment by glesica** [comment]
I pushed up a branch called `build-error`. It's necessary to remove the temporary fix I put in place (which skips all the tests, hence temporary) in order to see the failure. I just verified that it still fails.

I'm going to put up another issue based on the change I had to make in my fork. It's possible they're related since I reverted a commit that changed the version of OpenBabel in use, but it's not immediately clear.

**Comment by dkoes** [comment]
Try configuring OpenBabel with ` -DPYTHON_EXECUTABLE=/usr/bin/python3 -DWITH_COORDGEN=0 -DWITH_MAEPARSER=0`

The coordgen/maeparser libraries tend to be problematic and I think they are causing the issue.  You also want to be using Python3.

**Comment by glesica** [comment]
Tried it, and updated the branch accordingly. Same failure, though.

**Comment by dkoes** [comment]
I can't reproduce.  The attached Dockerfile, which includes these changes and removes the exclusion of tests, builds for me.


[Dockerfile.txt](https://github.com/gnina/gnina/files/4942229/Dockerfile.txt)

**Comment by glesica** [comment]
Fantastic, it looks like the changes I had made to gnina itself are no longer necessary with the new options, so everything just kinda works now. Thanks!
