### ISSUE TITLE
CMake Error while compiling gnina

### ISSUE THREAD

**Issue by shikhar2333** [gnina/gnina#112]
### Issue summary
Unable to execute the build phase during installation of gnina.

### Your system configuration
Operating system: 16.04.1-Ubuntu
Compiler: gcc 5.5.0
CUDA version (if applicable): 9.1
CUDNN version (if applicable): 
Python version: 3.6.8

CMake Error at caffe/src/caffe/CMakeLists.txt:23 (target_link_libraries):
  Error evaluating generator expression:

    $<TARGET_FILE:openbabel>

  No target "openbabel"

CMake Error:
  Error evaluating generator expression:

    $<TARGET_FILE:openbabel>

  No target "openbabel"

CMake Error:
  Error evaluating generator expression:

    $<TARGET_FILE:openbabel>

  No target "openbabel"

CMake Error at gninasrc/CMakeLists.txt:114 (target_link_libraries):
  Error evaluating generator expression:

    $<TARGET_FILE:openbabel>

  No target "openbabel"

CMake Error at gninasrc/CMakeLists.txt:124 (target_link_libraries):
  Error evaluating generator expression:

    $<TARGET_FILE:openbabel>

  No target "openbabel"

CMake Error at gninasrc/CMakeLists.txt:109 (target_link_libraries):
  Error evaluating generator expression:

    $<TARGET_FILE:openbabel>

  No target "openbabel"

CMake Error at gninasrc/CMakeLists.txt:135 (target_link_libraries):
  Error evaluating generator expression:

    $<TARGET_FILE:openbabel>

  No target "openbabel"

CMake Error at gninasrc/CMakeLists.txt:138 (target_link_libraries):
  Error evaluating generator expression:

    $<TARGET_FILE:openbabel>

  No target "openbabel"

CMake Error at test/gnina/CMakeLists.txt:22 (target_link_libraries):
  Error evaluating generator expression:

    $<TARGET_FILE:openbabel>

  No target "openbabel"

CMake Error:
  Error evaluating generator expression:

    $<TARGET_FILE:openbabel>

  No target "openbabel"

CMake Error:
  Error evaluating generator expression:

    $<TARGET_FILE:openbabel>

  No target "openbabel"

CMake Error:
  Error evaluating generator expression:

    $<TARGET_FILE:openbabel>

  No target "openbabel"

CMake Error:
  Error evaluating generator expression:

    $<TARGET_FILE:openbabel>

  No target "openbabel"

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

I have installed OpenBabel3 successfully. But while building gnina, I get the above error on running `cmake ..`. Any inputs as to why it shows: No target "openbabel"?

**Comment by dkoes** [comment]
Is OpenBabel being found by cmake?  You may need to set OpenBabel3_DIR explicitly if it wasn't installed into a standard place.

**Comment by shikhar2333** [comment]
How do i pass it while running cmake?

**Comment by shikhar2333** [comment]
My OpenBabel installation dir is: `~/Tools/openbabel-install`

**Comment by dkoes** [comment]
`cmake -DOpenBabel3_DIR=$HOME/Tools/openbabel-install ..`

**Comment by shikhar2333** [comment]
> cmake -DOpenBabel3_DIR=$HOME/Tools/openbabel-install ..

I get the same error in addition to the following message:
CMake Warning:
  Manually-specified variables were not used by the project:

   ` OpenBabel3_DIR`

**Comment by dkoes** [comment]
What version of cmake are you using?

**Comment by shikhar2333** [comment]
> What version of cmake are you using?

3.19.4.

**Comment by dkoes** [comment]
I do not see what it wouldn't understand the OpenBabel3_DIR variable then.
Are you planning on doing development?  If not, there is a binary you can just download and use:
https://github.com/gnina/gnina/releases/download/v1.0/gnina

**Comment by shikhar2333** [comment]
I tried using the following 3 flags: OPENBABEL3_DIR,  OPENBABEL_LIBRARIES,  OPENBABEL_INCLUDE_DIR.
Cmake did detect my local installation. But still the same error was thrown. So I think there might be some issue in the CMakeList.txt file.
I plan to use the binary for now until this gets resolved.

**Comment by dkoes** [comment]
Unless you can provide a docker file that exhibits the error, it will not be resolved since I can't reproduce it.
