### ISSUE TITLE
Normalization about the input grid density (training data)

### ISSUE THREAD

**Issue by yangxiufengsia** [gnina/gnina#113]
### Issue summary
Hi prof. Koes, 
I am wondering if data normalization was performed for the input grid density ? Thank you!

### Your system configuration
Operating system:
Compiler:
CUDA version (if applicable):
CUDNN version (if applicable):
Python version:

**Comment by dkoes** [comment]
There is no normalization, but of course the Gaussians have characteristic distributions.
