### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by yy2058** [gnina/gnina#115]
### Issue summary
virtual memory exhausted:  Cannot allocate memory
gninasrc/CMakeFiles/gnina.dir/build.make:202: recipe for target 'gninasrc/CMakeFiles/gnina.dir/lib/cnn_data.cpp.o' failed
make[2]: *** [gninasrc/CMakeFiles/gnina.dir/lib/cnn_data.cpp.o] Error 1
CMakeFiles/Makefile2:1888: recipe for target 'gninasrc/CMakeFiles/gnina.dir/all' failed
make[1]: *** [gninasrc/CMakeFiles/gnina.dir/all] Error 2
Makefile:159: recipe for target 'all' failed
make: *** [all] Error 2

### Steps to reproduce
I tried these commands, but it didn't work.
mkdir /opt/images/  
rm -rf /opt/images/swap  
dd if=/dev/zero of=/opt/images/swap bs=1024 count=2048000
mkswap /opt/images/swap
swapon /opt/images/swap

### Your system configuration
Operating system:
Compiler:
CUDA version (if applicable):
CUDNN version (if applicable):
Python version:

**Comment by dkoes** [comment]
You don't have enough memory to compile.  This is not an issue with the code base, but with your environment.

**Comment by yy2058** [comment]
> You don't have enough memory to compile. This is not an issue with the code base, but with your environment.

thanks a lot.

**Comment by dkoes** [comment]
I'm sorry, but you need 8GB of RAM to compile the CNN models.  If you don't have enough memory to compile, you aren't going to have enough RAM to use the CNN models either.
