### ISSUE TITLE
Change Python installation location?

### ISSUE THREAD

**Issue by RMeli** [gnina/gnina#116]
The `caffe` version of GNINA gets installed in `/usr/local/python`, which needs to be explicitly added to the path (as detailed in [gnina/scripts](https://github.com/gnina/scripts)). Wouldn't it be better to install it on the locations corresponding the the Python executable defined with ` -DPYTHON_EXECUTABLE`?

**Comment by dkoes** [comment]
Sure, that's legacy from caffe.  Would you be willing to submit a pull request?

**Comment by RMeli** [comment]
Yes, I was planning to open one in the next few days if this the idea was OK. I'll leave this open as a reminder.

**Comment by RMeli** [comment]
Fixed by #169 (I completely lost track of this issue, sorry).
