### ISSUE TITLE
How to generate dx file for gninagrid command

### ISSUE THREAD

**Issue by chrisxu2016** [gnina/gnina#117]
When I use gninagrid to generate data, I added the parameter --separate, but I need to specify the additional grid file through the parameter --grid or --example_grid, but I don't know how to generate this  .dx  file. 

I refer to the steps 3.1  in the following link
https://www.protocols.io/view/train-cnn-model-using-gnina-3rngm5e?step=3.1

Can you provide a data processing tutorials？

**Comment by dkoes** [comment]
If you don't already have a grid that defines the dimensions you want, then I can't think of a use case where it makes sense to pre-generate grids instead of using libmolgrid (https://gnina.github.io/libmolgrid/) to dynamically generate grids.
