### ISSUE TITLE
GNINA - how to pass include and libraries of OpenBabel/libmolgrid to cmake?

### ISSUE THREAD

**Issue by mercadde** [gnina/gnina#120]
### Issue summary

Hello,
I am trying to compile GNINA in a non-standard location. 
I have previously (succesfully) installed openbabel and libmolgrid (also in non-standard locations). 

I am trying to pass to cmake the locations of the header files and libraries of OpenBabel and Libmolgrid, previously installed but unsuccesfully so far and I get the following error at the make stage: 

/mnt/shared/releases/source/gnina/caffe/src/caffe/common.cpp:10:10: fatal error: libmolgrid/libmolgrid.h: No such file or directory
 #include <libmolgrid/libmolgrid.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
caffe/src/caffe/CMakeFiles/caffe.dir/build.make:89: recipe for target 'caffe/src/caffe/CMakeFiles/caffe.dir/common.cpp.o' failed
make[2]: *** [caffe/src/caffe/CMakeFiles/caffe.dir/common.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/mnt/shared/releases/source/gnina/caffe/src/caffe/layer_factory.cpp: In instantiation of ‘boost::shared_ptr<caffe::Layer<Dtype> > caffe::GetPythonLayer(const caffe::LayerParameter&) [with Dtype = float]’:
/mnt/shared/releases/source/gnina/caffe/src/caffe/layer_factory.cpp:309:1:   required from here
/mnt/shared/releases/source/gnina/caffe/src/caffe/layer_factory.cpp:303:5: warning: catching polymorphic type ‘struct boost::python::error_already_set’ by value [-Wcatch-value=]
   } catch (bp::error_already_set) {
     ^~~~~
/mnt/shared/releases/source/gnina/caffe/src/caffe/layer_factory.cpp: In instantiation of ‘boost::shared_ptr<caffe::Layer<Dtype> > caffe::GetPythonLayer(const caffe::LayerParameter&) [with Dtype = double]’:
/mnt/shared/releases/source/gnina/caffe/src/caffe/layer_factory.cpp:309:1:   required from here
/mnt/shared/releases/source/gnina/caffe/src/caffe/layer_factory.cpp:303:5: warning: catching polymorphic type ‘struct boost::python::error_already_set’ by value [-Wcatch-value=]
CMakeFiles/Makefile2:1294: recipe for target 'caffe/src/caffe/CMakeFiles/caffe.dir/all' failed
make[1]: *** [caffe/src/caffe/CMakeFiles/caffe.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2

### Steps to reproduce

This is my cmake command:

cmake -DCMAKE_CUDA_COMPILER=/usr/local/cuda-10.2/bin/nvcc -DOpenBabel3_SOURCE_DIR=/mnt/shared/releases/compiled/OpenBabel -DCMAKE_INSTALL_PREFIX=/mnt/shared/releases/compiled/GNina -DCUDA_ARCH_NAME=All -DOpenBabel3_DIR=/mnt/shared/releases/source/openbabel/build -DLIBMOLGRID_INCLUDE_DIR=/mnt/shared/releases/compiled/Libmolgrid/include/libmolgrid/ -DLIBMOLGRID_LIBRARY=/mnt/shared/releases/compiled/Libmolgrid/lib/libmolgrid.so -DOpenBabel3_INCLUDE_DIRS=/mnt/shared/releases/compiled/OpenBabel/include -DOpenBabel3_LIBRARIES=/mnt/shared/releases/compiled/OpenBabel/lib/libopenbabel.so ..

Not sure how to pass the OpenBabel and libmolgrid header and lib files to the cmake. 
I have installed them in the following directories respectively:

/mnt/shared/releases/compiled/OpenBabel
/mnt/shared/releases/compiled/Libmolgrid

Ideally, it would be great to have a statically compiled executable. 

Any help would be very much appreciated. 

Best Regards,
Davide

### Your system configuration
Operating system: Ubuntu 20.04
Compiler: GNU 8.4.0
CUDA version (if applicable):
CUDNN version (if applicable): 
Python version: 3.6.9

**Comment by dkoes** [comment]
You can see that the libmolgrid directory is part of the include, so the directory should be `-DLIBMOLGRID_INCLUDE_DIR=/mnt/shared/releases/compiled/Libmolgrid/include` without the libmolgrid at the end.

**Comment by mercadde** [comment]
Thank you very much for the reply. I am afraid that it didn't solve the problem. 
My new command (had tried that before) is:

cmake -DCMAKE_CUDA_COMPILER=/usr/local/cuda-10.2/bin/nvcc -DOpenBabel3_SOURCE_DIR=/mnt/shared/releases/compiled/OpenBabel -DCMAKE_INSTALL_PREFIX=/mnt/shared/releases/compiled/GNina -DCUDA_ARCH_NAME=All -DOpenBabel3_DIR=/mnt/shared/releases/source/openbabel/build -DLIBMOLGRID_INCLUDE_DIR=/mnt/shared/releases/compiled/Libmolgrid/include -DLIBMOLGRID_LIBRARY=/mnt/shared/releases/compiled/Libmolgrid/lib/libmolgrid.so -DOpenBabel3_INCLUDE_DIRS=/mnt/shared/releases/compiled/OpenBabel/include -DOpenBabel3_LIBRARIES=/mnt/shared/releases/compiled/OpenBabel/lib/libopenbabel.so ..

I am still getting: 

/mnt/shared/releases/source/gnina/caffe/src/caffe/common.cpp:10:10: fatal error: libmolgrid/libmolgrid.h: No such file or directory
 #include <libmolgrid/libmolgrid.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
caffe/src/caffe/CMakeFiles/caffe.dir/build.make:89: recipe for target 'caffe/src/caffe/CMakeFiles/caffe.dir/common.cpp.o' failed
make[2]: *** [caffe/src/caffe/CMakeFiles/caffe.dir/common.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/mnt/shared/releases/source/gnina/caffe/src/caffe/layer_factory.cpp: In instantiation of ‘boost::shared_ptr<caffe::Layer<Dtype> > caffe::GetPythonLayer(const caffe::LayerParameter&) [with Dtype = float]’:
/mnt/shared/releases/source/gnina/caffe/src/caffe/layer_factory.cpp:309:1:   required from here
/mnt/shared/releases/source/gnina/caffe/src/caffe/layer_factory.cpp:303:5: warning: catching polymorphic type ‘struct boost::python::error_already_set’ by value [-Wcatch-value=]
   } catch (bp::error_already_set) {
     ^~~~~
/mnt/shared/releases/source/gnina/caffe/src/caffe/layer_factory.cpp: In instantiation of ‘boost::shared_ptr<caffe::Layer<Dtype> > caffe::GetPythonLayer(const caffe::LayerParameter&) [with Dtype = double]’:
/mnt/shared/releases/source/gnina/caffe/src/caffe/layer_factory.cpp:309:1:   required from here
/mnt/shared/releases/source/gnina/caffe/src/caffe/layer_factory.cpp:303:5: warning: catching polymorphic type ‘struct boost::python::error_already_set’ by value [-Wcatch-value=]
CMakeFiles/Makefile2:1294: recipe for target 'caffe/src/caffe/CMakeFiles/caffe.dir/all' failed
make[1]: *** [caffe/src/caffe/CMakeFiles/caffe.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2

Additionally, it doesn't seem that cmake points correctly to the installed OpenBabel as in the cmake step I get:

-- The C compiler identification is GNU 8.4.0
-- The CXX compiler identification is GNU 8.4.0
-- The CUDA compiler identification is NVIDIA 10.2.89
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda-10.2/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found suitable version "10.2", minimum required is "9.0") 
openbabel BINARY_DIR = /mnt/shared/releases/source/gnina/build
openbabel BINARY_DIR = /mnt/shared/releases/source/gnina/build
openbabel IMPORTED = TRUE
openbabel IMPORTED_CONFIGURATIONS = RELEASE
openbabel IMPORTED_GLOBAL = FALSE
openbabel NAME = openbabel
openbabel POSITION_INDEPENDENT_CODE = True
openbabel SOURCE_DIR = /mnt/shared/releases/source/gnina
openbabel SOURCE_DIR = /mnt/shared/releases/source/gnina
openbabel TYPE = SHARED_LIBRARY
openbabel TYPE = SHARED_LIBRARY
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Found libmolgrid: /mnt/shared/releases/compiled/Libmolgrid/include  
-- CUDA detected: 10.2
-- Added CUDA NVCC flags for: sm_35 sm_50 sm_60 sm_61 sm_70 sm_75
-- Found Boost: /usr/include (found suitable version "1.65.1", minimum required is "1.54") found components: system thread filesystem iostreams timer chrono date_time atomic regex 
-- Found GFlags: /usr/include  
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found Glog: /usr/include  
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found version "3.0.0") 
-- Found PROTOBUF Compiler: /usr/bin/protoc
-- Found HDF5: /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so;/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_cpp.so;/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "1.10.0.1") found components: HL 
-- CUDA detected: 10.2
-- Found cuDNN: ver. 7.6.5 found (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Added CUDA NVCC flags for: sm_35 sm_50 sm_60 sm_61 sm_70 sm_75
-- Found Atlas: /usr/include/x86_64-linux-gnu  
-- Found Atlas (include: /usr/include/x86_64-linux-gnu library: /usr/lib/x86_64-linux-gnu/libatlas.so lapack: /usr/lib/x86_64-linux-gnu/liblapack.so
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.9", minimum required is "3.0") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found suitable version "3.6.9", minimum required is "3.0") 
-- Found NumPy: /home/dmer018/.local/lib/python3.6/site-packages/numpy/core/include (found suitable version "1.16.6", minimum required is "1.7.1") 
-- NumPy ver. 1.16.6 found (include: /home/dmer018/.local/lib/python3.6/site-packages/numpy/core/include)
-- Found Boost: /usr/include (found suitable version "1.65.1", minimum required is "1.58") found components: python36 
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Found Git: /usr/bin/git (found version "2.17.1") 
-- 
-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version           :   1.0.0
--   Git               :   v1.0.1-13-g36bd9dda
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -Wno-deprecated-declarations -Wno-unknown-pragmas -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -Wno-deprecated-declarations -Wno-unknown-pragmas -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release
-- 
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   ON
--   CPU_ONLY          :   OFF
--   USE_OPENCV        :   0
--   USE_LEVELDB       :   0
--   USE_LMDB          :   0
--   USE_NCCL          :   OFF
--   ALLOW_LMDB_NOLOCK :   OFF
-- 
-- Dependencies:
--   BLAS              :   Yes (Atlas)
--   Boost             :   Yes (ver. 1.65)
--   glog              :   Yes
--   gflags            :   Yes
--   OpenBabel         :   No
--   protobuf          :   Yes (ver. 3.0.0)
--   CUDA              :   Yes (ver. 10.2)
-- 
-- NVIDIA CUDA:
--   Target GPU(s)     :   All
--   GPU arch(s)       :   sm_35 sm_50 sm_60 sm_61 sm_70 sm_75
--   cuDNN             :   Yes (ver. 7.6.5)
-- 
-- Python:
--   Interpreter       :   /usr/bin/python3 (ver. 3.6.9)
--   Libraries         :   /usr/lib/x86_64-linux-gnu/libpython3.6m.so (ver 3.6.9)
--   NumPy             :   /home/dmer018/.local/lib/python3.6/site-packages/numpy/core/include (ver 1.16.6)
-- 
-- Documentaion:
--   Doxygen           :   No
--   config_file       :   
-- 
-- Install:
--   Install path      :   /mnt/shared/releases/compiled/GNina
-- 
-- Found Boost: /usr/include (found version "1.65.1") found components: program_options system iostreams timer thread serialization filesystem date_time regex unit_test_framework chrono atomic 
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Found RDKit include files at /usr/include/rdkit
-- Found RDKit libraries at /usr/lib
-- Found RDKit library files at /usr/lib/libFileParsers.so;/usr/lib/libSmilesParse.so;/usr/lib/libGraphMol.so;/usr/lib/libRDGeometryLib.so;/usr/lib/libRDGeneral.so;/usr/lib/libSubgraphs.so;/usr/lib/libDataStructs.so;/usr/lib/libDepictor.so
-- Found RDKit: /usr/include/rdkit  
-- Found Boost: /usr/include (found version "1.65.1") found components: unit_test_framework system 
-- Found PythonInterp: /usr/bin/python3 (found version "3.6.9") 
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    OpenBabel3_SOURCE_DIR

-- Build files have been written to: /mnt/shared/releases/source/gnina/build

Besides the problem with libmolgrid header files, seems that OpenBabel is still pointing to the wrong place?  

Thank you in advance for your time. 

Best Regards,
D.

**Comment by dkoes** [comment]
You should only have to specify OpenBabel3_DIR.  The SOURCE_DIR definitely isn't needed.

I can't tell you exactly what is wrong without access to your system, but the way to approach this is to run `make VERBOSE=1` and look at the `-I` arguments to gcc.  The libmolgrid install directory should be present there and you should verify that `libmolgrid/libmolgrid.h` is indeed at that location.

**Comment by sawsimeon** [comment]
Hi I also face the similarity issue when install GNINA from source. This was my error when trying to call ```cmake ..```. I have also install openbabel version 3.

```
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- The CUDA compiler identification is NVIDIA 10.1.243
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr (found suitable version "10.1", minimum required is "9.0") 
CMake Error at CMakeLists.txt:62 (find_package):
  Found package configuration file:

    /usr/local/lib/cmake/openbabel3/OpenBabel3Config.cmake

  but it set OpenBabel3_FOUND to FALSE so package "OpenBabel3" is considered
  to be NOT FOUND.  Reason given by package:

  The following imported targets are referenced, but are missing: coordgen

```

**Comment by dkoes** [comment]
coordgen and maeparser are often problematic.  My recommendation is to build openbabel3 without them (` -DWITH_MAEPARSER=NO -DWITH_COORDGEN=NO`)

**Comment by sawsimeon** [comment]
@dkoes Wow! that's it. It works. Thanks a bunch.
