### ISSUE TITLE
Building GNINA on Google Colab

### ISSUE THREAD

**Issue by jokpreiksa** [gnina/gnina#123]
### Issue summary
Hello, 
I am having some issues to build Gnina on Google Colab.
Maybe You could help me:

### Steps to reproduce

CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.18 or higher is required.  You are running version 3.12.0

-- Configuring incomplete, errors occurred!
CMakeFiles/libmolgrid.dir/build.make:105: recipe for target 'libmolgrid-prefix/src/libmolgrid-stamp/libmolgrid-configure' failed
make[2]: *** [libmolgrid-prefix/src/libmolgrid-stamp/libmolgrid-configure] Error 1
CMakeFiles/Makefile2:424: recipe for target 'CMakeFiles/libmolgrid.dir/all' failed
make[1]: *** [CMakeFiles/libmolgrid.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

### Your system configuration
Google Colab
Operating system:
Compiler:
CUDA version (if applicable):
CUDNN version (if applicable):
Python version:

**Comment by RMeli** [comment]
>  CMake 3.18 or higher is required. You are running version 3.12.0

To build GNINA from source you need CMake 3.18 or higher, while 3.12 seems to be installed. If you only need to use GNINA, I suggest you download the executable:

```
!wget https://github.com/gnina/gnina/releases/download/v1.0.1/gnina
```

---

There is also a Google Colab notebook that shows how to use GNINA (from the [RSC Workshop](https://www.youtube.com/watch?v=MG3Srzi5kZ0)): [gninaworkshop.ipynb](https://colab.research.google.com/drive/1GXmk1v8C-c4UtyKFqIm9HnsrVYH0pI-c)

**Comment by dkoes** [comment]
I will second this - since colab instances are ephemeral and building gnina takes a long time, it really doesn't make sense to build from source as oppose to using the provided binary.
