### ISSUE TITLE
Could anyone tell me where to find a test set (with receptor & ligand) :)

### ISSUE THREAD

**Issue by CHANG-Shaole** [gnina/gnina#124]
### Your system configuration
Operating system:
Compiler:
CUDA version (if applicable):
CUDNN version (if applicable):
Python version:

**Comment by dkoes** [comment]
As stated at the top of the README, there is an example notebook showing usage here:
https://colab.research.google.com/drive/1QYo5QLUE80N_G28PlpYs6OKGddhhd931?usp=sharing
