### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by quantumania** [gnina/gnina#13]
[ 39%] Building CXX object caffe/src/caffe/CMakeFiles/caffe.dir/util/upgrade_proto.cpp.o
[ 39%] Linking CXX shared library ../../lib/libcaffe.so
[ 39%] Built target caffe
Scanning dependencies of target upgrade_solver_proto_text
[ 39%] Building CXX object caffe/tools/CMakeFiles/upgrade_solver_proto_text.dir/upgrade_solver_proto_text.cpp.o
[ 40%] Linking CXX executable upgrade_solver_proto_text
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `OpenBabel::OBAtomAtomIter::operator++()'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `cblas_sgemv'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `cblas_dgemm'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `cblas_sscal'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `OpenBabel::OBAtomAtomIter::OBAtomAtomIter(OpenBabel::OBAtom&)'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `cblas_dgemv'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `OpenBabel::OBAtom::IsHbondAcceptor()'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `cblas_saxpy'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `cblas_ddot'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `cblas_dasum'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `OpenBabel::OBConversion::~OBConversion()'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `OpenBabel::OBAtom::IsAromatic() const'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `OpenBabel::OBMolAtomIter::OBMolAtomIter(OpenBabel::OBMol&)'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `cblas_sgemm'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `OpenBabel::OBMol::AddHydrogens(bool, bool, double)'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `OpenBabel::OBConversion::ReadFile(OpenBabel::OBBase*, std::string)'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `cblas_dscal'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `OpenBabel::OBElementTable::GetSymbol(int)'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `cblas_scopy'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `OpenBabel::OBMol::~OBMol()'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `cblas_sasum'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `OpenBabel::OBMol::NumHvyAtoms()'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `OpenBabel::OBMolAtomIter::operator++()'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `cblas_daxpy'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `OpenBabel::OBConversion::OBConversion(std::istream*, std::ostream*)'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `OpenBabel::etab'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `OpenBabel::OBMol::OBMol()'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `cblas_dcopy'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `cblas_sdot'
collect2: error: ld returned 1 exit status
caffe/tools/CMakeFiles/upgrade_solver_proto_text.dir/build.make:126: recipe for target 'caffe/tools/upgrade_solver_proto_text' failed
make[2]: *** [caffe/tools/upgrade_solver_proto_text] Error 1
CMakeFiles/Makefile2:474: recipe for target 'caffe/tools/CMakeFiles/upgrade_solver_proto_text.dir/all' failed
make[1]: *** [caffe/tools/CMakeFiles/upgrade_solver_proto_text.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

Can anyone help!

**Comment by dkoes** [comment]
It's not finding the openbabel or blas libraries.  Are you sure they are installed?  In CMakeCache.txt, what is OPENBABEL2_LIBRARIES set to?

**Comment by quantumania** [comment]
Scanning dependencies of target upgrade_solver_proto_text
[ 39%] Building CXX object caffe/tools/CMakeFiles/upgrade_solver_proto_text.dir/upgrade_solver_proto_text.cpp.o
[ 40%] Linking CXX executable upgrade_solver_proto_text
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `cblas_sgemv'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `cblas_dgemm'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `cblas_sscal'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `cblas_dgemv'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `cblas_saxpy'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `cblas_ddot'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `cblas_dasum'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `cblas_sgemm'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `cblas_dscal'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `cblas_scopy'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `cblas_sasum'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `cblas_daxpy'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `cblas_dcopy'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `cblas_sdot'
collect2: error: ld returned 1 exit status
caffe/tools/CMakeFiles/upgrade_solver_proto_text.dir/build.make:127: recipe for target 'caffe/tools/upgrade_solver_proto_text' failed
make[2]: *** [caffe/tools/upgrade_solver_proto_text] Error 1
CMakeFiles/Makefile2:474: recipe for target 'caffe/tools/CMakeFiles/upgrade_solver_proto_text.dir/all' failed
make[1]: *** [caffe/tools/CMakeFiles/upgrade_solver_proto_text.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
============================================
The openbabel errors are gone, with cblas errors left. Here's the CMakeCache sections related to Atlas. Not sure what caused the errors...

//Path to a library.
Atlas_BLAS_LIBRARY:FILEPATH=/usr/lib64/atlas/libtatlas.so.3

//Path to a file.
Atlas_CBLAS_INCLUDE_DIR:PATH=/usr/include/atlas

//Path to a library.
Atlas_CBLAS_LIBRARY:FILEPATH=/usr/lib64/atlas/libtatlas.so.3

//Path to a file.
Atlas_CLAPACK_INCLUDE_DIR:PATH=/usr/include/atlas

//Path to a library.
Atlas_LAPACK_LIBRARY:FILEPATH=/usr/lib64/atlas/libtatlas.so.3

//Selected BLAS library
BLAS:STRING=Atlas
