### ISSUE TITLE
Multi-GPU VS

### ISSUE THREAD

**Issue by HBioquant** [gnina/gnina#131]
Hi, how to make gnina perform multi-GPU parallel computing in virtual screening tasks? The current speed (e.g. --cnn_scoring rescore) on a single GPU is not satisfactory for, ...maybe most of us. Thanks, a nice work!

**Comment by dkoes** [comment]
If you are evaluating multiple molecules it should be trivial to split up the input and run on multiple GPUs.

**Comment by HyungSik-Jo** [comment]
@dkoes  Hi, I'm interested in the features you created and I'm trying out various things.

Is there still no way to compute gnina to multiple GPUs?
