### ISSUE TITLE
unable to Install

### ISSUE THREAD

**Issue by kimlabSchatterjee** [gnina/gnina#132]
### Issue summary

Unable to install

### Steps to reproduce

[ 48%] Linking CXX executable caffe
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::throw_error_already_set()'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::import(boost::python::str)'
../lib/libcaffe.so.1.0.0: undefined reference to `typeinfo for boost::python::error_already_set'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::error_already_set::~error_already_set()'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::detail::str_base::str_base(char const*)'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::api::getattr(boost::python::api::object const&, char const*)'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::converter::rvalue_from_python_stage1(_object*, boost::python::converter::registration const&)'
../lib/libcaffe.so.1.0.0: undefined reference to `vtable for boost::python::error_already_set'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::converter::registry::lookup(boost::python::type_info)'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::converter::registry::lookup_shared_ptr(boost::python::type_info)'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::converter::rvalue_from_python_stage2(_object*, boost::python::converter::rvalue_from_python_stage1_data&, boost::python::converter::registration const&)'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::converter::detail::arg_to_python_base::arg_to_python_base(void const volatile*, boost::python::converter::registration const&)'
collect2: error: ld returned 1 exit status
caffe/tools/CMakeFiles/caffe.bin.dir/build.make:138: recipe for target 'caffe/tools/caffe' failed
make[2]: *** [caffe/tools/caffe] Error 1
CMakeFiles/Makefile2:1457: recipe for target 'caffe/tools/CMakeFiles/caffe.bin.dir/all' failed
make[1]: *** [caffe/tools/CMakeFiles/caffe.bin.dir/all] Error 2
[ 48%] Linking CXX shared library ../lib/_caffe.so
Creating symlink /home/kimlab/Downloads/gnina-master/caffe/python/caffe/_caffe.so -> /home/kimlab/Downloads/gnina-master/build/caffe/lib/_caffe.so
[ 48%] Built target pycaffe
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2[ 48%] Linking CXX executable caffe
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::throw_error_already_set()'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::import(boost::python::str)'
../lib/libcaffe.so.1.0.0: undefined reference to `typeinfo for boost::python::error_already_set'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::error_already_set::~error_already_set()'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::detail::str_base::str_base(char const*)'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::api::getattr(boost::python::api::object const&, char const*)'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::converter::rvalue_from_python_stage1(_object*, boost::python::converter::registration const&)'
../lib/libcaffe.so.1.0.0: undefined reference to `vtable for boost::python::error_already_set'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::converter::registry::lookup(boost::python::type_info)'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::converter::registry::lookup_shared_ptr(boost::python::type_info)'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::converter::rvalue_from_python_stage2(_object*, boost::python::converter::rvalue_from_python_stage1_data&, boost::python::converter::registration const&)'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::converter::detail::arg_to_python_base::arg_to_python_base(void const volatile*, boost::python::converter::registration const&)'
collect2: error: ld returned 1 exit status
caffe/tools/CMakeFiles/caffe.bin.dir/build.make:138: recipe for target 'caffe/tools/caffe' failed
make[2]: *** [caffe/tools/caffe] Error 1
CMakeFiles/Makefile2:1457: recipe for target 'caffe/tools/CMakeFiles/caffe.bin.dir/all' failed
make[1]: *** [caffe/tools/CMakeFiles/caffe.bin.dir/all] Error 2
[ 48%] Linking CXX shared library ../lib/_caffe.so
Creating symlink /home/kimlab/Downloads/gnina-master/caffe/python/caffe/_caffe.so -> /home/kimlab/Downloads/gnina-master/build/caffe/lib/_caffe.so
[ 48%] Built target pycaffe
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2[ 48%] Linking CXX executable caffe
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::throw_error_already_set()'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::import(boost::python::str)'
../lib/libcaffe.so.1.0.0: undefined reference to `typeinfo for boost::python::error_already_set'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::error_already_set::~error_already_set()'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::detail::str_base::str_base(char const*)'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::api::getattr(boost::python::api::object const&, char const*)'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::converter::rvalue_from_python_stage1(_object*, boost::python::converter::registration const&)'
../lib/libcaffe.so.1.0.0: undefined reference to `vtable for boost::python::error_already_set'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::converter::registry::lookup(boost::python::type_info)'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::converter::registry::lookup_shared_ptr(boost::python::type_info)'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::converter::rvalue_from_python_stage2(_object*, boost::python::converter::rvalue_from_python_stage1_data&, boost::python::converter::registration const&)'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::converter::detail::arg_to_python_base::arg_to_python_base(void const volatile*, boost::python::converter::registration const&)'
collect2: error: ld returned 1 exit status
caffe/tools/CMakeFiles/caffe.bin.dir/build.make:138: recipe for target 'caffe/tools/caffe' failed
make[2]: *** [caffe/tools/caffe] Error 1
CMakeFiles/Makefile2:1457: recipe for target 'caffe/tools/CMakeFiles/caffe.bin.dir/all' failed
make[1]: *** [caffe/tools/CMakeFiles/caffe.bin.dir/all] Error 2
[ 48%] Linking CXX shared library ../lib/_caffe.so
Creating symlink /home/kimlab/Downloads/gnina-master/caffe/python/caffe/_caffe.so -> /home/kimlab/Downloads/gnina-master/build/caffe/lib/_caffe.so
[ 48%] Built target pycaffe
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2[ 48%] Linking CXX executable caffe
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::throw_error_already_set()'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::import(boost::python::str)'
../lib/libcaffe.so.1.0.0: undefined reference to `typeinfo for boost::python::error_already_set'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::error_already_set::~error_already_set()'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::detail::str_base::str_base(char const*)'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::api::getattr(boost::python::api::object const&, char const*)'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::converter::rvalue_from_python_stage1(_object*, boost::python::converter::registration const&)'
../lib/libcaffe.so.1.0.0: undefined reference to `vtable for boost::python::error_already_set'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::converter::registry::lookup(boost::python::type_info)'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::converter::registry::lookup_shared_ptr(boost::python::type_info)'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::converter::rvalue_from_python_stage2(_object*, boost::python::converter::rvalue_from_python_stage1_data&, boost::python::converter::registration const&)'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::converter::detail::arg_to_python_base::arg_to_python_base(void const volatile*, boost::python::converter::registration const&)'
collect2: error: ld returned 1 exit status
caffe/tools/CMakeFiles/caffe.bin.dir/build.make:138: recipe for target 'caffe/tools/caffe' failed
make[2]: *** [caffe/tools/caffe] Error 1
CMakeFiles/Makefile2:1457: recipe for target 'caffe/tools/CMakeFiles/caffe.bin.dir/all' failed
make[1]: *** [caffe/tools/CMakeFiles/caffe.bin.dir/all] Error 2
[ 48%] Linking CXX shared library ../lib/_caffe.so
Creating symlink /home/kimlab/Downloads/gnina-master/caffe/python/caffe/_caffe.so -> /home/kimlab/Downloads/gnina-master/build/caffe/lib/_caffe.so
[ 48%] Built target pycaffe
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2[ 48%] Linking CXX executable caffe
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::throw_error_already_set()'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::import(boost::python::str)'
../lib/libcaffe.so.1.0.0: undefined reference to `typeinfo for boost::python::error_already_set'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::error_already_set::~error_already_set()'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::detail::str_base::str_base(char const*)'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::api::getattr(boost::python::api::object const&, char const*)'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::converter::rvalue_from_python_stage1(_object*, boost::python::converter::registration const&)'
../lib/libcaffe.so.1.0.0: undefined reference to `vtable for boost::python::error_already_set'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::converter::registry::lookup(boost::python::type_info)'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::converter::registry::lookup_shared_ptr(boost::python::type_info)'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::converter::rvalue_from_python_stage2(_object*, boost::python::converter::rvalue_from_python_stage1_data&, boost::python::converter::registration const&)'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::python::converter::detail::arg_to_python_base::arg_to_python_base(void const volatile*, boost::python::converter::registration const&)'
collect2: error: ld returned 1 exit status
caffe/tools/CMakeFiles/caffe.bin.dir/build.make:138: recipe for target 'caffe/tools/caffe' failed
make[2]: *** [caffe/tools/caffe] Error 1
CMakeFiles/Makefile2:1457: recipe for target 'caffe/tools/CMakeFiles/caffe.bin.dir/all' failed
make[1]: *** [caffe/tools/CMakeFiles/caffe.bin.dir/all] Error 2
[ 48%] Linking CXX shared library ../lib/_caffe.so
Creating symlink /home/kimlab/Downloads/gnina-master/caffe/python/caffe/_caffe.so -> /home/kimlab/Downloads/gnina-master/build/caffe/lib/_caffe.so
[ 48%] Built target pycaffe
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2
### Your system configuration
Operating system:
Compiler:
CUDA version (if applicable):
CUDNN version (if applicable):
Python version:

**Comment by dkoes** [comment]
Looks like you don't have boost_python installed (or at least not the right version).

**Comment by kimlabSchatterjee** [comment]
kimlab@kimlab:~$ sudo apt-get install libboost-all-dev
[sudo] password for kimlab:       
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libboost-all-dev is already the newest version (1.65.1.0ubuntu1).
The following packages were automatically installed and are no longer required:
  linux-headers-4.15.0-156 linux-headers-4.15.0-156-generic
  linux-headers-4.15.0-158 linux-headers-4.15.0-158-generic
  linux-headers-4.15.0-159 linux-headers-4.15.0-159-generic
  linux-headers-4.15.0-162 linux-headers-4.15.0-162-generic
  linux-headers-5.4.0-81-generic linux-headers-5.4.0-84-generic
  linux-headers-5.4.0-86-generic linux-headers-5.4.0-87-generic
  linux-hwe-5.4-headers-5.4.0-81 linux-hwe-5.4-headers-5.4.0-84
  linux-hwe-5.4-headers-5.4.0-86 linux-hwe-5.4-headers-5.4.0-87
  linux-image-4.15.0-156-generic linux-image-4.15.0-158-generic
  linux-image-4.15.0-159-generic linux-image-4.15.0-162-generic
  linux-image-5.4.0-81-generic linux-image-5.4.0-84-generic
  linux-image-5.4.0-86-generic linux-image-5.4.0-87-generic
  linux-modules-4.15.0-156-generic linux-modules-4.15.0-158-generic
  linux-modules-4.15.0-159-generic linux-modules-4.15.0-162-generic
  linux-modules-5.4.0-81-generic linux-modules-5.4.0-84-generic
  linux-modules-5.4.0-86-generic linux-modules-5.4.0-87-generic
  linux-modules-extra-4.15.0-156-generic
  linux-modules-extra-4.15.0-158-generic
  linux-modules-extra-4.15.0-159-generic
  linux-modules-extra-4.15.0-162-generic linux-modules-extra-5.4.0-81-generic
  linux-modules-extra-5.4.0-84-generic linux-modules-extra-5.4.0-86-generic
  linux-modules-extra-5.4.0-87-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.

**Comment by dkoes** [comment]
Okay, but what is missing is libboost_python.  You need to make sure you have a version installed that matches the version of python you are using.

**Comment by kimlabSchatterjee** [comment]
ok ok. Thanks
