### ISSUE TITLE
smina scoring after rebuilding the receptor with fleible sidechains 

### ISSUE THREAD

**Issue by beanik** [gnina/gnina#138]
Hi, I have a problem with scoring the flexible docking results obtained using SMINA. The values obtained with docking do not match the ones that I get for the receptor rebuild using makeflex.py script. The difference is quite high (about 1.5 kcal/mol higher energy for rebuild receptor) so I am not sure how to make the energy decomposition now. Could anyone help me with this issue?

Best regards,
Beata

**Comment by RMeli** [comment]
Hi, thank you for reporting the issue. Can you please provide more details on how you perform the docking and the re-scoring? I can't reproduce your issue (tried with one system I had at hand).

For docking with flexible residues I get
```
mode |  affinity  |    CNN     |   CNN
     | (kcal/mol) | pose score | affinity
-----+------------+------------+----------
    1       -9.70       0.6440      5.732
    2       -9.95       0.5034      5.393
    3       -8.59       0.3453      4.804
    4       -7.54       0.3382      4.445
    5       -8.51       0.3368      4.779
    6       -7.70       0.3289      4.833
    7       -8.85       0.3263      4.688
    8       -8.56       0.3196      4.977
    9       -8.49       0.2603      4.344
```
and when re-scoring the first pose using the same command (which also fixes the random seed) used for docking but with the `--score_only` option and the receptor re-built using the `makeflex.py` script I get the following:
```
## Name gauss(o=0,_w=0.5,_c=8) gauss(o=3,_w=2,_c=8) repulsion(o=0,_c=8) hydrophobic(g=0.5,_b=1.5,_c=8) non_dir_h_bond(g=-0.7,_b=0,_c=8) num_tors_div
Affinity: -9.69658 (kcal/mol)
CNNscore: 0.65230 
CNNaffinity: 5.74346
CNNvariance: 0.56408
Intramolecular energy: -18.23352
Term values, before weighting:
##  95.35953 1156.97241 4.37594 5.24111 9.68127 0.00000
```

**Comment by dkoes** [comment]
The score when using flexible docking includes the intramolecular interactions of the flexible sidechains.  To match scores when rescoring, you have to keep the same set of residues in the flexible part (i.e., you will not get the same score as when treating the receptor as rigid).

**Comment by RMeli** [comment]
As @dkoes mentioned, in order to get the same results when re-scoring the docked pose you need to include the same flexible residues (in order to include the same intramolecular interactions of the flexible sidechains). Otherwise, in your re-scoring you will miss out the contribution of intramolecular interactions of the flexible side chains and therefore the results will be different. Therefore, if you use the following for re-scoring
```
--score_only --flexres A:905,A:910,A:916,A:919,A:920,A:923,A:966,A:969,A:970,A:1003,A:1006,A:1007,A:1497,A:1531,A:1533,A:1534,A:1535,A:1538,A:1539,A:1541
```
you should get the same results.

> As I am running flexible docking calculations at the supercomputer and cannot fix the open babel error, I do not have the output normally printed at the console so I cannot compare the energy from the sdf file and the printed one.

The output can usually be found in your scheduler's output file. It is good practice IMHO to save the log file and to do that I usually pipe the output of SMINA/GNINA to a file using `tee`.
```bash
gnina -r rec.pdb -l lig.sdf --autobox_ligand alig.sdf | tee gnina.log
```

**Comment by beanik** [comment]
Now it is clear, thank you very much!
