### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by mbatgh** [gnina/gnina#140]
### Issue summary
nvlink fatal   : Could not open input file '/usr/lib/x86_64-linux-gnu/libpthread.a' (target: sm_86)

### Steps to reproduce
git clone ...
mkdir build
cd build
"cmake .." 
works
then "make"
I get:
[ 40%] Linking CUDA device code CMakeFiles/caffe.dir/cmake_device_link.o
nvlink warning : Skipping incompatible '/usr/lib/x86_64-linux-gnu/librt.a' when searching for -lrt (target: sm_86)
nvlink warning : Skipping incompatible '/usr/lib/x86_64-linux-gnu/libpthread.a' when searching for -lpthread (target: sm_86)
nvlink warning : Skipping incompatible '/usr/lib/x86_64-linux-gnu/libdl.a' when searching for -ldl (target: sm_86)
nvlink fatal   : Could not open input file '/usr/lib/x86_64-linux-gnu/libpthread.a' (target: sm_86)
make[2]: *** [caffe/src/caffe/CMakeFiles/caffe.dir/build.make:2787: caffe/src/caffe/CMakeFiles/caffe.dir/cmake_device_link.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1387: caffe/src/caffe/CMakeFiles/caffe.dir/all] Error 2
make: *** [Makefile:160: all] Error 2

any help/advice appreciatred!
thanks!
michael

### Your system configuration
Operating system: ubuntu 21.10
Compiler: gcc 10.3.0
CUDA version (if applicable): 11.4
CUDNN version (if applicable):
Python version: 3.9.7

**Comment by dkoes** [comment]
The system libraries are being reported as incompatible with the CUDA libraries.  Can you compile other CUDA code?

**Comment by mbatgh** [comment]
thanks for the swift reply.
I just compiled and ran gromacs, which definitely uses CUDA, and this appears to work without problems.
I assume the system setup I have (ubuntu 21.10, Cuda 11.4, gcc 10.3.0)  should be quite common.
Has anybody reported successful compilation of gnina with this or a similar setup?
cheers,
michael

**Comment by dkoes** [comment]
Can you provide the complete output of `make VERBOSE=1`

Do the incompatible libraries exist? Perhaps you are missing the static versions of these libraries.

**Comment by mbatgh** [comment]
output of make VERBOSE=1 is in the attached file err.gz

[err.gz](https://github.com/gnina/gnina/files/8196042/err.gz)

**Comment by dkoes** [comment]
What's the output of `objdump -a /usr/lib/x86_64-linux-gnu/librt.a`?

**Comment by mbatgh** [comment]
this is all i get ... 

prompt> objdump -a /usr/lib/x86_64-linux-gnu/librt.a
In archive /usr/lib/x86_64-linux-gnu/librt.a:

turns out this file is nearly empty, contains only a single string: "!<arch>"

what am i missing?

sorry to keep bothering you ;)

michael

**Comment by dkoes** [comment]
You should get something like this:
```
$ objdump -a /usr/lib/x86_64-linux-gnu/librt.a
In archive /usr/lib/x86_64-linux-gnu/librt.a:

aio_cancel.o:     file format elf64-x86-64
rw-r--r-- 0/0   2984 Dec 31 19:00 1969 aio_cancel.o


aio_error.o:     file format elf64-x86-64
rw-r--r-- 0/0   1632 Dec 31 19:00 1969 aio_error.o
...
```
with lots more included object files.  This file is provided by the libc6-dev package (on ubuntu):
```
$ dpkg -S /usr/lib/x86_64-linux-gnu/librt.a
libc6-dev:amd64: /usr/lib/x86_64-linux-gnu/librt.a
```

**Comment by mbatgh** [comment]
Thanks, dkoes, for your help  ... I don't seem to be the only one with this the problem, see:
https://www.reddit.com/r/archlinux/comments/sx33g4/whats_happened_to_librta/
https://forum.openwrt.org/t/where-are-libpthread-and-librt-on-target/82591
these are different architectures/distros, but apparently ubuntu has the same issue.
still searching for a solution...

**Comment by mbatgh** [comment]
BTW ... the binary version of gnina i downloaded does not seem to work as well on my system.
when i start the program with some test input (redocking of a single ligand to its receptor) the program
just starts using both my CPU and GPU (all of it), but does not provide any output (at least for several minutes,
then i did Ctrl-C) ... same with "--no_gpu"

I have:
prompt> ldd ~/bin/gnina
	linux-vdso.so.1 (0x00007ffdf6bda000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f25d3e78000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f25d3e73000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f25d3e6e000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f25d3c55000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f25d3b71000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f25d3b55000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f25d392d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f25d3e97000)

**Comment by dkoes** [comment]
Try the cuda-11.2 binary (https://github.com/gnina/gnina/releases/download/v1.0.1/gnina.cuda-11.2)

It sounds like changes were made to libc.  Maybe what is needed is upgrading to the newest version of cmake which hopefully has been updated to incorporate these changes and won't try to link to the legacy libraries (or possible what is needed is a even newer cuda with an nvlink that links to the right libraries).

**Comment by mbatgh** [comment]
if i use the downloaded binary (gnina.cuda-11.2) with gpu i get (after several minutes running):
 
gnina v1.0.1 HEAD:aa41230   Built Apr 13 2021.
gnina is based on smina and AutoDock Vina.
Please cite appropriately.

Commandline: gnina.cuda-11.2 -r 5tbmafixed.pdb -l 4redock.sdf --autobox_ligand 4redock.sdf --out xxxgpu112.sdf
Using random seed: 670073228

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
terminate called after throwing an instance of 'std::runtime_error'
  what():  CUDNN Error (out of memory?): CUDNN_STATUS_EXECUTION_FAILED
*** Aborted at 1646927037 (unix time) try "date -d @1646927037" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x3e8000011dc) received by PID 4572 (TID 0x7f2d120e9000) from PID 4572; stack trace: ***
    @     0x7f2d1c4df520 (unknown)
    @     0x7f2d1c533828 pthread_kill
    @     0x7f2d1c4df476 raise
    @     0x7f2d1c4c57b7 abort
    @     0x7f2d1c866a31 (unknown)
    @     0x7f2d1c8724ec (unknown)
    @     0x7f2d1c872557 std::terminate()
    @     0x7f2d1c8727f9 __cxa_throw
    @           0x7e174d caffe::CuDNNReLULayer<>::Forward_gpu()
    @           0x763751 caffe::Net<>::ForwardFromTo()
    @           0x763876 caffe::Net<>::Forward()
    @           0x536083 CNNScorer::score()
    @           0x4d7f1e get_cnn_info()
    @           0x4dccfd do_search()
    @           0x4dea47 main_procedure()
    @           0x4df37e threads_at_work()
    @           0x4f6db3 boost::_bi::list6<>::operator()<>()
    @           0x85aa54 thread_proxy
    @     0x7f2d1c531947 (unknown)
    @     0x7f2d1c5c1a44 clone
    @                0x0 (unknown)

in the error message it says something about out of memory but this seems strange, my machine has 68Gb, and this
is a single ligand in a small binding site...

with the older binary i get:

gnina v1.0 HEAD:6381355   Built Mar  6 2021.
gnina is based on smina and AutoDock Vina.
Please cite appropriately.

Commandline: gnina -r 5tbmafixed.pdb -l 4redock.sdf --autobox_ligand 4redock.sdf --out xxxgpu.sdf
Using random seed: 392518824

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
/tmp/libmolgrid/src/grid_maker.cu:288: no kernel image is available for execution on the deviceterminate called after throwing an instance of 'std::runtime_error'
  what():  CUDA Error: no kernel image is available for execution on the device
*** Aborted at 1646920418 (unix time) try "date -d @1646920418" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x3e800000ffc) received by PID 4092 (TID 0x7f91e1357640) from PID 4092; stack trace: ***
    @     0x7f91edeea520 (unknown)
    @     0x7f91edf3e828 pthread_kill
    @     0x7f91edeea476 raise
    @     0x7f91eded07b7 abort
    @     0x7f91ee271a31 (unknown)
    @     0x7f91ee27d4ec (unknown)
    @     0x7f91ee27d557 std::terminate()
    @     0x7f91ee27d7f9 __cxa_throw
    @           0xbcc1f4 libmolgrid::GridMaker::forward<>()
    @           0x661ec8 caffe::MolGridDataLayer<>::set_grid_minfo()
    @           0x65e607 caffe::MolGridDataLayer<>::forward()
    @           0x6e0261 caffe::Net<>::ForwardFromTo()
    @           0x6e0386 caffe::Net<>::Forward()
    @           0x4b30a3 CNNScorer::score()
    @           0x45446e get_cnn_info()
    @           0x45924d do_search()
    @           0x45af97 main_procedure()
    @           0x45b8ce threads_at_work()
    @           0x473303 boost::_bi::list6<>::operator()<>()
    @           0x7d74e4 thread_proxy
    @     0x7f91edf3c947 (unknown)
    @     0x7f91edfcca44 clone
    @                0x0 (unknown)


without gpu the binary works but takes about 10 minutes for redocking a single (fairly small and rigid) ligand to a an 
equally small binding site, on a computer with a fairly recent processor (AMD Ryzen 9 5900X 12-Core)
as in:

prompt> gnina -r 5tbmafixed.pdb -l 4redock.sdf --autobox_ligand 4redock.sdf --out nogpu.sdf --no_gpu > ernogpu

Is this kind of timing to be expected?

thanks!

**Comment by dkoes** [comment]
What is your GPU?

**Comment by mbatgh** [comment]
Geforce RTX 3080

**Comment by mbatgh** [comment]
I downgraded to ubuntu 20.04 ... works now.
lightning fast - thanks!

**Comment by dkoes** [comment]
@Luc1100 Can you figure out how to get gnina building on the latest ubuntu please?
