### ISSUE TITLE
van der Waals radius of the atoms

### ISSUE THREAD

**Issue by jaechang-hits** [gnina/gnina#141]
### Issue summary
What is the value of van der Waals radius of the atoms in gnina?
are they same as smina and vina?

### Your system configuration
Operating system:
Compiler:
CUDA version (if applicable):
CUDNN version (if applicable):
Python version:

**Comment by dkoes** [comment]
Yes.

**Comment by jaechang-hits** [comment]
@dkoes Thank you for the response.
Could you share the van der Waals radius of the atoms in gnina?

**Comment by dkoes** [comment]
If you run `gnina --print_atom_types` you will get
`atom_name ad_radius ad_depth ad_solvation ad_volume covalent_radius xs_radius xs_hydrophobe xs_donor xs_acceptor ad_heteroatom`

`xs_radius` is what is used by most potentials for computing optimal atom distances.

**Comment by jaechang-hits** [comment]
Thank you for the kind reply.
