### ISSUE TITLE
water

### ISSUE THREAD

**Issue by mbatgh** [gnina/gnina#143]
### Issue summary
Hi,
I successfully used gnina (the CPU version) for docking of ligands to a target - with good results.
However, the binding site contains (at least) one conserved water, and I noticed that I get
different results depending on whether I leave the water in the binding site (the input receptor pdb file) or not.
So, at least during docking, gnina seems to "see" the water, but what about the scoring stage?
And will the way water is dealt with differ, depending on whether I use cnn or vinardo for scoring?
When I tried to understand how gnina deals with water  I came up empty handed  - neither in the original
publication nor anywhere on the github web page, nor in the source (as far as I managed to read/understand it)
I found anything on this topic. Can anybody give me a hint, a link, or a reference on how gnina deals with
water molecules in the binding site, both, during the docking and the scoring stages?
thanks!
Michael

### Your system configuration
Operating system: Ubuntu 20.04.4 LTS
Compiler: gcc  9.4.0
CUDA version (if applicable):
CUDNN version (if applicable):
Python version: Python 3.8.10

**Comment by dkoes** [comment]
The water is treated as part of the receptor.  It has the same potentials as an OxygenDonorAcceptor on the receptor.
