### ISSUE TITLE
process 1000+ moleculars in one command

### ISSUE THREAD

**Issue by cooper87** [gnina/gnina#144]
### Issue summary
Hi, when I need to test 1000+ molecular with one protein receptor,  then I should execute  1000+ times command  which likely ```gnina -r rec.pdb -l lig.sdf --autobox_ligand ```.

Is there a plan for process batch moleculars one command? Batch process will reduce time cost.

**Comment by dkoes** [comment]
Put all the molecules in lig.sdf.
