### ISSUE TITLE
installation problem on mac: Failed to find nvcc

### ISSUE THREAD

**Issue by rczerminski-valo** [gnina/gnina#145]
### Issue summary

```
$ cmake ..
-- The C compiler identification is AppleClang 12.0.5.12050022
-- The CXX compiler identification is AppleClang 12.0.5.12050022
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.23/Modules/CMakeDetermineCUDACompiler.cmake:180 (message):
  Failed to find nvcc.

  Compiler requires the CUDA toolkit.  Please set the CUDAToolkit_ROOT
  variable.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

-- Configuring incomplete, errors occurred!
```

### Steps to reproduce

`$ cmake ..` on Mac

### Your system configuration
Operating system: macOS BigSur (11.2.3)
Compiler:
CUDA version (if applicable):
CUDNN version (if applicable):
Python version:

Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro16,1
  Processor Name:	6-Core Intel Core i7
  Processor Speed:	2.6 GHz
  Number of Processors:	1
  Total Number of Cores:	6
  L2 Cache (per Core):	256 KB
  L3 Cache:	12 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
  System Firmware Version:	1554.80.3.0.0 (iBridge: 18.16.14347.0.0,0)

**Comment by dkoes** [comment]
Mac is not supported.
