### ISSUE TITLE
install error on Centos7

### ISSUE THREAD

**Issue by HyungSik-Jo** [gnina/gnina#146]
### Issue summary
Could NOT find RDKit (missing:  RDKIT_INCLUDE_DIR RDKIT_LIBRARIES) 
CMake Warning at gninasrc/CMakeLists.txt:154 (message):
  RDKIT not found.  gninavis will NOT be built.

CMake Error in caffe/src/caffe/CMakeLists.txt:
  Target "caffe" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/home/molgrid-gnina/gnina/build/external/gflags-install/include"

  which is prefixed in the build directory.

### Steps to reproduce
The command in use is: 
`cmake -D CMAKE_CUDA_COMPILER:PATH=/usr/local/cuda-11.5/bin/nvcc -D BOOST_ROOT=/usr/include/boost_1_59 -D BLAS=open ..`

The error that is occurring is:
openbabel BINARY_DIR = /home/molgrid-gnina/gnina/build
openbabel BINARY_DIR = /home/molgrid-gnina/gnina/build
openbabel IMPORTED = TRUE
openbabel IMPORTED_CONFIGURATIONS = RELEASE
openbabel IMPORTED_GLOBAL = FALSE
openbabel INTERFACE_LINK_LIBRARIES = /usr/lib64/libm.so;dl;/usr/lib64/libz.so;Threads::Threads
openbabel NAME = openbabel
openbabel POSITION_INDEPENDENT_CODE = True
openbabel SOURCE_DIR = /home/molgrid-gnina/gnina
openbabel SOURCE_DIR = /home/molgrid-gnina/gnina
openbabel TYPE = SHARED_LIBRARY
openbabel TYPE = SHARED_LIBRARY
-- Could NOT find libmolgrid (missing:  LIBMOLGRID_INCLUDE_DIR LIBMOLGRID_LIBRARY) 
libmolgrid will be fetched from git
-- CUDA detected: 11.5
-- Added CUDA NVCC flags for: sm_35 sm_50 sm_60 sm_61 sm_70 sm_75
-- Found Boost: /usr/include/boost_1_59/include (found suitable version "1.59.0", minimum required is "1.54") found components: system thread filesystem iostreams timer chrono date_time atomic regex 
-- Could NOT find GFlags (missing:  GFLAGS_INCLUDE_DIR GFLAGS_LIBRARY) 
-- Found glog    (include: /usr/include, library: /usr/lib64/libglog.so)
-- Found PROTOBUF Compiler: /usr/bin/protoc
-- CUDA detected: 11.5
-- Added CUDA NVCC flags for: sm_35 sm_50 sm_60 sm_61 sm_70 sm_75
-- Found OpenBLAS libraries: /usr/lib64/libopenblas.so
-- Found OpenBLAS include: /usr/include
-- Found PythonInterp: /home/johyungsik/anaconda3/envs/gnina2/bin/python3 (found suitable version "3.7.13", minimum required is "3.0") 
-- NumPy ver. 1.21.5 found (include: /home/johyungsik/anaconda3/envs/gnina2/lib/python3.7/site-packages/numpy/core/include)
-- Could NOT find Boost (missing: python37) (found suitable version "1.59.0", minimum required is "1.58")
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- 
-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version           :   1.0.0
--   Git               :   v1.0.1-53-gb9ae032-dirty
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -Wno-deprecated-declarations -Wno-unknown-pragmas -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -Wno-deprecated-declarations -Wno-unknown-pragmas -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release
-- 
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   ON
--   CPU_ONLY          :   OFF
--   USE_OPENCV        :   0
--   USE_LEVELDB       :   0
--   USE_LMDB          :   0
--   USE_NCCL          :   OFF
--   ALLOW_LMDB_NOLOCK :   OFF
-- 
-- Dependencies:
--   BLAS              :   Yes (open)
--   Boost             :   Yes (ver. 1.59)
--   glog              :   Yes
--   gflags            :   Yes
--   OpenBabel         :   No
--   protobuf          :   Yes (ver. 2.5.0)
--   CUDA              :   Yes (ver. 11.5)
-- 
-- NVIDIA CUDA:
--   Target GPU(s)     :   All
--   GPU arch(s)       :   sm_35 sm_50 sm_60 sm_61 sm_70 sm_75
--   cuDNN             :   Not found
-- 
-- Python:
--   Interpreter       :   /home/johyungsik/anaconda3/envs/gnina2/bin/python3 (ver. 3.7.13)
--   Libraries         :   /home/johyungsik/anaconda3/envs/gnina2/lib/libpython3.7m.so (ver 3.7.13)
--   NumPy             :   /home/johyungsik/anaconda3/envs/gnina2/lib/python3.7/site-packages/numpy/core/include (ver 1.21.5)
-- 
-- Documentaion:
--   Doxygen           :   No
--   config_file       :   
-- 
-- Install:
--   Install path      :   /usr/local
-- 
-- Found Boost: /usr/include/boost_1_59/include (found version "1.59.0") found components: program_options system iostreams timer thread serialization filesystem date_time regex unit_test_framework chrono atomic 
-- Could NOT find RDKit (missing:  RDKIT_INCLUDE_DIR RDKIT_LIBRARIES) 
CMake Warning at gninasrc/CMakeLists.txt:154 (message):
  RDKIT not found.  gninavis will NOT be built.

-- Found Boost: /usr/include/boost_1_59/include (found version "1.59.0") found components: unit_test_framework system 
-- Found PythonInterp: /home/johyungsik/anaconda3/envs/gnina2/bin/python3 (found version "3.7.13") 
-- Configuring done
CMake Error in caffe/src/caffe/CMakeLists.txt:
  Target "caffe" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/home/molgrid-gnina/gnina/build/external/gflags-install/include"

  which is prefixed in the build directory.

CMake Error in caffe/src/caffe/CMakeLists.txt:
  Target "caffe" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/home/molgrid-gnina/gnina/build/external/gflags-install/include"

  which is prefixed in the build directory.Target "caffe"
  INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/home/molgrid-gnina/gnina/build/external/gflags-install/include"

  which is prefixed in the source directory.

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

I have two questions.
1. I installed rdkit from conda, but cmake doesn't seem to find that path. Is there any way to fix it?
2. It seems that caffe cannot be installed in the process. Is there any part that can be edited?

### Your system configuration
Operating system: Centos 7
Compiler:
CUDA version (if applicable): 11.5 
CUDNN version (if applicable):
Python version: 3.7

**Comment by dkoes** [comment]
RDKit is an optional dependency anyway, but you can set the appropriate cmake variable (RDKIT_INCLUDE_DIR RDKIT_LIBRARIES) to the necessary paths.

@Luc1100 can you see if you can reproduce the include dir error?

**Comment by HyungSik-Jo** [comment]
@dkoes Thank you for quick response.

In the end, I finished the configuration using the docker image distributed today.

There seem to be several problems with settings in environments with different os.

In addition, molgrid and openbabel are missing in docker, so I installed it with anaconda and confirmed that it works.

Hope it helps in your work.
