### ISSUE TITLE
make errors

### ISSUE THREAD

**Issue by ralphleeAI** [gnina/gnina#148]
### Issue summary
[ 75%] Built target test_grid_cu
[ 76%] Linking CXX executable ../bin/test_gridmaker_cpp
/usr/bin/ld: ../lib/libmolgrid.a(coord_cache.cpp.o): in function `boost::filesystem::path::append(boost::filesystem::path const&)':
/usr/local/include/boost/filesystem/path.hpp:596: undefined reference to `boost::filesystem::path::append_v3(boost::filesystem::path const&)'
/usr/bin/ld: /usr/local/include/boost/filesystem/path.hpp:596: undefined reference to `boost::filesystem::path::append_v3(boost::filesystem::path const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [test/CMakeFiles/test_gridmaker_cpp.dir/build.make:108: bin/test_gridmaker_cpp] Error 1
make[1]: *** [CMakeFiles/Makefile2:1086: test/CMakeFiles/test_gridmaker_cpp.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

### Your system configuration
Operating system:ubuntu 20.04
Compiler: 
CUDA version (if applicable):11.7
CUDNN version (if applicable):none
Python version:3.8

**Comment by dkoes** [comment]
You need to tell cmake where to find your boost libraries.

**Comment by ralphleeAI** [comment]
Hi dkos, I have solved this issue,  I degrade cuda version to 11.6 which is same with the drivers and re build, and it works.
