### ISSUE TITLE
gnina not installing with cuda 11.7

### ISSUE THREAD

**Issue by Nick-Mul** [gnina/gnina#149]
### Issue summary

I have to gnina as a docker/podman container (if I want to use a GPU) the machine is set up with Cuda11.7. I've edited the dockerfile to 
FROM docker pull nvidia/cuda:11.7.0-devel-ubuntu18.04

seems to go well until the very last step of gnina build: 

[ 96%] Built target test_grid_cu
[ 98%] Linking CXX shared library molgrid/molgrid.so
[ 98%] Built target molgrid

the molgrid step seems to freeze, no exit errors just 1hr + ?! Any ideas on what I should do? Different version of cmake?

### Steps to reproduce
edited docker file to
FROM docker pull nvidia/cuda:11.7.0-devel-ubuntu18.04

### Your system configuration
Operating system:
Compiler:
CUDA version (if applicable): 
CUDNN version (if applicable):
Python version:

**Comment by dkoes** [comment]
Try running with `make -DVERBOSE=1` and then share the output.

**Comment by Nick-Mul** [comment]
Looks like it could be CUDNN issue? Either not be present (I thought this was include in the devel image) or maybe that cuda 11.7 only works with CUDNN  >8 ?    

TEP 6/6: RUN git clone https://github.com/gnina/gnina.git;     cd gnina; mkdir build; cd build;     cmake -DVERBOSE=1 .. ;    make -j4 ; make -DVERBOSE=1 install
Cloning into 'gnina'...
Checking out files: 100% (1463/1463), done.
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- The CUDA compiler identification is NVIDIA 11.7.64
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CUDA: /usr/local/cuda (found suitable version "11.7", minimum required is "9.0")
openbabel AUTOGEN_ORIGIN_DEPENDS = ON
openbabel AUTOMOC_COMPILER_PREDEFINES = ON
openbabel AUTOMOC_MACRO_NAMES = Q_OBJECT;Q_GADGET;Q_NAMESPACE;Q_NAMESPACE_EXPORT
openbabel AUTOMOC_PATH_PREFIX = OFF
openbabel BINARY_DIR = /root/gnina/build
openbabel BINARY_DIR = /root/gnina/build
openbabel BUILD_WITH_INSTALL_RPATH = OFF
openbabel CUDA_SEPARABLE_COMPILATION = ON
openbabel CUDA_STANDARD = 14
openbabel CXX_STANDARD = 14
openbabel IMPORTED = TRUE
openbabel IMPORTED_CONFIGURATIONS = RELEASE
openbabel IMPORTED_GLOBAL = FALSE
openbabel INSTALL_RPATH = /usr/local/lib
openbabel INSTALL_RPATH_USE_LINK_PATH = OFF
openbabel INTERFACE_LINK_LIBRARIES = /usr/lib/x86_64-linux-gnu/libm.so;dl;/usr/lib/x86_64-linux-gnu/libz.so;Threads::Threads
openbabel NAME = openbabel
openbabel PCH_WARN_INVALID = ON
openbabel POSITION_INDEPENDENT_CODE = True
openbabel SKIP_BUILD_RPATH = OFF
openbabel SOURCE_DIR = /root/gnina
openbabel SOURCE_DIR = /root/gnina
openbabel TYPE = SHARED_LIBRARY
openbabel TYPE = SHARED_LIBRARY
openbabel UNITY_BUILD_BATCH_SIZE = 8
openbabel UNITY_BUILD_MODE = BATCH
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
-- Could NOT find libmolgrid (missing:  LIBMOLGRID_INCLUDE_DIR LIBMOLGRID_LIBRARY)
libmolgrid will be fetched from git
-- Found Git: /usr/bin/git (found version "2.17.1")
-- Found Python: /usr/bin/python3.6 (found version "3.6.9") found components: Interpreter Development Development.Module Development.Embed
-- CUDA detected: 11.7
-- Automatic GPU detection failed. Building for all known architectures.
-- Added CUDA NVCC flags for: sm_35 sm_50 sm_60 sm_61 sm_70 sm_75
-- Found Boost: /usr/include (found suitable version "1.65.1", minimum required is "1.54") found components: system thread filesystem iostreams timer chrono date_time atomic regex
-- Found libmolgrid: /root/gnina/build/external/include
-- Found GFlags: /usr/include
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found Glog: /usr/include
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found version "3.0.0")
-- Found PROTOBUF Compiler: /usr/bin/protoc
-- Found HDF5: /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_cpp.so;/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "1.10.0.1") found components: HL
-- CUDA detected: 11.7
-- Automatic GPU detection failed. Building for all known architectures.
-- Added CUDA NVCC flags for: sm_35 sm_50 sm_60 sm_61 sm_70 sm_75
-- Found Atlas: /usr/include/x86_64-linux-gnu
-- Found Atlas (include: /usr/include/x86_64-linux-gnu library: /usr/lib/x86_64-linux-gnu/libatlas.so lapack: /usr/lib/x86_64-linux-gnu/liblapack.so
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.9", minimum required is "3.0")
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found suitable version "3.6.9", minimum required is "3.0")
-- Found NumPy: /usr/lib/python3/dist-packages/numpy/core/include (found suitable version "1.13.3", minimum required is "1.7.1")
-- NumPy ver. 1.13.3 found (include: /usr/lib/python3/dist-packages/numpy/core/include)
-- Found Boost: /usr/include (found suitable version "1.65.1", minimum required is "1.58") found components: python36
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
--
-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version           :   1.0.0
--   Git               :   v1.0.1-60-gbfd5a5c5
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -Wno-deprecated-declarations -Wno-unknown-pragmas -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -Wno-deprecated-declarations -Wno-unknown-pragmas -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release
--
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   ON
--   CPU_ONLY          :   OFF
--   USE_OPENCV        :   0
--   USE_LEVELDB       :   0
--   USE_LMDB          :   0
--   USE_NCCL          :   OFF
--   ALLOW_LMDB_NOLOCK :   OFF
--
-- Dependencies:
--   BLAS              :   Yes (Atlas)
--   Boost             :   Yes (ver. 1.65)
--   glog              :   Yes
--   gflags            :   Yes
--   OpenBabel         :   No
--   protobuf          :   Yes (ver. 3.0.0)
--   CUDA              :   Yes (ver. 11.7)
--
-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_35 sm_50 sm_60 sm_61 sm_70 sm_75
--   cuDNN             :   Not found
--
-- Python:
--   Interpreter       :   /usr/bin/python3 (ver. 3.6.9)
--   Libraries         :   /usr/lib/x86_64-linux-gnu/libpython3.6m.so (ver 3.6.9)
--   NumPy             :   /usr/lib/python3/dist-packages/numpy/core/include (ver 1.13.3)
--
-- Documentaion:
--   Doxygen           :   No
--   config_file       :
--
-- Install:
--   Install path      :   /usr/local
--
-- Found Boost: /usr/include (found version "1.65.1") found components: program_options system iostreams timer thread serialization filesystem date_time regex unit_test_framework chrono atomic
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- Found RDKit include files at /usr/include/rdkit
-- Found RDKit libraries at /usr/lib
-- Found RDKit library files at /usr/lib/libFileParsers.so;/usr/lib/libSmilesParse.so;/usr/lib/libSubstructMatch.so;/usr/lib/libGraphMol.so;/usr/lib/libRDGeometryLib.so;/usr/lib/libRDGeneral.so;/usr/lib/libSubgraphs.so;/usr/lib/libDataStructs.so;/usr/lib/libDepictor.so
-- Found RDKit: /usr/include/rdkit
-- Found Boost: /usr/include (found version "1.65.1") found components: unit_test_framework system
-- Found PythonInterp: /usr/bin/python3 (found version "3.6.9")
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    VERBOSE


-- Build files have been written to: /root/gnina/build
[  0%] Running C++/Python protocol buffer compiler on /root/gnina/caffe/src/caffe/proto/caffe.proto
Scanning dependencies of target libmolgrid
[  0%] Creating directories for 'libmolgrid'
[  1%] Performing download step (git clone) for 'libmolgrid'
Cloning into 'libmolgrid'...
Scanning dependencies of target caffeproto
[  1%] Building CXX object caffe/src/caffe/CMakeFiles/caffeproto.dir/__/__/include/caffe/proto/caffe.pb.cc.o
Already on 'master'
Your branch is up to date with 'origin/master'.
[  1%] Performing update step for 'libmolgrid'
[  1%] No patch step for 'libmolgrid'
[  1%] Performing configure step for 'libmolgrid'
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- The CUDA compiler identification is NVIDIA 11.7.64
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Found Git: /usr/bin/git
-- Current git revision is bfd5a5c5121527beea48ce9ed729f2b04c02a2a7
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CUDA: /usr/local/cuda (found version "11.7")
-- Found Boost: /usr/include (found version "1.65.1") found components: regex unit_test_framework program_options system filesystem iostreams
-- Found Open Babel include files at /usr/local/include/openbabel3
-- Found Open Babel library at /usr/local/lib/libopenbabel.so
Setting openbabel found TRUE
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found version "3.6.9")
-- Found PythonInterp: /usr/bin/python3.6 (found version "3.6.9")
-- Found Boost: /usr/include (found version "1.65.1") found components: system filesystem python36
-- Found NumPy: /usr/lib/python3/dist-packages/numpy/core/include (found version "1.13.3")
-- Found Boost: /usr/include (found version "1.65.1") found components: unit_test_framework system
-- Configuring done
-- Generating done
-- Build files have been written to: /root/gnina/build/libmolgrid-prefix/src/libmolgrid-build
[  1%] Performing build step for 'libmolgrid'
Scanning dependencies of target libmolgrid_shared
Scanning dependencies of target libmolgrid_static
[  1%] Building CXX object src/CMakeFiles/libmolgrid_shared.dir/libmolgrid.cpp.o
[  3%] Building CXX object src/CMakeFiles/libmolgrid_shared.dir/atom_typer.cpp.o
[  4%] Building CXX object src/CMakeFiles/libmolgrid_static.dir/libmolgrid.cpp.o
[  6%] Building CXX object src/CMakeFiles/libmolgrid_static.dir/atom_typer.cpp.o
[  7%] Building CXX object src/CMakeFiles/libmolgrid_static.dir/example.cpp.o
[  9%] Building CXX object src/CMakeFiles/libmolgrid_shared.dir/example.cpp.o
[  1%] Linking CXX static library ../../lib/libcaffeproto.a
[  1%] Built target caffeproto
[ 10%] Building CXX object src/CMakeFiles/libmolgrid_shared.dir/exampleref_providers.cpp.o
[ 12%] Building CXX object src/CMakeFiles/libmolgrid_static.dir/exampleref_providers.cpp.o
[ 14%] Building CXX object src/CMakeFiles/libmolgrid_static.dir/example_extractor.cpp.o
[ 15%] Building CXX object src/CMakeFiles/libmolgrid_static.dir/example_provider.cpp.o
[ 17%] Building CXX object src/CMakeFiles/libmolgrid_shared.dir/example_extractor.cpp.o
[ 18%] Building CXX object src/CMakeFiles/libmolgrid_shared.dir/example_provider.cpp.o
[ 20%] Building CXX object src/CMakeFiles/libmolgrid_shared.dir/example_dataset.cpp.o
[ 21%] Building CXX object src/CMakeFiles/libmolgrid_static.dir/example_dataset.cpp.o
[ 23%] Building CXX object src/CMakeFiles/libmolgrid_static.dir/grid_maker.cpp.o
[ 25%] Building CUDA object src/CMakeFiles/libmolgrid_static.dir/grid_maker.cu.o
[ 26%] Building CXX object src/CMakeFiles/libmolgrid_static.dir/coordinateset.cpp.o
[ 28%] Building CXX object src/CMakeFiles/libmolgrid_shared.dir/grid_maker.cpp.o
[ 29%] Building CUDA object src/CMakeFiles/libmolgrid_shared.dir/grid_maker.cu.o
[ 31%] Building CUDA object src/CMakeFiles/libmolgrid_static.dir/coordinateset.cu.o
[ 32%] Building CXX object src/CMakeFiles/libmolgrid_static.dir/coord_cache.cpp.o
[ 34%] Building CXX object src/CMakeFiles/libmolgrid_shared.dir/coordinateset.cpp.o
[ 35%] Building CXX object src/CMakeFiles/libmolgrid_static.dir/transform.cpp.o
[ 37%] Building CUDA object src/CMakeFiles/libmolgrid_shared.dir/coordinateset.cu.o
[ 39%] Building CXX object src/CMakeFiles/libmolgrid_shared.dir/coord_cache.cpp.o
[ 40%] Building CUDA object src/CMakeFiles/libmolgrid_static.dir/transform.cu.o
[ 42%] Building CXX object src/CMakeFiles/libmolgrid_static.dir/grid_io.cpp.o
[ 43%] Building CXX object src/CMakeFiles/libmolgrid_shared.dir/transform.cpp.o
[ 45%] Building CUDA object src/CMakeFiles/libmolgrid_shared.dir/transform.cu.o
[ 46%] Building CXX object src/CMakeFiles/libmolgrid_shared.dir/grid_io.cpp.o
[ 48%] Building CXX object src/CMakeFiles/libmolgrid_shared.dir/grid_interpolater.cpp.o
[ 50%] Building CXX object src/CMakeFiles/libmolgrid_static.dir/grid_interpolater.cpp.o
[ 51%] Building CUDA object src/CMakeFiles/libmolgrid_static.dir/grid_interpolater.cu.o
[ 53%] Building CXX object src/CMakeFiles/libmolgrid_static.dir/cartesian_grid.cpp.o
[ 54%] Building CUDA object src/CMakeFiles/libmolgrid_shared.dir/grid_interpolater.cu.o
[ 56%] Building CXX object src/CMakeFiles/libmolgrid_shared.dir/cartesian_grid.cpp.o
[ 57%] Linking CXX static library ../lib/libmolgrid.a
[ 57%] Built target libmolgrid_static
Scanning dependencies of target test_gridmaker_cpp
[ 59%] Building CXX object test/CMakeFiles/test_gridmaker_cpp.dir/test_gridmaker.cpp.o
Scanning dependencies of target test_transform_cu
[ 60%] Building CUDA object test/CMakeFiles/test_transform_cu.dir/test_transform.cu.o
Scanning dependencies of target test_mgrid_cu
[ 62%] Building CUDA object test/CMakeFiles/test_mgrid_cu.dir/test_mgrid.cu.o
[ 64%] Linking CXX shared library ../lib/libmolgrid.so
[ 64%] Built target libmolgrid_shared
Scanning dependencies of target test_grid_cpp
[ 65%] Building CXX object test/CMakeFiles/test_grid_cpp.dir/test_grid.cpp.o
[ 67%] Linking CXX executable ../bin/test_grid_cpp
[ 67%] Built target test_grid_cpp
Scanning dependencies of target test_gridmaker_cu
[ 68%] Building CUDA object test/CMakeFiles/test_gridmaker_cu.dir/test_gridmaker.cu.o
[ 70%] Linking CXX executable ../bin/test_gridmaker_cpp
[ 70%] Built target test_gridmaker_cpp
Scanning dependencies of target test_gridinterp_cpp
[ 71%] Building CXX object test/CMakeFiles/test_gridinterp_cpp.dir/test_gridinterp.cpp.o
[ 73%] Linking CXX executable ../bin/test_gridinterp_cpp
[ 73%] Built target test_gridinterp_cpp
Scanning dependencies of target test_grid_cu
[ 75%] Building CUDA object test/CMakeFiles/test_grid_cu.dir/test_grid.cu.o
[ 76%] Linking CXX executable ../bin/test_transform_cu
[ 76%] Built target test_transform_cu
Scanning dependencies of target test_mgrid_cpp
[ 78%] Building CXX object test/CMakeFiles/test_mgrid_cpp.dir/test_mgrid.cpp.o
[ 79%] Linking CXX executable ../bin/test_mgrid_cu
[ 79%] Built target test_mgrid_cu
Scanning dependencies of target test_quaternion_cpp
[ 81%] Building CXX object test/CMakeFiles/test_quaternion_cpp.dir/test_quaternion.cpp.o
[ 82%] Linking CXX executable ../bin/test_mgrid_cpp
[ 82%] Built target test_mgrid_cpp
Scanning dependencies of target test_coordinateset_cpp
[ 84%] Building CXX object test/CMakeFiles/test_coordinateset_cpp.dir/test_coordinateset.cpp.o
[ 85%] Linking CXX executable ../bin/test_quaternion_cpp
[ 85%] Built target test_quaternion_cpp
Scanning dependencies of target test_transform_cpp
[ 87%] Building CXX object test/CMakeFiles/test_transform_cpp.dir/test_transform.cpp.o
[ 89%] Linking CXX executable ../bin/test_coordinateset_cpp
[ 89%] Built target test_coordinateset_cpp
[ 90%] Inserting docstrings binding.cpp
Scanning dependencies of target molgrid
[ 92%] Building CXX object python/CMakeFiles/molgrid.dir/bindings.cpp.o
[ 93%] Linking CXX executable ../bin/test_transform_cpp
[ 93%] Built target test_transform_cpp
[ 95%] Building CXX object python/CMakeFiles/molgrid.dir/bindings_grids.cpp.o
[ 96%] Linking CXX executable ../bin/test_grid_cu
[ 96%] Built target test_grid_cu
[ 98%] Linking CXX shared library molgrid/molgrid.so
[ 98%] Built target molgrid

**Comment by dkoes** [comment]
You need to pass -DVERBOSE to `make`, not `cmake` so you can see what is happening during the build process.

**Comment by EricDeveaud** [comment]
same problem here whith gnina-1.0.1

```
[ 97%] Built target gninaserver
/opt/gensoft/src/gnina/gnina-1.0.1/test/../gninasrc/lib/gpu_util.h(18): warning #1444-D: function "cudaDeviceSynchronize"
/opt/gensoft/exe/cuda/11.7/include/cuda_device_runtime_api.h(142): here was declared deprecated ("Use of cudaDeviceSynchronize from device code is deprecated and will not be supported in a future release. Disable this warning with -D__CDPRT_SUPPRESS_SYNC_DEPRECATION_WARNING.")

/opt/gensoft/src/gnina/gnina-1.0.1/test/../gninasrc/lib/gpu_util.h(18): warning #1444-D: function "cudaDeviceSynchronize"
/opt/gensoft/exe/cuda/11.7/include/cuda_device_runtime_api.h(142): here was declared deprecated ("Use of cudaDeviceSynchronize from device code is deprecated and will not be supported in a future release. Disable this warning with -D__CDPRT_SUPPRESS_SYNC_DEPRECATION_WARNING.")

/opt/gensoft/src/gnina/gnina-1.0.1/test/../gninasrc/lib/gpu_util.h(18): warning #1444-D: function "cudaDeviceSynchronize"
/opt/gensoft/exe/cuda/11.7/include/cuda_device_runtime_api.h(142): here was declared deprecated ("Use of cudaDeviceSynchronize from device code is deprecated and will not be supported in a future release. Disable this warning with -D__CDPRT_SUPPRESS_SYNC_DEPRECATION_WARNING.")

/opt/gensoft/src/gnina/gnina-1.0.1/test/../gninasrc/lib/gpu_util.h(18): warning #1444-D: function "cudaDeviceSynchronize"
/opt/gensoft/exe/cuda/11.7/include/cuda_device_runtime_api.h(142): here was declared deprecated ("Use of cudaDeviceSynchronize from device code is deprecated and will not be supported in a future release. Disable this warning with -D__CDPRT_SUPPRESS_SYNC_DEPRECATION_WARNING.")

/opt/gensoft/src/gnina/gnina-1.0.1/test/../gninasrc/lib/gpu_util.h(18): warning #1444-D: function "cudaDeviceSynchronize"
/opt/gensoft/exe/cuda/11.7/include/cuda_device_runtime_api.h(142): here was declared deprecated ("Use of cudaDeviceSynchronize from device code is deprecated and will not be supported in a future release. Disable this warning with -D__CDPRT_SUPPRESS_SYNC_DEPRECATION_WARNING.")

/opt/gensoft/src/gnina/gnina-1.0.1/test/../gninasrc/lib/gpu_util.h(18): warning #1444-D: function "cudaDeviceSynchronize"
/opt/gensoft/exe/cuda/11.7/include/cuda_device_runtime_api.h(142): here was declared deprecated ("Use of cudaDeviceSynchronize from device code is deprecated and will not be supported in a future release. Disable this warning with -D__CDPRT_SUPPRESS_SYNC_DEPRECATION_WARNING.")

/opt/gensoft/src/gnina/gnina-1.0.1/test/../gninasrc/lib/gpu_util.h(18): warning #1444-D: function "cudaDeviceSynchronize"
/opt/gensoft/exe/cuda/11.7/include/cuda_device_runtime_api.h(142): here was declared deprecated ("Use of cudaDeviceSynchronize from device code is deprecated and will not be supported in a future release. Disable this warning with -D__CDPRT_SUPPRESS_SYNC_DEPRECATION_WARNING.")

/opt/gensoft/src/gnina/gnina-1.0.1/test/../gninasrc/lib/gpu_util.h(18): warning #1444-D: function "cudaDeviceSynchronize"
/opt/gensoft/exe/cuda/11.7/include/cuda_device_runtime_api.h(142): here was declared deprecated ("Use of cudaDeviceSynchronize from device code is deprecated and will not be supported in a future release. Disable this warning with -D__CDPRT_SUPPRESS_SYNC_DEPRECATION_WARNING.")

/opt/gensoft/src/gnina/gnina-1.0.1/test/../gninasrc/lib/gpu_util.h(18): warning #1444-D: function "cudaDeviceSynchronize"
/opt/gensoft/exe/cuda/11.7/include/cuda_device_runtime_api.h(142): here was declared deprecated ("Use of cudaDeviceSynchronize from device code is deprecated and will not be supported in a future release. Disable this warning with -D__CDPRT_SUPPRESS_SYNC_DEPRECATION_WARNING.")

/opt/gensoft/src/gnina/gnina-1.0.1/test/../gninasrc/lib/gpu_util.h(18): warning #1444-D: function "cudaDeviceSynchronize"
/opt/gensoft/exe/cuda/11.7/include/cuda_device_runtime_api.h(142): here was declared deprecated ("Use of cudaDeviceSynchronize from device code is deprecated and will not be supported in a future release. Disable this warning with -D__CDPRT_SUPPRESS_SYNC_DEPRECATION_WARNING.")

/opt/gensoft/src/gnina/gnina-1.0.1/test/../gninasrc/lib/gpu_util.h(18): warning #1444-D: function "cudaDeviceSynchronize"
/opt/gensoft/exe/cuda/11.7/include/cuda_device_runtime_api.h(142): here was declared deprecated ("Use of cudaDeviceSynchronize from device code is deprecated and will not be supported in a future release. Disable this warning with -D__CDPRT_SUPPRESS_SYNC_DEPRECATION_WARNING.")

/opt/gensoft/src/gnina/gnina-1.0.1/test/../gninasrc/lib/gpu_util.h(18): warning #1444-D: function "cudaDeviceSynchronize"
/opt/gensoft/exe/cuda/11.7/include/cuda_device_runtime_api.h(142): here was declared deprecated ("Use of cudaDeviceSynchronize from device code is deprecated and will not be supported in a future release. Disable this warning with -D__CDPRT_SUPPRESS_SYNC_DEPRECATION_WARNING.")

^C
Compilation terminated.

```

regards 
eric

**Comment by EricDeveaud** [comment]
sorry  previous log is useless (parallel build.... it misses a lot of information....)
here is a more relevant one.

```
make[3]: Entering directory '/tmp/build/gnina/1.0.1'
[ 97%] Building CUDA object test/gnina/CMakeFiles/gninacheck.dir/test_cache.cu.o
cd /tmp/build/gnina/1.0.1/test/gnina && /opt/gensoft/exe/cuda/11.7/bin/nvcc -forward-unknown-to-host-compiler -DBOOST_ALL_NO_LIB -DBOOST_CHRONO_DYN_LINK -DBOOST_DATE_TIME_DYN_LINK -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_IOSTREAMS_DYN_LINK -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_PYTHON_DYN_LINK -DBOOST_REGEX_DYN_LINK -DBOOST_SERIALIZATION_DYN_LINK -DBOOST_SYSTEM_DYN_LINK -DBOOST_THREAD_DYN_LINK -DBOOST_TIMER_DYN_LINK -DBOOST_UNIT_TEST_FRAMEWORK_DYN_LINK -I/opt/gensoft/exe/openbabel/3.1.1/include/openbabel3 -I/opt/gensoft/src/gnina/gnina-1.0.1/. -I/tmp/build/gnina/1.0.1/caffe/include -I/opt/gensoft/src/gnina/gnina-1.0.1/caffe/include -I/opt/gensoft/src/gnina/gnina-1.0.1/test/../gninasrc/lib -I/opt/gensoft/src/gnina/gnina-1.0.1/test/../gninavis -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=sm_75 -O3 -DNDEBUG -std=c++14 -x cu -dc /opt/gensoft/src/gnina/gnina-1.0.1/test/gnina/test_cache.cu -o CMakeFiles/gninacheck.dir/test_cache.cu.o
nvcc warning : The 'compute_35', 'compute_37', 'sm_35', and 'sm_37' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/opt/gensoft/src/gnina/gnina-1.0.1/test/../gninasrc/lib/gpu_util.h(18): warning #1444-D: function "cudaDeviceSynchronize"
/opt/gensoft/exe/cuda/11.7/include/cuda_device_runtime_api.h(142): here was declared deprecated ("Use of cudaDeviceSynchronize from device code is deprecated and will not be supported in a future release. Disable this warning with -D__CDPRT_SUPPRESS_SYNC_DEPRECATION_WARNING.")

/opt/gensoft/src/gnina/gnina-1.0.1/test/../gninasrc/lib/gpu_util.h(18): warning #1444-D: function "cudaDeviceSynchronize"
/opt/gensoft/exe/cuda/11.7/include/cuda_device_runtime_api.h(142): here was declared deprecated ("Use of cudaDeviceSynchronize from device code is deprecated and will not be supported in a future release. Disable this warning with -D__CDPRT_SUPPRESS_SYNC_DEPRECATION_WARNING.")

/opt/gensoft/src/gnina/gnina-1.0.1/test/../gninasrc/lib/gpu_util.h(18): warning #1444-D: function "cudaDeviceSynchronize"
/opt/gensoft/exe/cuda/11.7/include/cuda_device_runtime_api.h(142): here was declared deprecated ("Use of cudaDeviceSynchronize from device code is deprecated and will not be supported in a future release. Disable this warning with -D__CDPRT_SUPPRESS_SYNC_DEPRECATION_WARNING.")

/opt/gensoft/src/gnina/gnina-1.0.1/test/../gninasrc/lib/gpu_util.h(18): warning #1444-D: function "cudaDeviceSynchronize"
/opt/gensoft/exe/cuda/11.7/include/cuda_device_runtime_api.h(142): here was declared deprecated ("Use of cudaDeviceSynchronize from device code is deprecated and will not be supported in a future release. Disable this warning with -D__CDPRT_SUPPRESS_SYNC_DEPRECATION_WARNING.")

/opt/gensoft/src/gnina/gnina-1.0.1/test/../gninasrc/lib/gpu_util.h(18): warning #1444-D: function "cudaDeviceSynchronize"
/opt/gensoft/exe/cuda/11.7/include/cuda_device_runtime_api.h(142): here was declared deprecated ("Use of cudaDeviceSynchronize from device code is deprecated and will not be supported in a future release. Disable this warning with -D__CDPRT_SUPPRESS_SYNC_DEPRECATION_WARNING.")

/opt/gensoft/src/gnina/gnina-1.0.1/test/../gninasrc/lib/gpu_util.h(18): warning #1444-D: function "cudaDeviceSynchronize"
/opt/gensoft/exe/cuda/11.7/include/cuda_device_runtime_api.h(142): here was declared deprecated ("Use of cudaDeviceSynchronize from device code is deprecated and will not be supported in a future release. Disable this warning with -D__CDPRT_SUPPRESS_SYNC_DEPRECATION_WARNING.")

```

an it stay stuck at this stage.... 
additional info

```
top - 10:02:15 up 10 days, 17:50, 14 users,  load average: 3.15, 3.16, 3.11
Tasks: 854 total,   3 running, 851 sleeping,   0 stopped,   0 zombie
%Cpu(s):  1.6 us,  0.0 sy,  0.0 ni, 98.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem : 515574.6 total,  65349.9 free,  10035.2 used, 440189.5 buff/cache
MiB Swap:   8000.0 total,   7849.7 free,    150.2 used. 496353.4 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND 
3318354 polkitd   20   0 1013004 981.1m   6996 R  99.7   0.2  97:22.33 cudafe++
```

```
maestro-builder:~ > sudo strace -p 3318354
[sudo] password for edeveaud: 
strace: Process 3318354 attached
[ Process PID=3318354 runs in x32 mode. ]
```

rgeards

Eric

**Comment by dkoes** [comment]
I haven't run into this myself, but really seems like a compiler bug...

**Comment by EricDeveaud** [comment]
hello,

hacking `caffe/cmake/Cuda.cmake` to add 80 nand 86 capabilities to `Caffe_known_gpu_archs` allows gnina-1.0.2 to build with cuda-11.7 and to tun on A100 cards

regards

Eric

**Comment by dkoes** [comment]
0cb5eb8c
