### ISSUE TITLE
Do these warnings matter?

### ISSUE THREAD

**Issue by quantumania** [gnina/gnina#15]
CUDA9 is used here.

[  8%] Building NVCC (Device) object caffe/src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_molgrid_data_layer.cu.o
/garlic/apps/Downloads/gnina/./gninasrc/lib/gpu_math.h(13): warning: __host__ annotation on a defaulted function("gfloat3") is ignored

/garlic/apps/Downloads/gnina/./gninasrc/lib/gpu_math.h(13): warning: __device__ annotation on a defaulted function("gfloat3") is ignored

/garlic/apps/Downloads/gnina/./gninasrc/lib/gpu_math.h(34): warning: __host__ annotation on a defaulted function("operator=") is ignored

/garlic/apps/Downloads/gnina/./gninasrc/lib/gpu_math.h(34): warning: __device__ annotation on a defaulted function("operator=") is ignored

/garlic/apps/Downloads/gnina/./gninasrc/lib/gpu_math.h(60): warning: function "__shfl_down(float, unsigned int, int)"
/garlic/apps/cuda9.0/include/sm_30_intrinsics.hpp(278): here was declared deprecated ("__shfl_down() is deprecated in favor of __shfl_down_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")

/garlic/apps/Downloads/gnina/./gninasrc/lib/gpu_math.h(61): warning: function "__shfl_down(float, unsigned int, int)"
/garlic/apps/cuda9.0/include/sm_30_intrinsics.hpp(278): here was declared deprecated ("__shfl_down() is deprecated in favor of __shfl_down_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")

/garlic/apps/Downloads/gnina/./gninasrc/lib/gpu_math.h(62): warning: function "__shfl_down(float, unsigned int, int)"
/garlic/apps/cuda9.0/include/sm_30_intrinsics.hpp(278): here was declared deprecated ("__shfl_down() is deprecated in favor of __shfl_down_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")

/garlic/apps/Downloads/gnina/./gninasrc/lib/gpu_math.h(13): warning: __host__ annotation on a defaulted function("gfloat3") is ignored

/garlic/apps/Downloads/gnina/./gninasrc/lib/gpu_math.h(13): warning: __device__ annotation on a defaulted function("gfloat3") is ignored

/garlic/apps/Downloads/gnina/./gninasrc/lib/gpu_math.h(34): warning: __host__ annotation on a defaulted function("operator=") is ignored

/garlic/apps/Downloads/gnina/./gninasrc/lib/gpu_math.h(34): warning: __device__ annotation on a defaulted function("operator=") is ignored

**Comment by dkoes** [comment]
We haven't moved to CUDA9 yet.  When we do, we'll fix these warnings.

**Comment by quantumania** [comment]
So, which CUDA version should be used here, 7.5 or 8? Other than the warning, is using CUDA 9 problematic?

**Comment by dkoes** [comment]
We are using 8, but I haven’t had any problems with 9 in my limited testing.
