### ISSUE TITLE
What is SB4 command?

### ISSUE THREAD

**Issue by masato-mouse** [gnina/gnina#150]
### Issue summary
What is SB4 command?

### Steps to reproduce

I try 「!grep SB4 〜  XXX.pdb 」command .
As a result , I could make lig.pdb file.  But it's 0 byte.
So, docking error by lig.pdb.
May I help you?

### Your system configuration
Operating system: mac os
Compiler: Google colab
CUDA version (if applicable):
CUDNN version (if applicable):
Python version:

**Comment by dkoes** [comment]
It isn't a command, it is the name of the ligand in the PDB file in the example worksheet.  I am extracting the lines that define that ligand into a file of its own.  Use your favorite molecular editor to extract the ligand of interest from your file.

**Comment by masato-mouse** [comment]
I'm sorry to reply later.
Yes. I tried to rewirite my purpose moleculer for lig.pdb.

before) !grep SB4 3ERK.pdb > lig.pdb
after)    !grep SB4 1JP5.pdb > lig2.pdb

But it can be 0byte lig2.pdb flie.

**Comment by dkoes** [comment]
SB4 isn’t the name of the ligand in 1jp5. Use your favorite molecular editor to extract the ligand of interest from your file.

**Comment by masato-mouse** [comment]
I understand. Thank you .
I will try another one.
