### ISSUE TITLE
Could I get the docked file(pdbqt) from GNINA?

### ISSUE THREAD

**Issue by rest1h** [gnina/gnina#153]
### Question
Hello.

Could I get the docked file from GNINA? 

I actually want to identify and visualize names of residues in pocket that interact with ligands. 

Thank you in advance!

**Comment by RMeli** [comment]
Yes, you can specify the output file with the `-o` (or, equivalently, `--out`) option. The file format is taken from the file extension.

**Comment by rest1h** [comment]
Thank you very much!
