### ISSUE TITLE
CrossDocked2020 Dataset Documentation

### ISSUE THREAD

**Issue by hnisonoff** [gnina/gnina#154]
### Issue summary
Is there documentation available to explain the contents of the CrossDocked2020 dataset? I would love to explore it more. 

### Your system configuration
Operating system:
Compiler:
CUDA version (if applicable):
CUDNN version (if applicable):
Python version:

**Comment by francoep** [comment]
https://github.com/gnina/models/tree/master/data/CrossDocked2020

**Comment by hnisonoff** [comment]
Thank you!
