### ISSUE TITLE
Does Gnina/Smina allow you to fix certain bonds to not be rotatable during docking? 

### ISSUE THREAD

**Issue by hnisonoff** [gnina/gnina#156]
### Issue summary
Does Gnina/Smina allow you to fix certain bonds to not be rotatable during docking? 

### Your system configuration
Operating system:
Compiler:
CUDA version (if applicable):
CUDNN version (if applicable):
Python version:

**Comment by dkoes** [comment]
If you provide a PDBQT file as input, it will respect exactly what is in the file as far as which bonds are rotatable (and also protonation states in atom types - so make sure those are right).

**Comment by hnisonoff** [comment]
Ah sorry I didn't know that this Information was in the pdbqt file format. Thanks for explaining that!
