### ISSUE TITLE
Hi, What do you think of virtual screening classification models and affinity prediction model?

### ISSUE THREAD

**Issue by jooewood** [gnina/gnina#158]
Which one is more potential to find active compound?
Or they all have applicable scenarios？Such as virtual screening classification models maybe suitable for hit identification, affinity prediction model maybe more helpful in lead optimizaiton？Tks!

**Comment by dkoes** [comment]
https://www.mdpi.com/1420-3049/26/23/7369?ref=https://githubhelp.com

**Comment by jooewood** [comment]
Tks!
