### ISSUE TITLE
What could be the cause of this error?

### ISSUE THREAD

**Issue by quantumania** [gnina/gnina#16]
[ 98%] Building CXX object gninasrc/gninaserver/CMakeFiles/gninaserver.dir/MinimizationQuery.cpp.o
In file included from /garlic/apps/Downloads/gnina/gninasrc/gninaserver/MinimizationQuery.h:13:0,
                 from /garlic/apps/Downloads/gnina/gninasrc/gninaserver/MinimizationQuery.cpp:10:
/garlic/apps/Downloads/gnina/gninasrc/gninaserver/Reorienter.h:14:29: fatal error: eigen3/Eigen/Core: No such file or directory
 #include <eigen3/Eigen/Core>
                             ^
compilation terminated.

**Comment by quantumania** [comment]
Needs libeigen3-devel

**Comment by dkoes** [comment]
Yes, that's why we say to install it in the README.
