### ISSUE TITLE
Ignore bad molecules

### ISSUE THREAD

**Issue by mmagithub** [gnina/gnina#162]
### Issue summary
Hi,
I am wondering if there is a mechanism/command in Gnina to overcome bad molecules. I am trying to use Gnina (default CNN ensemble) to rescore poses (in sdf outputs) that have been provided through non-GPU Gnina (default vina). But in many cases, the jobs are early terminated because of the presence of what seems to be difficult to process molecules. This issue happens only in the rescoring by CNN, not in the docking itself. Dropping these molecules/poses from the outputs resulted in the rescoring finished smoothly. 

So is it possible to prevent gnina breaking if it encounters such poses/molecules, or I will always need to remove these molecules, which is not always straightforward if I am dealing with a large number of files?  

Different CNN ensembles, rescoring protocols, behaved the same.

Thanks
### Your system configuration
Operating system: Linux
Compiler: default gnina executable or the docker image
CUDA version (if applicable): 10.2
CUDNN version (if applicable):
Python version:

**Comment by dkoes** [comment]
Can you provide an example of a structure file that is failing?

**Comment by dkoes** [comment]
Closing issue since examples were not provided.
