### ISSUE TITLE
Is it possible to initialize pose with only the receptor file and smiles file?

### ISSUE THREAD

**Issue by HyungSik-Jo** [gnina/gnina#166]
### Issue summary

I would like to check whether about 100,000 Smiles can be docked to a specific protein.

After converting the Smiles into an sdf file, various tests were conducted.

If pose score and binding affinity are calculated with scripts/predict.py file, pose initialize does not seem to work.

If gnina is used, the pose score of a specific protein can be calculated, but it seems that all 100,000 cases need to be calculated individually.

Is there any good way I can apply it?

**Comment by dkoes** [comment]
SMILES files are 2D.  You must provide valid conformers for docking as only torsions are sampled.

**Comment by HyungSik-Jo** [comment]
Thank you for quick response.

After converting the smiles code to a 2d sdf file with rdkit, the score and structure appear normally when using gnina.

If autobox_lignad is set as a protein standard, execution is normal.

example
`gnina --receptor protein.pdb --ligand mol_2d.sdf --out test_pose5.sdf --autobox_ligand protein.pdb`

However, it seems to be very different from the values ​​taken based on the 3d structure of the docked ligand.

1. 2d structure & autobox_ligand = protein 
![image](https://user-images.githubusercontent.com/78404350/193984524-5d5afaea-e967-4f4e-8b6b-2e02cbbd0202.png)

2. docked 3d structure & autobox_ligand = ligand
![affinity](https://user-images.githubusercontent.com/78404350/193984645-b9f5cfa5-decc-426e-ba7f-7f935070f127.png)

May I know what is causing the difference?

**Comment by dkoes** [comment]
If I understand what you are doing, in the first you are doing whole protein docking with a generated ligand whereas in the second you are focused on the binding site using the crystal structure.  The first has a much larger search space and a non-ideal ligand geometry, so you would not expect as good results.  If the issue is the search space, you can increase the exhaustiveness level.  If the issue is the ligand geometry, you can do a better job generating a quality conformer (are you sampling multiple conformers, energy minimizing them, and taking the lowest energy one, or are you simply taking the first thing rdkit generates without any energy minimization?).

**Comment by HyungSik-Jo** [comment]
I understand what you said.

If so, how about extracting only the known binding site part to the pdb file and setting the autobox_ligand function to the whole protein?

How can you narrow the gap much with how you use the crystal structure?

**Comment by RMeli** [comment]
`autobox_ligand` is a convenience function that allow you to quickly and easily define the search space given a ligand or a fragment in the binding site (or the protein, for whole protein docking). The binding site is then defined as a box around the argument of `autobox_ligand` (with some padding, which you can control with `--autobox_add`).

However, you can also define the search space manually with the following options:
```text
Search space (required):
  --center_x arg                   X coordinate of the center
  --center_y arg                   Y coordinate of the center
  --center_z arg                   Z coordinate of the center
  --size_x arg                     size in the X dimension (Angstroms)
  --size_y arg                     size in the Y dimension (Angstroms)
  --size_z arg                     size in the Z dimension (Angstroms)
```

**Comment by HyungSik-Jo** [comment]
Thank you for answer ! 

It seems to output a bit more meaningful data.
