### ISSUE TITLE
CNN Affinity Score Bias? The bigger the molecules are, the higher the scores get

### ISSUE THREAD

**Issue by Kirito-Ausna** [gnina/gnina#167]
### Issue summary
Hello! Thanks for your awesome work!
I meet the problem above, that's, for the same pocket, the molecule atom number can affect the CNN Affinity Score in an unexpecting way. In my opinions, if the molecule size gets smaller, it should be easier to dock and then we get higher Affinity. Or it should be irrelevant?

### Steps to reproduce
I just use the default setting of gnina command line. If I misuse this software, please point out my mistakes. Thank you very much.
Very nice software, thank you for your efforts again ! 

### Your system configuration
Operating system:
Compiler:
CUDA version (if applicable):
CUDNN version (if applicable):
Python version:

**Comment by dkoes** [comment]
Larger molecules can make more interactions.  Most scoring function (regardless of class, e.g. ML or empirical) will have some correlation with molecular weight.
