### ISSUE TITLE
RDkit and Boost

### ISSUE THREAD

**Issue by quantumania** [gnina/gnina#17]
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: warning: libboost_system.so.1.63.0, needed by /usr/local/lib/libFileParsers.so, may conflict with libboost_system.so.1.53.0

probably because I installed RDkit 2017.09.2, is this a problem?

**Comment by dkoes** [comment]
Yes, although only for building the visualizer.  It seems like you are doing a lot of custom installs of dependencies instead of using a package manager.

**Comment by quantumania** [comment]
I use SLES 12, libboost_system.so.1.53.0 was installed from yast, the package manager. Maybe my Linux is too old...

**Comment by dkoes** [comment]
RDKit is now optional
