### ISSUE TITLE
RDKit uses C++17, gnina uses C++14

### ISSUE THREAD

**Issue by kcgthb** [gnina/gnina#173]
### Issue summary
RDKit [uses C++17](https://www.rdkit.org/docs/GettingStartedInC++.html) since 2018, but `gnina` has:
https://github.com/gnina/gnina/blob/e60ccc068db27a61c9ff46cfdbf2a74e667dfbcd/CMakeLists.txt#L13

In particular, RDkit uses constructs like this:
https://github.com/rdkit/rdkit/blob/fbbddc6035d74f12edde15bf1a93fa70a3fe6fd1/Code/RDGeneral/Dict.h#L261
which don't exist in C++14

This causes compilation error like these:
```
In file included from /share/software/user/open/py-rdkit/2022.09.1_py39/include/rdkit/RDGeneral/types.h:28,
                 from /share/software/user/open/py-rdkit/2022.09.1_py39/include/rdkit/GraphMol/ROMol.h:39,
                 from /dev/shm/gnina-1.0.2/gninasrc/gninavis/cnn_visualization.hpp:6,
                 from /dev/shm/gnina-1.0.2/gninasrc/gninavis/gninavis.cpp:2:
/share/software/user/open/py-rdkit/2022.09.1_py39/include/rdkit/RDGeneral/Dict.h: In member function ‘void RDKit::Dict::setVal(const string&, T&)’:
/share/software/user/open/py-rdkit/2022.09.1_py39/include/rdkit/RDGeneral/Dict.h:261:26: error: ‘is_samev’ is not a member of ‘std’; did you mean ‘is_same’?
  261 |     static_assert(! std::is_samev<T, std::string_view>,
      |                          ^~~~~~~~
      |                          is_same
```

**Comment by dkoes** [comment]
Why do they have be built using the same C++ standard?

**Comment by kcgthb** [comment]
Because as mentioned in the initial report, RDKit uses `is_samev`, which is a C++17 construct that will fail to compile with `-std=c++14`.

**Comment by dkoes** [comment]
But why do gnina and rdkit have to be built with the same c++ standard? C++14 code can link to C++17 code...

**Comment by kcgthb** [comment]
> C++14 code can link to C++17 code...

Not when the headers use C++17-specific functions.
The error happens when compiling `gnina`, not RDKit.

RDKit uses C++17 constructs in its header files, that `gnina` includes when RDKit support is enabled. Because `gnina`'s `CMakeLists.txt` defines `set(CMAKE_CXX_STANDARD 14)`, all of `gnina` is compiled with `-std=c++14`.

So when the compiler comes to `gninasrc/gninavis/gninavis.cpp`, it includes `cnn_visualization.hpp`, which in turns includes RDKit's `GraphMol/ROMol.h`, then `RDGeneral/types.h`, and finally `RDGeneral/Dict.h`, which contains `is_same_v`:
https://github.com/rdkit/rdkit/blob/master/Code/RDGeneral/Dict.h#L261

And compiling something that uses `is_same_v` with `-std=c+14` fails.

Does that make sense?
