### ISSUE TITLE
How to generate a binary file by using few dependences, like the first one in your releases?

### ISSUE THREAD

**Issue by li-jin-xing** [gnina/gnina#175]
Hi, I wanna use gnina in a slurm sever, but the gnina needs lots of dependences and I can't change the slurm configuration. So i need figure out how you generated your released version. I use the "ldd" comand to check your released gnina binary file and confirm it's my needed. So I propose this issue and expect that you can give me help.

**Comment by dkoes** [comment]
Docker files are here: https://github.com/gnina/gnina/tree/master/docker

**Comment by dkoes** [comment]
The docker files show you how to build a binary.

**Comment by li-jin-xing** [comment]
Thanks a bunch. It's really helpful.
