### ISSUE TITLE
Could NOT find Boost (missing: python37) (found suitable version "1.65.1", minimum required is "1.58")

### ISSUE THREAD

**Issue by alpha-beta-user** [gnina/gnina#176]
When I run cmake, there exists an error like below:

`-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- The CUDA compiler identification is NVIDIA 11.2.152
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found suitable version "11.2", minimum required is "11.0") 
openbabel BINARY_DIR = /content/openbabel/build/gnina/build
openbabel BINARY_DIR = /content/openbabel/build/gnina/build
openbabel IMPORTED = TRUE
openbabel IMPORTED_CONFIGURATIONS = RELEASE
openbabel IMPORTED_GLOBAL = FALSE
openbabel INTERFACE_LINK_LIBRARIES = /usr/lib/x86_64-linux-gnu/libm.so;dl;/usr/lib/x86_64-linux-gnu/libz.so;Threads::Threads
openbabel NAME = openbabel
openbabel POSITION_INDEPENDENT_CODE = True
openbabel SOURCE_DIR = /content/openbabel/build/gnina
openbabel SOURCE_DIR = /content/openbabel/build/gnina
openbabel TYPE = SHARED_LIBRARY
openbabel TYPE = SHARED_LIBRARY
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Could NOT find libmolgrid (missing:  LIBMOLGRID_INCLUDE_DIR LIBMOLGRID_LIBRARY) 
libmolgrid will be fetched from git
-- Found Git: /usr/bin/git (found version "2.17.1") 
-- Found Python: /usr/bin/python3.7 (found version "3.7.15") found components: Interpreter Development Development.Module Development.Embed 
-- CUDA detected: 11.2
-- Automatic GPU detection failed. Building for all known architectures.
-- Added CUDA NVCC flags for: sm_35 sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86
-- Found Boost: /usr/include (found suitable version "1.65.1", minimum required is "1.54") found components: system thread filesystem iostreams timer chrono date_time atomic regex 
-- Found libmolgrid: /content/openbabel/build/gnina/build/external/include  
-- Found GFlags: /usr/include  
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found Glog: /usr/include  
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found version "3.0.0") 
-- Found PROTOBUF Compiler: /usr/bin/protoc
-- Found HDF5: /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so;/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_cpp.so;/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "1.10.0.1") found components: HL 
-- CUDA detected: 11.2
-- Found cuDNN: ver. 8.1.1 found (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Automatic GPU detection failed. Building for all known architectures.
-- Added CUDA NVCC flags for: sm_35 sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86
-- Found Atlas: /usr/include/x86_64-linux-gnu  
-- Found Atlas (include: /usr/include/x86_64-linux-gnu library: /usr/lib/x86_64-linux-gnu/libatlas.so lapack: /usr/lib/x86_64-linux-gnu/liblapack.so
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.7.15", minimum required is "3.0") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.7m.so (found suitable version "3.7.15", minimum required is "3.0") 
-- Found NumPy: /usr/local/lib/python3.7/dist-packages/numpy/core/include (found suitable version "1.21.6", minimum required is "1.7.1") 
-- NumPy ver. 1.21.6 found (include: /usr/local/lib/python3.7/dist-packages/numpy/core/include)
-- Could NOT find Boost (missing: python37) (found suitable version "1.65.1", minimum required is "1.58")
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- 
-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version           :   1.0.0
--   Git               :   v1.0.2-20-ge60ccc06
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -Wno-deprecated-declarations -Wno-unknown-pragmas -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -Wno-deprecated-declarations -Wno-unknown-pragmas -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release
-- 
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   ON
--   CPU_ONLY          :   OFF
--   USE_OPENCV        :   0
--   USE_LEVELDB       :   0
--   USE_LMDB          :   0
--   USE_NCCL          :   OFF
--   ALLOW_LMDB_NOLOCK :   OFF
-- 
-- Dependencies:
--   BLAS              :   Yes (Atlas)
--   Boost             :   Yes (ver. 1.65)
--   glog              :   Yes
--   gflags            :   Yes
--   OpenBabel         :   No
--   protobuf          :   Yes (ver. 3.0.0)
--   CUDA              :   Yes (ver. 11.2)
-- 
-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_35 sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86
--   cuDNN             :   Yes (ver. 8.1.1)
-- 
-- Python:
--   Interpreter       :   /usr/bin/python3 (ver. 3.7.15)
--   Libraries         :   /usr/lib/x86_64-linux-gnu/libpython3.7m.so (ver 3.7.15)
--   NumPy             :   /usr/local/lib/python3.7/dist-packages/numpy/core/include (ver 1.21.6)
-- 
-- Documentaion:
--   Doxygen           :   No
--   config_file       :   
-- 
-- Install:
--   Install path      :   /usr/local
-- 
-- Found Boost: /usr/include (found version "1.65.1") found components: program_options system iostreams timer thread serialization filesystem date_time regex unit_test_framework chrono atomic 
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Found RDKit include files at /usr/include/rdkit
-- Found RDKit libraries at /usr/lib
-- Found RDKit library files at /usr/lib/libFileParsers.so;/usr/lib/libSmilesParse.so;/usr/lib/libSubstructMatch.so;/usr/lib/libGraphMol.so;/usr/lib/libRDGeometryLib.so;/usr/lib/libRDGeneral.so;/usr/lib/libSubgraphs.so;/usr/lib/libDataStructs.so;/usr/lib/libDepictor.so
-- Found RDKit: /usr/include/rdkit  
-- Found Boost: /usr/include (found version "1.65.1") found components: unit_test_framework system 
-- Found PythonInterp: /usr/bin/python3 (found version "3.7.15") 
-- Configuring done
-- Generating done
-- Build files have been written to: /content/openbabel/build/gnina/build`

**Comment by dkoes** [comment]
What is the error?
