### ISSUE TITLE
Aborted (core dumped) issue

### ISSUE THREAD

**Issue by amarye** [gnina/gnina#177]
when i ran gnina, i got error. 
could you please help me to solve it"

![Screenshot from 2022-12-02 11-14-15](https://user-images.githubusercontent.com/55770700/205207275-8468750d-ab11-4824-b0ee-a5d49bd421cf.png)

**Comment by dkoes** [comment]
How much GPU memory do you have?  Does the problem go away if you run with `CUDA_VISIBLE_DEVICES=`?

**Comment by amarye** [comment]
My GPU memory is 12288MB. I did not ran CUDA_VISIBLE_DEVICES=.
I have download binary code of gnina as colab notebook.

**Comment by dkoes** [comment]
It would be helpful to verify that this is a CUDA error but running on the CPU only.
