### ISSUE TITLE
Incorrect cuda requirements in readme

### ISSUE THREAD

**Issue by chedatomasz** [gnina/gnina#179]
### Issue summary
The readme lists minimal cuda version as >= 10.0. The CMakeLists file requires cuda >=11.0.
A workaround is to compile version 1.0.2, which does not suffer from this issue. Compilation with cuda 10.x for that version fails while building libmolgrid - I filed a separate issue for that in the other repository.

**Comment by dkoes** [comment]
I've updated the README to reflect the CUDA 11 requirement (is it actually required? no; do I want to have to support it? also no).
