### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Tonylac77** [gnina/gnina#180]
### Issue summary
When running Vinardo scoring only, I get the following error : 

```
*** Aborted at 1675757726 (unix time) try "date -d @1675757726" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x0) received by PID 4051559 (TID 0x7f8648b02040) from PID 0; stack trace: ***
    @     0x7f8648442520 (unknown)
    @     0x7f864859d97d (unknown)
    @     0x7f86488f445c std::string::compare()
    @           0x46cfea string_to_smina_type()
    @           0x5210ad OutputAtom()
    @           0x523eb5 OutputTree()
    @           0x4c810e GninaConverter::convertParsing()
    @           0x4c829d GninaConverter::convertParsing()
    @           0x4eee48 MolGetter::readMoleculeIntoModel()
    @           0x42fb3d main
    @     0x7f8648429d90 (unknown)
    @     0x7f8648429e40 __libc_start_main
    @           0x44bd8d (unknown)
    @                0x0 (unknown)
Segmentation fault (core dumped)
```
This happens only using Vinardo, other scoring such as AutoDock4 works fine. I can provide the protein file, autobox ligand file and the library I am trying to rescore (please suggest a suitable way to share the files in that case). The command syntax I am using is as follows : 

```
vinardo_cmd = 'cd '+software+' && ./gnina -r '+protein_file+' -l '+sdf+' --autobox_ligand '+ref_file+' -o '+results+' --score_only --scoring vinardo --cnn_scoring none'
subprocess.call(vinardo_cmd, shell=True)
```
Where : software is the path to the directory containing the gnina executable, the rest of the variables should be self explanatory.

### Steps to reproduce
Attached files as a .zip: [Issue 180.zip](https://github.com/gnina/gnina/files/10682770/Issue.180.zip)
RMSD_clustered.sdf is the ligand library to be rescored
crystal_ligand_protoss.sdf is the reference ligand for the pocket definition
receptor_protoss_prepared.pdb is the receptor file

### Your system configuration
Operating system: Ubuntu 22
Compiler: using precompiled executable
CUDA version (if applicable):
CUDNN version (if applicable):
Python version: 3.8

**Comment by dkoes** [comment]
Please upload the files to this issue as a zip.

**Comment by Tonylac77** [comment]
Thanks for your answer, there is a now a link to the required files in the 'Steps to reproduce' section

**Comment by dkoes** [comment]
I've pushed a fix for this problem.  If you'd like a workaround that doesn't involve rebuilding, filter out all the molecules with unspecified elements in them (look at CHEMBL371307_PLANTS_09 for an example of what I mean - it has an atom with element `*`).
