### ISSUE TITLE
rdkit , libmolgrid dependency in  installing gnina

### ISSUE THREAD

**Issue by croshong** [gnina/gnina#183]
### Issue summary
while installing gnina with running cmake,
even libmolgrid and rdkit is installed,
it complains libmolgrid and rdkit is not installed

### Steps to reproduce
1. running cmake : cmake ../ -DBLAS=open
2. it seems to finish without error , but when I see the log , I can find following statement
.
.
Could NOT find libmolgrid (missing:  LIBMOLGRID_INCLUDE_DIR LIBMOLGRID_LIBRARY) 
.
.
Could NOT find RDKit (missing:  RDKIT_INCLUDE_DIR RDKIT_LIBRARIES)
.
I could check the installation of molgrid and rdkit with following
(py39) [user1@gpu-004 build]$ python
Python 3.9.16 (main, Mar  1 2023, 18:22:10) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import molgrid
>>> 
>>> import rdkit
>>> 

### Your system configuration
Operating system: centos 7
Compiler: GCC 
CUDA version (if applicable): 11
CUDNN version (if applicable):
Python version:3.9.16

Installation of gnina seems to be really challenging,
Any kind of comments would be really welcomed

Thanks
Jong hui

**Comment by croshong** [comment]
Thanks for your reply

But still I can't figure out how I can set the path variable in cmake argument

I installed libmolgrid and rdkit with pip like below 
pip install molgrid
pip install rdkit 

and both molgrid and rdkit works fine

and it seems that installed folder is located in 
molgrid : envs/py39/lib/python3.9/site-packages/molgrid
rdkit : envs/py39/lib/python3.9/site-packages/rdkit

with above  information how can I set the right path variable in cmake argument?

**Comment by dkoes** [comment]
cmake isn't going to look inside your conda environments.  You need to manually specify them with `-D LIBMOLGRID_INCLUDE_DIR=path -DLIBMOLGRID_LIBRARY=path -DRDKIT_INCLUDE_DIR=path -DRDKIT_LIBRARIES=path` (although rdkit is optional).

**Comment by croshong** [comment]
Yes, That's what I want to figure out, My libmolgrid and rdkit installation is in the conda environment and I want to manually specifiy them in cmake argument,

with this conda env,

molgrid : envs/py39/lib/python3.9/site-packages/molgrid
rdkit : envs/py39/lib/python3.9/site-packages/rdkit

What should be the LIBMOLGRID_INCLUDE_DIR, LIBMOLGRID_LIBRARY, RDKIT_INCLUDE_DIR, RDKIT_LIBRARIES ?

**Comment by croshong** [comment]
I could proceed by 
setting LIBMOLGRID_INCLUDE_DIR  to libmolgrid/include ( which was downloaded from github ( not pip))
setting LIBMOLGRID_LIBRARY to py39/lib/python3.9/site-packages/molgrid/molgrid.so ( pip installed library)
setting RDKIT_LIBRARIES to py39/lib/python3.9/site-packages/rdkit.libs ( pip installed library)
settting DRDKIT_INCLUDE_DIR to py39/lib/python3.9/site-packages/rdkit ( pip installed)

I'm not sure whether I 'm doing correctly or not but it seems there's no problem except some warning as below
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- The CUDA compiler identification is NVIDIA 11.3.58
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda-11.3/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda-11.3 (found suitable version "11.3", minimum required is "11.0") 
openbabel AUTOGEN_ORIGIN_DEPENDS = ON
openbabel AUTOMOC_COMPILER_PREDEFINES = ON
openbabel AUTOMOC_MACRO_NAMES = Q_OBJECT;Q_GADGET;Q_NAMESPACE;Q_NAMESPACE_EXPORT
openbabel AUTOMOC_PATH_PREFIX = OFF
openbabel BINARY_DIR = /lwork01/gnina/build
openbabel BINARY_DIR = /lwork01/gnina/build
openbabel BUILD_WITH_INSTALL_RPATH = OFF
openbabel CUDA_SEPARABLE_COMPILATION = ON
openbabel CUDA_STANDARD = 17
openbabel CXX_STANDARD = 17
openbabel IMPORTED = TRUE
openbabel IMPORTED_CONFIGURATIONS = RELEASE
openbabel IMPORTED_GLOBAL = FALSE
openbabel INSTALL_RPATH = /usr/local/lib
openbabel INSTALL_RPATH_USE_LINK_PATH = OFF
openbabel INTERFACE_LINK_LIBRARIES = /usr/lib64/libm.so;dl;/usr/lib64/libz.so;Threads::Threads
openbabel NAME = openbabel
openbabel PCH_WARN_INVALID = ON
openbabel POSITION_INDEPENDENT_CODE = True
openbabel SKIP_BUILD_RPATH = OFF
openbabel SOURCE_DIR = /lwork01/gnina
openbabel SOURCE_DIR = /lwork01/gnina
openbabel TYPE = SHARED_LIBRARY
openbabel TYPE = SHARED_LIBRARY
openbabel UNITY_BUILD_BATCH_SIZE = 8
openbabel UNITY_BUILD_MODE = BATCH
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7") 
-- Found libmolgrid: /lwork01/libmolgrid/include/  
-- CUDA detected: 11.3
-- Automatic GPU detection failed. Building for all known architectures.
-- Added CUDA NVCC flags for: sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86
-- Found Boost: /usr/local/include (found suitable version "1.69.0", minimum required is "1.54") found components: system thread filesystem iostreams timer chrono date_time atomic regex 
-- Found GFlags: /usr/include  
-- Found gflags  (include: /usr/include, library: /usr/lib64/libgflags.so)
-- Found Glog: /usr/include  
-- Found glog    (include: /usr/include, library: /usr/lib64/libglog.so)
-- Found Protobuf: /usr/lib64/libprotobuf.so;-lpthread (found version "2.5.0") 
-- Found PROTOBUF Compiler: /usr/bin/protoc
-- Found HDF5: /usr/lib64/libhdf5_cpp.so;/usr/lib64/libhdf5.so (found version "1.8.12") found components: HL 
-- CUDA detected: 11.3
-- Found cuDNN: ver. 8.8.1 found (include: /usr/local/cuda-11.3/include, library: /usr/local/cuda-11.3/lib64/libcudnn.so)
-- Automatic GPU detection failed. Building for all known architectures.
-- Added CUDA NVCC flags for: sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86
-- Found OpenBLAS libraries: /usr/lib64/libopenblas.so
-- Found OpenBLAS include: /usr/include
-- Found PythonInterp: /lwork01/miniconda3/envs/py39/bin/python3 (found suitable version "3.9.16", minimum required is "3.0") 
-- Found PythonLibs: /lwork01/miniconda3/envs/py39/lib/libpython3.9.so (found suitable version "3.9.16", minimum required is "3.0") 
-- Found NumPy: /lwork01/miniconda3/envs/py39/lib/python3.9/site-packages/numpy/core/include (found suitable version "1.24.2", minimum required is "1.7.1") 
-- NumPy ver. 1.24.2 found (include: /lwork01/miniconda3/envs/py39/lib/python3.9/site-packages/numpy/core/include)
-- Found Boost: /usr/local/include (found suitable version "1.69.0", minimum required is "1.58") found components: python39 
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.5") found components: doxygen missing components: dot
-- Detected Doxygen OUTPUT_DIRECTORY: ./doxygen/
-- Found Git: /usr/bin/git (found version "1.8.3.1") 
-- 
-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version           :   1.0.0
--   Git               :   v1.0.3-3-gac4b481
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -Wno-deprecated-declarations -Wno-unknown-pragmas -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -Wno-deprecated-declarations -Wno-unknown-pragmas -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release
-- 
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   ON
--   CPU_ONLY          :   OFF
--   USE_OPENCV        :   0
--   USE_LEVELDB       :   0
--   USE_LMDB          :   0
--   USE_NCCL          :   OFF
--   ALLOW_LMDB_NOLOCK :   OFF
-- 
-- Dependencies:
--   BLAS              :   Yes (open)
--   Boost             :   Yes (ver. 1.69)
--   glog              :   Yes
--   gflags            :   Yes
--   OpenBabel         :   No
--   protobuf          :   Yes (ver. 2.5.0)
--   CUDA              :   Yes (ver. 11.3)
-- 
-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86
--   cuDNN             :   Yes (ver. 8.8.1)
-- 
-- Python:
--   Interpreter       :   /lwork01/miniconda3/envs/py39/bin/python3 (ver. 3.9.16)
--   Libraries         :   /lwork01/miniconda3/envs/py39/lib/libpython3.9.so (ver 3.9.16)
--   NumPy             :   /lwork01/miniconda3/envs/py39/lib/python3.9/site-packages/numpy/core/include (ver 1.24.2)
-- 
-- Documentaion:
--   Doxygen           :   /usr/bin/doxygen (1.8.5)
--   config_file       :   /lwork01/gnina/caffe/.Doxyfile
-- 
-- Install:
--   Install path      :   /usr/local
-- 
-- Found Boost: /usr/local/include (found version "1.69.0") found components: program_options system iostreams timer thread serialization filesystem date_time regex unit_test_framework chrono atomic 
-- Found OpenMP_C: -fopenmp (found version "3.1") 
-- Found OpenMP_CXX: -fopenmp (found version "3.1") 
-- Found OpenMP: TRUE (found version "3.1")  
-- Found RDKit: /lwork01/miniconda3/envs/py39/lib/python3.9/site-packages/rdkit  
-- Found Boost: /usr/local/include (found version "1.69.0") found components: unit_test_framework system 
-- Found PythonInterp: /lwork01/miniconda3/envs/py39/bin/python3 (found version "3.9.16") 
-- Configuring done
WARNING: Target "gninavis" requests linking to directory "/lwork01/miniconda3/envs/py39/lib/python3.9/site-packages/rdkit.libs/".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "gninacheck" requests linking to directory "/lwork01/miniconda3/envs/py39/lib/python3.9/site-packages/rdkit.libs/".  Targets may link only to libraries.  CMake is dropping the item.
-- Generating done
-- Build files have been written to: /lwork01/gnina/build

but when I execute make command , there is an error like following
[ 25%] Building CUDA object caffe/src/caffe/CMakeFiles/caffe.dir/layers/absval_layer.cu.o
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The -std=c++17 flag is not supported with the configured host compiler. Flag will be ignored.
/lwork01/gnina/caffe/include/caffe/syncedmem.hpp(61): error: expected a ";"

1 error detected in the compilation of "/lwork01/gnina/caffe/src/caffe/layers/absval_layer.cu".
make[2]: *** [caffe/src/caffe/CMakeFiles/caffe.dir/layers/absval_layer.cu.o] Error 1
make[1]: *** [caffe/src/caffe/CMakeFiles/caffe.dir/all] Error 2
make: *** [all] Error 2

I use CUDA-11.3 and I think this error occurs while installing caffe.
Can you please  give me some suggestion about this error?

Thanks in advance

**Comment by dkoes** [comment]
That's an error with the host compiler (gcc).  You need a newer version.  

Why is the precompiled binary not sufficient for your use case?

**Comment by croshong** [comment]
gcc version of my system is 4.8.5 . which version of GCC is required for installation? Actually because  I need another script or binary for 3D-CNN such as gninavis or gninatyper not only gnina itself, I'm trying to install gnina from source

**Comment by dkoes** [comment]
The compat Dockerfile should provide some hints for compiling on an ancient operating system like CentOS 7:
https://github.com/gnina/gnina/blob/master/docker/compat/Dockerfile

**Comment by croshong** [comment]
In  docker file that you mentioned above,

It seems that gcc version 6.3.0 is uesd.

shoud I use exactly same version of gcc and the version of other tool?

**Comment by dkoes** [comment]
The docker file provides a known good way to build the software.

**Comment by RMeli** [comment]
Sorry to hijack the conversation, but recently I created a [Spack](https://spack.readthedocs.io/en/latest/) package to hopefully make GNINA compilation easier. Maybe it is of interest.

I just opened a PR with some improvements, which will build `gninavis` as well: https://github.com/spack/spack/pull/36117/files

If you [configure a (modern) compiler](https://spack.readthedocs.io/en/latest/getting_started.html#compiler-configuration) (which you can also [build with Spack](https://spack.readthedocs.io/en/latest/getting_started.html#build-your-own-compiler)), you _should_ be able to just do the following:
```
spack install gnina
# Make gnina, gninatyper, gninavis available in your path
spack load gnina
```
This will require to use the code from my PR (`gnina` branch in [my Spack fork](https://github.com/RMeli/spack)) or Spack's `develop` branch if you can go without `gninavis` for now.

```bash
# Get and setup Spack (gnina branch from my own fork)
# See: https://spack.readthedocs.io/en/latest/getting_started.html#installation
git clone -b gnina -c feature.manyFiles=true https://github.com/RMeli/spack.git
. spack/share/spack/setup-env.sh

# If you need a modern compiler
# See: https://spack.readthedocs.io/en/latest/getting_started.html#compiler-configuration
spack install gcc@11.3
spack load gcc@11.3
spack compiler find
spack unload gcc@11.3

# Install gnina, gninavis, gninatyper
# See: https://spack.readthedocs.io/en/latest/basic_usage.html#installing-and-uninstalling
spack install gnina

# Get gnina, gninavis, and gninatyper in PATH
# See: https://spack.readthedocs.io/en/latest/basic_usage.html#using-installed-packages
spack load gnina
```

I tested the installation with GCC 11.3 and CUDA 11.8, but I haven't got the chance of test it on different platforms. **It is still rather experimental and might not work for you**, but could be interesting to give it a try.

**Comment by croshong** [comment]
Thanks I'll try and test with docker file and spack also

**Comment by croshong** [comment]
the docker file that you provide was really helpful 

I could compile most of gnina binary such as gnina, gninatype,..etc

but still I have difficulty in compiling gninavis

at the very final step of compiling, I got the following error 

CMakeFiles/gninavis.dir/gninavis/cnn_visualization.cpp.o: In function `cnn_visualization::remove_fragments(int)':
cnn_visualization.cpp:(.text+0x80c7): undefined reference to `RDKit::MolDataStreamToMol(std::istream&, unsigned int&, bool, bool, bool)'
cnn_visualization.cpp:(.text+0x8128): undefined reference to `vtable for RDKit::ROMol'
cnn_visualization.cpp:(.text+0x8265): undefined reference to `RDKit::ROMol::initFromOther(RDKit::ROMol const&, bool, int)'
cnn_visualization.cpp:(.text+0x82b6): undefined reference to `RDKit::MolOps::removeHs(RDKit::RWMol&, bool, bool, bool)'
cnn_visualization.cpp:(.text+0x82e1): undefined reference to `RDKit::ROMol::beginBonds()'
cnn_visualization.cpp:(.text+0x82f7): undefined reference to `RDKit::BondIterator_::operator*() const'
cnn_visualization.cpp:(.text+0x82ff): undefined reference to `RDKit::BondIterator_::operator*() const'
cnn_visualization.cpp:(.text+0x8307): undefined reference to `RDKit::BondIterator_::operator++()'
cnn_visualization.cpp:(.text+0x831b): undefined reference to `RDKit::ROMol::endBonds()'
cnn_visualization.cpp:(.text+0x832b): undefined reference to `RDKit::BondIterator_::operator!=(RDKit::BondIterator_ const&) const'
cnn_visualization.cpp:(.text+0x83ab): undefined reference to `RDKit::findAllSubgraphsOfLengthsMtoN(RDKit::ROMol const&, unsigned int, unsigned int, bool, int)'
cnn_visualization.cpp:(.text+0x83bd): undefined reference to `RDKit::ROMol::getConformer(int)'
cnn_visualization.cpp:(.text+0x83d5): undefined reference to `RDKit::Conformer::Conformer(RDKit::Conformer const&)'
cnn_visualization.cpp:(.text+0x87ad): undefined reference to `RDKit::ROMol::beginAtoms()'
cnn_visualization.cpp:(.text+0x8847): undefined reference to `RDKit::AtomIterator_<RDKit::Atom, RDKit::ROMol>::operator++()'
cnn_visualization.cpp:(.text+0x885b): undefined reference to `RDKit::ROMol::endAtoms()'
cnn_visualization.cpp:(.text+0x886b): undefined reference to `RDKit::AtomIterator_<RDKit::Atom, RDKit::ROMol>::operator!=(RDKit::AtomIterator_<RDKit::Atom, RDKit::ROMol> const&) const'
cnn_visualization.cpp:(.text+0x887b): undefined reference to `RDKit::AtomIterator_<RDKit::Atom, RDKit::ROMol>::operator*() const'
cnn_visualization.cpp:(.text+0x89a1): undefined reference to `RDKit::ROMol::getBondWithIdx(unsigned int)'
cnn_visualization.cpp:(.text+0x89ad): undefined reference to `RDKit::Bond::Bond(RDKit::Bond const&)'
cnn_visualization.cpp:(.text+0x89c8): undefined reference to `RDKit::Conformer::getAtomPos(unsigned int)'
cnn_visualization.cpp:(.text+0x89f3): undefined reference to `RDKit::Conformer::getAtomPos(unsigned int)'
cnn_visualization.cpp:(.text+0x8c23): undefined reference to `RDKit::Bond::~Bond()'
cnn_visualization.cpp:(.text+0x91f6): undefined reference to `RDKit::AtomIterator_<RDKit::Atom, RDKit::ROMol>::operator*() const'
cnn_visualization.cpp:(.text+0x9202): undefined reference to `RDKit::Atom::getSymbol() const'
cnn_visualization.cpp:(.text+0x9260): undefined reference to `RDKit::ROMol::getConformer(int)'
cnn_visualization.cpp:(.text+0x926a): undefined reference to `RDKit::Conformer::getAtomPos(unsigned int)'
CMakeFiles/gninavis.dir/gninavis/cnn_visualization.cpp.o: In function `cnn_visualization::remove_fragments(int) [clone .cold.1496]':
cnn_visualization.cpp:(.text.unlikely+0x12aa): undefined reference to `RDKit::Bond::~Bond()'
CMakeFiles/gninavis.dir/gninavis/cnn_visualization.cpp.o: In function `RDKit::ROMol::~ROMol()':
cnn_visualization.cpp:(.text._ZN5RDKit5ROMolD2Ev[_ZN5RDKit5ROMolD5Ev]+0x14): undefined reference to `vtable for RDKit::ROMol'
cnn_visualization.cpp:(.text._ZN5RDKit5ROMolD2Ev[_ZN5RDKit5ROMolD5Ev]+0x19): undefined reference to `RDKit::ROMol::destroy()'
CMakeFiles/gninavis.dir/gninavis/cnn_visualization.cpp.o:(.rodata._ZTIN5RDKit5RWMolE[_ZTIN5RDKit5RWMolE]+0x10): undefined reference to `typeinfo for RDKit::ROMol'
CMakeFiles/gninavis.dir/gninavis/cnn_visualization.cpp.o:(.rodata._ZTVN5RDKit5RWMolE[_ZTVN5RDKit5RWMolE]+0x20): undefined reference to `RDKit::ROMol::destroy()'
collect2: error: ld returned 1 exit status
make[2]: *** [gninasrc/CMakeFiles/gninavis.dir/build.make:173: bin/gninavis] Error 1
make[1]: *** [CMakeFiles/Makefile2:2002: gninasrc/CMakeFiles/gninavis.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

 I think it's related with setting RDKit header file folder , and  RDKIT library folder

  I set  DRDKIT_INCLUDE_DIR =rdkit/Code ( which contain header file for submodule ( such as Graphmol,.etc) )
         DRDKIT_LIBRARIES=rdkit.libs ( which contain *.so( I think they are library files))

How can I solve this last problem?

**Comment by dkoes** [comment]
RDKIT_LIBRARIES should specify the actual libraries, not the directory.  Try setting the RDKIT_LIBRARY_DIR environment variable, cmake should then be able to find the libraries.

**Comment by croshong** [comment]
Thanks for your reply but When I set the RDKIT_LIBRARY_DIR instead of RDKIT_LIBRARIES,
It complains the missing RDKIT_LIBRARIES with following warning
-- Could NOT find RDKit (missing:  RDKIT_LIBRARIES)
When I see the RDKIT LIBRARY Folder,  I could see there are so many library file( *.so) 
Which file I should set as library ? or  Is there any other way to set multiple library file as RDKIT_LIBRARIES?
thanks

**Comment by croshong** [comment]
I could install everything in gnina by setting correct rdkit library folder name in RDKIT_LIBRARY_DIR 
Thanks for your help

**Comment by croshong** [comment]
Sorry to ask continuously in this issue
I would like to install in gnina in another server
OS : ubuntu 16.04
GCC : 8.4
python: 3.9.16
I use same approach as I have done in centos server
But I got following error
../lib/libcaffe.so.1.0.0: undefined reference to `boost::detail::set_tss_data(void const*, boost::shared_ptr<boost::detail::tss_cleanup_function>, void*, bool)'
../lib/libcaffe.so.1.0.0: undefined reference to `boost::filesystem::path::stem() const'
collect2: error: ld returned 1 exit status
caffe/tools/CMakeFiles/caffe.bin.dir/build.make:135: recipe for target 'caffe/tools/caffe' failed
make[2]: *** [caffe/tools/caffe] Error 1
CMakeFiles/Makefile2:1402: recipe for target 'caffe/tools/CMakeFiles/caffe.bin.dir/all' failed
make[1]: *** [caffe/tools/CMakeFiles/caffe.bin.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2

maybe some difference in setting between centos and ubuntu that I don't know can be here
what could be the problem in this case?

really thanks for your help

**Comment by dkoes** [comment]
Looks like it can’t find the boost libraries. 16.04 has been end-of-lifed for two years. Why can’t you use the provided binary and avoid all this trouble?

**Comment by croshong** [comment]
As you told me the problem was boost library and I could fix it by reinstalling boost library 
Thanks
