### ISSUE TITLE
Does Crossdock2020 contains complex where ligand binds to PPI pocket or protein-DNA pocket?

### ISSUE THREAD

**Issue by sll513** [gnina/gnina#185]
Does Crossdock2020 contain complex where ligand binds to PPI pocket or protein-DNA pocket?

**Comment by francoep** [comment]
DNA-protein - No.

PPI (Protein-protein interaction?) -- maybe?. If a ligand already existed in the PDB binding to both members of a PPI, then it could be included in the dataset. If it is present, it would be a very small portion of the dataset.

In either case, I would not recommend CrossDocked2020 for training if those were the types of interactions you cared about modeling the most.

**Comment by sll513** [comment]
Thanks a lot. That makes sense.
