### ISSUE TITLE
Issue When rescoring with Vinardo

### ISSUE THREAD

**Issue by Tonylac77** [gnina/gnina#187]
### Issue summary

For the ACE target from the DUD-E dataset, I'm getting an error when attempting to rescore using the Vinardo scoring function.

```
*** Aborted at 1681884913 (unix time) try "date -d @1681884913" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x0) received by PID 144078 (TID 0x7f04e06da040) from PID 0; stack trace: ***
    @     0x7f04e0042520 (unknown)
    @     0x7f04e019d97d (unknown)
    @     0x7f04e04f445c std::string::compare()
    @           0x46cfea string_to_smina_type()
    @           0x5210ad OutputAtom()
    @           0x5239cb OutputTree()
    @           0x4c810e GninaConverter::convertParsing()
    @           0x4c829d GninaConverter::convertParsing()
    @           0x4eee48 MolGetter::readMoleculeIntoModel()
    @           0x42fb3d main
    @     0x7f04e0029d90 (unknown)
    @     0x7f04e0029e40 __libc_start_main
    @           0x44bd8d (unknown)
    @                0x0 (unknown)
Segmentation fault (core dumped)
```

### Steps to reproduce

I've attached the file containing the Ligands I am trying to rescore and the receptor file as well as the reference ligand file for the binding site determination.
Here's the command I used : 

`./gnina -r '+protein_file+' -l '+sdf+' --autobox_ligand '+ref_file+' -o '+results+' --score_only --scoring vinardo --cnn_scoring none --no_gpu'`

Thanks for your insight.

### Your system configuration
Operating system: Ubuntu 22.04
Compiler: Using prebuilt executable
CUDA version (if applicable):
CUDNN version (if applicable):
Python version: 3.8.15

[ace.zip](https://github.com/gnina/gnina/files/11269363/ace.zip)

**Comment by dkoes** [comment]
Thanks for the feedback - I've fixed the link in the README.
