### ISSUE TITLE
CNN center does not work

### ISSUE THREAD

**Issue by jnoske** [gnina/gnina#191]
Dear Gnina developers,

Thank you for the excellent work.
However, I am unable to change the center of the CNN coordinate frame, since the coordinates I define with: --cnn_center_x,y,z are just ignored by gnina.

Best,
Jakob

**Comment by dkoes** [comment]
The above commit fixes the problem (or rather, provides a workaround).  The default is to automatically move the grid with the ligand.  This is a configurable option (cnn_update_min_frame) but it was implemented as a bool_switch (back when the default was false) which doesn't actually let you change the value from true to false.  With the commit you can now set `--cnn_update_min_frame=false` and the specified center should be used.

**Comment by jnoske** [comment]
Dear dkoes,

Thank you for the fast reply and the fix/workaround. Is there a way that you could provide this fix in the precompiled binary to test it out?

Best,
Jakob

**Comment by dkoes** [comment]
Sorry for the super delay - the docker image is now fully up-to-date:
https://hub.docker.com/r/gnina/gnina
