### ISSUE TITLE
predicing CNNscore CNNaffinity with in house built model 

### ISSUE THREAD

**Issue by croshong** [gnina/gnina#192]
Dear Dr Koes

I have made 3D cnn model with PDB bind general data set 
in https://github.com/gnina/models/tree/master/data/PDBBind2016/General_types/gen_uff_train0.types, gen_uff_test0.types

model generation process seems to have no problem

and final model quality is 
AUC =0.922
R^2 = 0.62( R ~=0.8)

so it seems to be not bad
so I tried to predict CNNscore and CNNaffinity with this model and model weith( *.caffemodel)
But the problem is that there is a difference in predicted value between prediction using gnina binary 
and prediction using predict.py in ( https://github.com/gnina/scripts)

when I use gnina binary, I use the following command line
gnina -r rec.pdb -l het.pdb --minimize --device 0 --cnn_model default2018.model --cnn_weights gen_uff_default2018.0_iter_80000.caffemodel
( rec.pdb, het.pdb was splitted from input protein ligand complex)
as an output, I got the following
Affinity: -7.41848  0.17850 (kcal/mol)
RMSD: 0.67871
CNNscore: 0.26599 
CNNaffinity: 7.00397

when I use the predict.py script, I use the following command line
python predict_v1.py -m default2018.model -w gen_uff_default2018.0_iter_80000.caffemodel -i xx.types -g 0
( where in xx.types
  1.0 7.8 1.5 rec_0.gninatypes het_0.gninatypes( *.gninatypes was generated from rec.pdb,het.pdb with gninatyper)
as an output, I got the following
0.361812 6.976402 | 1.0 7.8 1.5 rec_0.gninatypes het_0.gninatypes
( I think CNNscore=0.36182 and CNNaffinity=6.97642)

Is there something wrong with what I have done with gnina or predict.py or Is the difference that I have observed between gnina and predict.py not significant ?

**Comment by dkoes** [comment]
You are passing --minimize to gnina which will change the input pose.  What are the values with --score_only?

**Comment by croshong** [comment]
after I remove --minimize option and add --score_only option
I got the following value
CNNscore: 0.38091
CNNaffinity: 6.98595
( with predict.py I got CNNscore = 0.36182l, CNNaffinity = 6.97642) 

I think difference seems to be small.
Can I think this difference as not significant?

**Comment by dkoes** [comment]
The small differences might be due to how the center of the grid is computed.  I would say it is working as intended.

**Comment by croshong** [comment]
Yes I understand, Thanks for your comment
