### ISSUE TITLE
symmetry related chemical in 3D cnn

### ISSUE THREAD

**Issue by croshong** [gnina/gnina#195]
The predicted CNN score value are generally well fit into real world
but in some case as shown in the image ( green: crystal complex(0.81), cyan: conformer with top CNNscore(0.92)),
The conformer which is symmetry related to original crystal complex conformer gets more high CNNscore or
in some gase, gets similar score. Is there any other method to distinguish symmetry related conformer from original confomer
with 3D-cnn approach? 
![image](https://github.com/gnina/gnina/assets/7292758/76a609e0-2977-42e1-84f6-608b6794e46c)

**Comment by dkoes** [comment]
No docking algorithm is perfect.
