### ISSUE TITLE
question about gninavis generated file 

### ISSUE THREAD

**Issue by croshong** [gnina/gnina#197]
I run the gninavis with command like below 
gninavis --receptor rec.pdb --ligand lig.pdb --cnn_model default2018.model --cnn_weights gen_uff_default2018.0_iter_80000.caffemodel

as a result it produces *.pdbqt, *.pdbqt.ext. 
with this file as a result, how can I get the each atomic score and produce the pymol visualization as 
in paper 
Visualizing convolutional neural network protein-ligand scoring

Thanks

**Comment by dkoes** [comment]
Are there not values in the b factor fields?

**Comment by croshong** [comment]
what you mean is the value in a column Elec?
![image](https://github.com/gnina/gnina/assets/7292758/ef5ea13a-13e1-4265-afda-40b24ebf60b8)

**Comment by dkoes** [comment]
Sorry, I forgot it was a pdbqt output instead of pdb.  The per-atom visualization score is output starting at column 61 which I assume is the elec column.

**Comment by croshong** [comment]
Yes I understand gninavis output format
but when I run gninavis with gnina in buit model such as crossdock_default2018.... or general_default2018...,
I got segmentation fault error like below
CNN SCORE: 0.988952

Doing masking...
Segmentation fault (core dumped)

when I try with my own model it works well.
Is there anything that I should consider?

**Comment by dkoes** [comment]
Can you provide a complete test case so I can see if I can reproduce the issue?

**Comment by croshong** [comment]
Thanks for your reply 

Attached files are the example

In the readme file
## run without error
gninavis --receptor rec.pdb --ligand lig.pdb --gpu 0 --cnn_model default2018.model --cnn_weights gen_uff_default2018.0_iter_80000.caffemodel
## run with error
gninavis --receptor rec.pdb --ligand lig.pdb --gpu 0 --cnn crossdock_default2018

but I found that after I dumpmodel crossdock_default2018 using dumpmodel command 
dumpmodel crossdock_default2018

and run with 
gninavis --receptor rec.pdb --ligand lig.pdb --gpu 0 --cnn_model default2018.model --cnn_weights crossdock_default2018.caffemodel

It runs without error
[example.zip](https://github.com/gnina/gnina/files/11835380/example.zip)

I think there's something wrong with my setting when I run with 'gninavis --receptor rec.pdb --ligand lig.pdb --gpu 0 --cnn crossdock_default2018'

**Comment by croshong** [comment]
When running gninavis with gradient method, I know that the resulting gradient 
can be visualized as vectors in 3D space
but when I run gninavis in my server, I got pdbqt file with scalar magnitue on each atom at column61
same as masking method.
How can I draw vectors with pdbqt file generated with gradient method?

**Comment by dkoes** [comment]
The gradient vectors should be in an gradient_*.xyz file generated by gninavis.

**Comment by croshong** [comment]
Thanks for your reply
I found that *.xyz file is generated when I run gninavis with gradient visualization

*.xyz file looks like this 

N 16.379 33.292 37.803 1.7166e-05 7.6294e-06 -7.6294e-06
C 15.029 33.262 37.502 7.8201e-05 -1.1444e-05 -4.1962e-05
C 14.581 32.773 36.265 0.00011635 3.8147e-06 3.0518e-05
C 13.197 32.764 36.009 8.5831e-05 -2.2888e-05 4.1962e-05
.
.
it seems first 4 columns are atom name and its X, Y, Z coordinate.
The other columns should be vector information as you wrote.
but I don't know how to extract gradient vector information as the paper
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6343664/
Can you please describe how to interpret the xyz file generated by gninavis?

**Comment by dkoes** [comment]
https://github.com/gnina/scripts/blob/master/show_xyz_arrows.py

**Comment by dkoes** [comment]
Please close issues when they are resolved.
