### ISSUE TITLE
Scoring functions in gnina

### ISSUE THREAD

**Issue by Le-Phung-Hien** [gnina/gnina#199]
Hi,

I am sorry for the naive question. What built-in scoring function does gnina have? Also, if I use `--scoring` to specify alternative scoring function, will it be applied through out the Monte Carlo sampling and full refinement?

Thank you very much!

**Comment by dkoes** [comment]
The default CNN scoring function is an ensemble of 5 models selected to balance pose prediction performance and runtime: dense, general_default2018_3, dense_3, crossdock_default2018, and redock_default2018. More information on these various models can be found in the papers listed in the README.

**Comment by dkoes** [comment]
--cnn_scoring determines at what points of the docking procedure that the CNN scoring function is used.

- none - No CNNs used for docking. Uses the specified empirical scoring function throughout.
- rescore (default) - CNN used for reranking of final poses. Least computationally expensive CNN option.
- refinement - CNN used to refine poses after Monte Carlo chains and for final ranking of output poses. 10x slower than rescore when using a GPU.
- all - CNN used as the scoring function throughout the whole procedure. Extremely computationally intensive and not recommended.

If the CNN scoring function isn't being used then the empirical scoring function is used, which defaults to Vina.

**Comment by dkoes** [comment]
Yes, the default is to use the default ensemble.

**Comment by JeniFoo** [comment]
how can I run the 

> default2018.def

 in /gnina/gninascr with 

> redock2018_0.def

 in /gnina/gnianscr/weights  in a conda python=3.6 environment?

**Comment by dkoes** [comment]
You can see the mapping between commandline names and model weights here: https://github.com/gnina/gnina/blob/master/gninasrc/lib/cnn_data.cpp
