### ISSUE TITLE
identifier "__shfl_down_sync" is undefined

### ISSUE THREAD

**Issue by amrhamedp** [gnina/gnina#20]
The error occurs on 
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5) 
Cuda compilation tools, release 8.0, V8.0.44

/media/cresset/scratch2/rfscore/gnina/gnina/./gninasrc/lib/gpu_math.h(58): error: identifier "__shfl_down_sync" is undefined

/media/cresset/scratch2/rfscore/gnina/gnina/./gninasrc/lib/gpu_math.h(63): error: identifier "__shfl_down_sync" is undefined

2 errors detected in the compilation of "/tmp/tmpxft_00005162_00000000-7_molgrid_data_layer.cpp1.ii".
CMake Error at cuda_compile_1_generated_molgrid_data_layer.cu.o.Release.cmake:282 (message):
  Error generating file
  /media/cresset/scratch2/rfscore/gnina/gnina/build/caffe/src/caffe/CMakeFiles/cuda_compile_1.dir/layers/./cuda_compile_1_generated_molgrid_data_layer.cu.o

**Comment by dkoes** [comment]
Yes, we (very) recently moved to CUDA 9.  Upgrading will resolve this issue.
