### ISSUE TITLE
CNNAffinity correlation of implemented models

### ISSUE THREAD

**Issue by jnoske** [gnina/gnina#204]
Hi,

Thanks for the brilliant work!

Is was wondering if there is a general recommendation which of the implemented CNN models or ensemble of CNN models works best for affinity predictions, so that given a number of ligands that have been already docked, which one would be most likely to show the best correlation.

**Comment by dkoes** [comment]
I recommend the default ensemble, as it was selected to be best all around.  But if you have data for your target, you can calibrate against that.
