### ISSUE TITLE
I failed run docker image on v100 

### ISSUE THREAD

**Issue by caijq0712** [gnina/gnina#207]
### Issue summary
I pull singularity image from docker pull gnina/gnina:latest.
And then I run it on v100 gpu.
but  occur this " WARNING: No GPU detected. CNN scoring will be slow. "

**Comment by caijq0712** [comment]
In the img, i find the viersion that is gnina v1.0.1 master:aa41230   Built Mar 23 2021. and cuda version is 10.2

**Comment by dkoes** [comment]
You probably need to update the cuda version in the docker image.

**Comment by caijq0712** [comment]
thanks alot Mr Koes
