### ISSUE TITLE
How can I run python scripts in Gnina Docker?

### ISSUE THREAD

**Issue by Kerro-junior** [gnina/gnina#216]
### Issue summary
I pull the latest docker image of gnina/gnina. but I find it doesn't have python in PATH
I bundle the gnina/data to my host system directory '/home/user/gnina_docker'

How can I run python script, which is able to dock molecules of PDBbind with gnina in batch?

```
import os
import subprocess
import os

root_dir = '~/gnina/data'

for sub_dir, _, _ in os.walk(root_dir):
    code = sub_dir.split('/')[-1]
    ligand_file = f'{root_dir}/{sub_dir}/{code}_ligand.sdf'
    receptor_file = f'{root_dir}/{sub_dir}/{code}_pocket.pdb'
    cmd = f'gnina --receptor {receptor_file} --ligand {ligand_file} --autobox_ligand {ligand_file} --out {root_dir}/{sub_dir}/{code}_docked.sdf'
    subprocess.call(cmd, shell=True)
```

### Your system configuration
Operating system: Linux/Docker
CUDA version (if applicable): host system cuda 11.x
Python version:python3.6

**Comment by dkoes** [comment]
This really isn't an issue with gnina, but with general understanding of linux and docker.  Please try to solve issues that are not gnina-specific using resources other than this forum.

Run `python3` instead of `python`.
