### ISSUE TITLE
Runtime Error  boost::thread_resource_error

### ISSUE THREAD

**Issue by Kerro-junior** [gnina/gnina#217]
### Issue summary
```
WARNING: No GPU detected. CNN scoring will be slow.
Recommend running with single model (--cnn crossdock_default2018)
or without cnn scoring (--cnn_scoring=none).

### Steps to reproduce
I use the pdbbind database 1a1e to dock in gnina docker, every file is downloaded from PDBbind directly without change

### Your system configuration
Operating system: Linux/Docker (the docker cannot use GPU )

**Comment by dkoes** [comment]
My guess is you are running on a system that limits the number of threads you can run.  Check `/proc/sys/kernel/threads-max`

https://stackoverflow.com/questions/22569805/boost-thread-throwing-exception-thread-resource-error-resource-temporarily-una

If you run with `--cpu=1` gnina will use fewer threads (and of course take longer).

**Comment by Kerro-junior** [comment]
The gnina still doesn't work even after assigning the` --cpu=1` in my gnina/gnina docker container:

`root@88e3591f84a8:~/gnina/data/2al5# gnina -r 2al5_protein.pdb --ligand 2al5_ligand.sdf --autobox_ligand 2al5_ligand.sdf -o docked.sdf.gz --cnn_scoring=none --cpu=1`

`==============================
*** Open Babel Warning  in ReadMolecule
  WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 3 that is
less than the observed explicit valence 4.
WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 1 that is
less than the observed explicit valence 2.
WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 3 that is
less than the observed explicit valence 4.
WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 1 that is
less than the observed explicit valence 2.
WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 3 that is
less than the observed explicit valence 4.
WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 3 that is
less than the observed explicit valence 4.
WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 3 that is
less than the observed explicit valence 5.
WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 1 that is
less than the observed explicit valence 2.
WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 1 that is
less than the observed explicit valence 2.

Runtime Error
boost::thread_resource_error
GPU memory usage: used = 0.000000, free = 0.000000 MB, total = 0.000000 MB`

Is this something wrong with my docker container or the GPU?

 (My teacher said they wouldn't allow the GPU usage for normal users these days for an important huge project, they would immediately kill any program using GPU.However, I already set the `--cnn_scoring=none...`)

**Comment by Kerro-junior** [comment]
Additional ERROR information:
```
WARNING: No GPU detected. CNN scoring will be slow.
Recommend running with single model (--cnn crossdock_default2018)
or without cnn scoring (--cnn_scoring=none).

Commandline: gnina -r 2al5_protein.pdb --ligand 2al5_ligand.sdf --autobox_ligand 2al5_ligand.sdf -o docked.sdf.gz --cnn_scoring=none
==============================
*** Open Babel Warning  in ReadMolecule
  WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 3 that is
less than the observed explicit valence 4.

```

**Comment by dkoes** [comment]
This really seems like an issue with your environment. Do other multi-threaded programs work?

**Comment by Kerro-junior** [comment]
Sorry I do not have other multi-threaded programs to test...
### System Information
I use the gnina/gnina:1.0.3 image to build docker container in my CentOS7 system, it successfully created and started.
When I was in the container, I run nvcc --version, it says the CUDA is 11.7 (so the CUDA is good, the problem might be the GPU)

### Procedure to dock
in the directory, I run `gnina -r 1a1e_protein.pdb -l 1a1e_ligand.sdf --autobox_ligand 1a1e_ligand.sdf -o test.sdf`

### ERROR
```
gnina v1.0.3 HEAD:8537041   Built Jul 24 2023.
gnina is based on smina and AutoDock Vina.
Please cite appropriately.

WARNING: No GPU detected. CNN scoring will be slow.
Recommend running with single model (--cnn crossdock_default2018)
or without cnn scoring (--cnn_scoring=none).

Commandline: gnina -r 1a1e_protein.pdb -l 1a1e_ligand.sdf --autobox_ligand 1a1e_ligand.sdf -o test.sdf
==============================
*** Open Babel Warning  in ReadMolecule
  WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 3 that is
less than the observed explicit valence 4.
```


```
less than the observed explicit valence 2.
WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 1 that is
less than the observed explicit valence 2.


Runtime Error
boost::thread_resource_error
GPU memory usage: used = 0.000000, free = 0.000000 MB, total = 0.000000 MB
```

**Comment by Kerro-junior** [comment]
I even use `--gpus '"device=0"'` when create the docker container, but it still doesn't work. Is this command right ?

`docker run --name gnina -v /home/Kerror/gnina_docker:/scr/data --gpus '"device=0"' -idt gnina/gnina`

**Comment by Kerro-junior** [comment]
This time, I have set` --gpu all` when creating the docker container.

`docker run --name gnina -v /data2/Kerror/gnina_docker:/scr --gpus all -idt gnina/gnina`

it still cannot detect GPU, and finally report thread error:

`
WARNING: No GPU detected. CNN scoring will be slow.
Recommend running with single model (--cnn crossdock_default2018)
or without cnn scoring (--cnn_scoring=none).

Commandline: gnina -r 1a4k_pocket.pdb -l 1a4k_ligand.sdf --autobox_ligand 1a4k_ligand.sdf -o test.sdf
==============================
*** Open Babel Warning  in PerceiveBondOrders
  Failed to kekulize aromatic bonds in OBMol::PerceiveBondOrders

==============================
*** Open Babel Warning  in ReadMolecule
  WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 3 that is
less than the observed explicit valence 4.

==============================
*** Open Babel Warning  in ReadMolecule
  WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 3 that is
less than the observed explicit valence 4.
WARNING: Problem interpreting the valence field of an atom
The valence field specifies a valence 1 that is
less than the observed explicit valence 2.
`
`Runtime Error
boost::thread_resource_error
GPU memory usage: used = 0.000000, free = 0.000000 MB, total = 0.000000 MB
`

IS THIS BECAUSE THE GPU DOES NOT HAVE FREE SPACE?

**Comment by dkoes** [comment]
It isn't a seeing a GPU.  The problem is the thread_resource_error, which is an issue with your environment.
Check  `/proc/sys/kernel/threads-max`

https://stackoverflow.com/questions/22569805/boost-thread-throwing-exception-thread-resource-error-resource-temporarily-una

**Comment by Kerro-junior** [comment]
After checking my /proc/sys/kernel/threads-max, it reports:

```
root@f7c1fba21cb2:~/data/1a4k# cat /proc/sys/kernel/threads-max
2059132
```

Surely it is enough.

**Comment by JonasLi-19** [comment]
> @dkoes Hi Professor! After checking my /proc/sys/kernel/threads-max, it reports:
> 
> ```
> root@f7c1fba21cb2:~/data/1a4k# cat /proc/sys/kernel/threads-max
> 2059132
> ```
> 
> Surely it is enough. So I do not know where the problem is for :
> 
> ```
> Runtime Error
> boost::thread_resource_error
> GPU memory usage: used = 0.000000, free = 0.000000 MB, total = 0.000000 MB
> ```


I think you could try to use less MC steps etc. ?

**Comment by JonasLi-19** [comment]
@dkoes  There must be something imcompatible  with your gnina/gnina image in docker-hub, I encounter this same issue last month.

> <img alt="image" width="707" src="https://user-images.githubusercontent.com/107249755/266318572-19c5c9ef-c97c-42fd-bfb6-d3e33164f6ab.png">
> The error is twofold though, it does not detect the GPU but then it does not even detect any available CPU threads.
> 
> <img alt="image" width="764" src="https://user-images.githubusercontent.com/107249755/266318905-afbb332d-c85c-4f6a-8549-2806512c646b.png">

**Comment by Dadiao-shuai** [comment]
Dear professor Koes,
I follow the instruction 'docker pull gnina/gnina' to use gnina in docker, 
then build container using all gpus:`docker run -itd --gpus all -v /home/shuai/gnina_docker:/root/data --name gnina_official gnina/gnina:latest`
and I encoutered the same issue:

`gnina -r pocket.pdb -l ligand.sdf --autobox_ligand ligand.sdf -o test_docked.sdf`

```
Runtime Error
boost::thread_resource_error
GPU memory usage: used = 0.000000, free = 0.000000 MB, total = 0.000000 MB
```

I tried **nvidia-smi**, it shows as:
![图片](https://github.com/gnina/gnina/assets/145245978/ae7f226e-1f72-4ab6-b4d3-e7157711e41e)

I tried **nvcc --version**:
![图片](https://github.com/gnina/gnina/assets/145245978/30b36540-e235-4200-9f19-aa7d9fab847b)
