### ISSUE TITLE
Stray '\341' (was \240 previously) in redock_2018_1.def breaks make

### ISSUE THREAD

**Issue by toddjm** [gnina/gnina#221]
### File redock_2018_1.def - both from cloning this repo (error is '\240') and from colleague (error is '\341') - appears to be corrupted upon translation

``In file included from /home/todd/code/gnina/gninasrc/lib/cnn_data.cpp:50:
/home/todd/code/gnina/gninasrc/lib/models/weights/redock_2018_1.def:36705:24: error: stray ‘\341’ in program
36705 |   0xed, 0x08, 0x4d, 0x3�, 0xd9, 0x12, 0xef, 0x39, 0x16, 0x48, 0x0c, 0xb9``

### Steps to reproduce
Everything from the instructions, this occurs during make in the build directory.

### Your system configuration
Operating system:  Linux finch 6.2.0-31-generic #31~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Aug 16 13:45:26 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
Compiler:
CUDA version (if applicable):
CUDNN version (if applicable):
Python version:

-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version           :   1.0.0
--   Git               :   v1.0.3-22-gda19662b
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -Wno-deprecated-declarations -Wno-unknown-pragmas -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -Wno-deprecated-declarations -Wno-unknown-pragmas -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release
-- 
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   ON
--   CPU_ONLY          :   OFF
--   USE_OPENCV        :   0
--   USE_LEVELDB       :   0
--   USE_LMDB          :   0
--   USE_NCCL          :   OFF
--   ALLOW_LMDB_NOLOCK :   OFF
-- 
-- Dependencies:
--   BLAS              :   Yes (Atlas)
--   Boost             :   Yes (ver. 1.74)
--   glog              :   Yes
--   gflags            :   Yes
--   OpenBabel         :   No
--   protobuf          :   Yes (ver. ..)
--   CUDA              :   Yes (ver. 12.1)
-- 
-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_89
--   cuDNN             :   Not found
-- 
-- Python:
--   Interpreter       :   /usr/bin/python3 (ver. 3.10.12)
--   Libraries         :   /usr/lib/x86_64-linux-gnu/libpython3.10.so (ver 3.10.12)
--   NumPy             :   /home/todd/.local/lib/python3.10/site-packages/numpy/core/include (ver 1.23.1)
-- 
-- Documentaion:
--   Doxygen           :   /usr/bin/doxygen (1.9.1)
--   config_file       :   /home/todd/code/gnina/caffe/.Doxyfile
-- 
-- Install:
--   Install path      :   /usr/local

**Comment by dkoes** [comment]
I'm not sure what to do on my end.  There's no issue when I clone the repository and when you look at the file online (https://raw.githubusercontent.com/gnina/gnina/master/gninasrc/lib/models/weights/redock_2018_1.def) there is also no issue.

Does git realize the files are different?  Then checking it out again should fix the problem.

**Comment by toddjm** [comment]
David, thanks for getting back to me.

I've edited the file and should be good to go - fyi, here's what it looks like:

![image](https://github.com/gnina/gnina/assets/12463984/eee142d8-964e-4d29-86a2-72f499fb696d)

**Comment by toddjm** [comment]
Let's close and chalk it up to something on my end.
