### ISSUE TITLE
Wrongly used cmake -DCUDA_ARCH_NAME=All ..

### ISSUE THREAD

**Issue by Kerro-junior** [gnina/gnina#223]
`-DCUDA_ARCH_NAME=All` during cmake. 
So, does this option influences the dock result precision? Is this error fatal to caffe or something else? Do I need to reinstall gnina again?

### Your system configuration
Operating system: a ubuntu system in docker

![image](https://github.com/gnina/gnina/assets/139468131/5725bab6-1e7d-4db1-bd6a-180cb20f796f)

nvcc:
```
Cuda compilation tools, release 11.6, V11.6.124
Build cuda_11.6.r11.6/compiler.31057947_0
```

**Comment by dkoes** [comment]
What error are you talking about?

If you don't compile for all architectures, the resulting binary will not run on GPUs that it isn't compiled for.
