### ISSUE TITLE
error: no matching function for call to ‘libmolgrid::CallbackIndexTyper::CallbackIndexTyper   AND   error: no matching function for call to ‘libmolgrid::CallbackVectorTyper::CallbackVectorTyper

### ISSUE THREAD

**Issue by leticrisassis** [gnina/gnina#224]
### Issue summary
/gnina/build/libmolgrid-prefix/src/libmolgrid-build/python/bindings.cpp:207:60: **error**: no matching function for call to ‘libmolgrid::CallbackIndexTyper::CallbackIndexTyper(PythonCallbackIndexTyper::PythonCallbackIndexTyper(boost::python::api::object, unsigned int, boost::python::list)::<lambda(OpenBabel::OBAtom*)>, unsigned int&, std::vector<std::__cxx11::basic_string<char> >)’
  207 |     }, ntypes, list_to_vec<std::string>(names)), callback(c) {

/gnina/build/libmolgrid-prefix/src/libmolgrid-build/python/bindings.cpp:240:64: **error**: no matching function for call to ‘libmolgrid::CallbackVectorTyper::CallbackVectorTyper(PythonCallbackVectorTyper::PythonCallbackVectorTyper(boost::python::api::object, unsigned int, boost::python::list)::<lambda(OpenBabel::OBAtom*, std::vector<float>&)>, unsigned int&, std::vector<std::__cxx11::basic_string<char> >)’
  240 |           ntypes, list_to_vec<std::string>(lnames)), callback(c) {

### Steps to reproduce
The error occurs during installation. After executing the "make" command.

### Your system configuration
Operating system: Ubuntu 22
Compiler: g++ 11.4
CUDA version (if applicable): 12.2
CUDNN version (if applicable):  nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0

Python version: 3.10.12

**Comment by dkoes** [comment]
There's no issue building gnina in a clean Ubuntu 22.04 docker container:
https://github.com/gnina/gnina/blob/master/docker/ubuntu-22.04/Dockerfile

My guess is you have multiple versions of OpenBabel installed and the libraries being linked don't match the header files included during compilation.

**Comment by leticrisassis** [comment]
Understood, thank you!
