### ISSUE TITLE
dockerfile for ubuntu outdated

### ISSUE THREAD

**Issue by Dadiao-shuai** [gnina/gnina#225]
### Issue summary
```
$ docker pull nvidia/cuda:11.4.2-cudnn8-devel-ubuntu18.04
Error response from daemon: manifest for nvidia/cuda:11.4.2-cudnn8-devel-ubuntu18.04 not found: manifest unknown: manifest unknown
```

### Steps to reproduce
```
$ docker build -t gnina_ubuntu18 .
Sending build context to Docker daemon  3.072kB
Step 1/6 : FROM nvidia/cuda:11.4.2-cudnn8-devel-ubuntu18.04
manifest for nvidia/cuda:11.4.2-cudnn8-devel-ubuntu18.04 not found: manifest unknown: manifest unknown
```

I guess it needs to modify according to the current release in Dockerhub.

===========================================================================

Additionally, when I use the latest ubuntu22.04 dockerfile to build new image, it has an warning:
`WARNING: apt does not have a stable CLI interface. Use with caution in scripts.`

**Comment by Dadiao-shuai** [comment]
**Dear Professor, the dockerfile in ubuntu22.04 is also needed to be update.**
Not to mention that the cuda-11.7.0-devel is changed into 11.7.1-devel, so is the pubilc key for Ubuntu to use apt install to packages. 
So after I changed the Dockerfile into `FROM nvidia/cuda:11.7.1-devel-ubuntu22.04`, the ERROR is :

```
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
......
Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Get:3 https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu2204/x86_64  InRelease [1581 B]
Err:1 http://security.ubuntu.com/ubuntu jammy-security InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
Get:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [109 kB]
Err:2 http://archive.ubuntu.com/ubuntu jammy InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
Err:3 https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu2204/x86_64  InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
Err:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
Err:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C

```

**Comment by Dadiao-shuai** [comment]
Also I find the images of `nvidia/cuda:11.*-devel-ubuntu*` often causes errors about the key:
![fea37d2c1ebf55e0e4da6cd1e9a81f2](https://github.com/gnina/gnina/assets/145245978/fedd0212-974c-4f04-a0fe-cad721669d47)
![image](https://github.com/gnina/gnina/assets/145245978/ddf146e6-fafb-4d41-87e7-c6e19391b00b)

I tried apt-get install dirmngr but this command also failed.

I also tried apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 871920D1991BC93C   apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A4B469963BF863CC but it doesn't work out right..

**Comment by Kerro-junior** [comment]
Hi, I'd like to know why you set ` -DPYTHON_EXECUTABLE=/usr/bin/python3 -DHAVE_PYTHON=0 -DBUILD_python=OFF` in **gnina/docker/compat**

If set the` -DBUILD_python=OFF`, can I use this docker container to run train.py?

**Comment by dkoes** [comment]
I would run using a newer operating system than compat.  The goal of compat was to get the most compatible possible gnina binary, not to enable training.
