### ISSUE TITLE
Python path setting question when install Gnina 

### ISSUE THREAD

**Issue by JonasLi-19** [gnina/gnina#226]
### Issue summary
I find my python and python3 are all pointed to `mambaforge/bin/python* ` (mamba is just the same as conda)
```
(base) $ mamba deactivate
$ which python3
~/mambaforge/bin/python3
$ python
Python 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
$ which python
~/mambaforge/bin/python
```
It is because I add the mambaforge/bin to `~/.bashrc`

But even I delete the `export ...`, the default python is still in `~/mambaforge/bin`
```
(base)$ source ~/.bashrc
(base)$ mamba deactivate
$ which python
~/mambaforge/bin/python
$ which python3
~/mambaforge/bin/python3
```

So, when I install gnina, do I have to specific the python3 to `~/mambaforge/bin/python3`?

### Your system configuration
Operating system: CentOS
CUDA version (if applicable):11.8
Python version: 3.10

**Comment by dkoes** [comment]
If that is the python you want to use and you are installing the dependencies for.
