### ISSUE TITLE
GPU Failure on CNN

### ISSUE THREAD

**Issue by scheah86** [gnina/gnina#230]
### Issue summary
Hello there,

I've submitted a GNINA script to execute CNN on approximately 3.7 million compounds, leveraging the GPU capabilities of the supercomputer. However, the team managing the supercomputer informed me that the GPU is not being utilized efficiently or possibly even detected. When I log into any of the nodes associated with my jobs, I frequently observe "GPU-Util 0%" as shown below. Could you provide guidance on addressing this issue? Thank you.

[root@gina14 ~]# nvidia-smi 
Mon Oct  9 14:13:01 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100-SXM4-80GB          On  | 00000000:01:00.0 Off |                    0 |
| N/A   28C    P0              75W / 500W |   5410MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-SXM4-80GB          On  | 00000000:41:00.0 Off |                    0 |
| N/A   28C    P0              76W / 500W |   5410MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   2  NVIDIA A100-SXM4-80GB          On  | 00000000:81:00.0 Off |                    0 |
| N/A   31C    P0              79W / 500W |   5410MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   3  NVIDIA A100-SXM4-80GB          On  | 00000000:C1:00.0 Off |                    0 |
| N/A   28C    P0              74W / 500W |   5410MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A     11476      C   /fred/oz123/XXX/gnina                     5400MiB |
|    1   N/A  N/A     11586      C   /fred/oz123/XXX/gnina                     5400MiB |
|    2   N/A  N/A     11536      C   /fred/oz123/XXX/gnina                     5400MiB |
|    3   N/A  N/A     11481      C   /fred/oz123/XXX/gnina                     5400MiB |
+---------------------------------------------------------------------------------------+

### Steps to reproduce
Attached in the comment section. Thank you.

### Your system configuration
Operating system:
Compiler:
CUDA version (if applicable):
CUDNN version (if applicable):
Python version:

**Comment by AquifersBSIM** [comment]
I would like to add on that at certain times the GPU was utilized at maybe 40% to 70%. The utilization fluctuates, I would say often.   Even more puzzling was that certain execution of GNINA CNN utilizes 0% of the GPU. It was understood that CNN requires the GPU for better and efficient scoring.

**Comment by dkoes** [comment]
A reproducible test case would be greatly appreciated.

**Comment by scheah86** [comment]
1) Log into a supercomputer account
2) _python 2_GNINA_sdf_v5_atb5_ (we modified the ligand autobox_add value to be 5)
3) Input protein, ligand, enter 5 to choose CNN, type yes for GPU, then press enter to process all sdf files.

After that, we received comments from the supercomputer team as mentioned. Please let me know if any additional info is needed. Thanks for investigating this matter.

The GNINA script we used is as below: 
import os
import subprocess

def generate_slurm_script(output_script, job_name, protein_name, ligand_file, reference_ligand, docking_mode, use_gpu):
    if docking_mode == 1:
        output_prefix = "BD"
    elif docking_mode == 2:
        output_prefix = "Vina"
    elif docking_mode == 3:
        output_prefix = "Vinardo"
    elif docking_mode == 4:
        output_prefix = "AD4"
    elif docking_mode == 5:
        output_prefix = "CNN"
    else:
        raise ValueError("Invalid docking mode")

    with open(output_script, "w") as script_file:
        script_file.write("#!/bin/bash\n")
        script_file.write("#\n")
        script_file.write(f"#SBATCH --job-name={job_name}\n")
        script_file.write(f"#SBATCH --output={output_prefix}_{job_name}.txt\n")  # Updated output file name
        script_file.write("#\n")
        script_file.write("#SBATCH --ntasks=1\n")
        script_file.write("#SBATCH --cpus-per-task=1\n")
        script_file.write("#SBATCH --ntasks-per-node=1\n")
        script_file.write("#SBATCH --time=168:00:00\n")
        script_file.write("#SBATCH --mem-per-cpu=5000\n")
        if use_gpu:
            script_file.write("#SBATCH --gres=gpu:1\n")
        script_file.write("\n")
        script_file.write("ml imkl/2023.0.0")
        script_file.write("\n")
        if docking_mode == 1:  # Blind Docking
            script_file.write(f"/fred/oz241/schl/gnina -r {protein_name}.pdb -l {ligand_file}.sdf --autobox_ligand {protein_name} -o {output_prefix}_{protein_name}_{ligand_file}.sdf --exhaustiveness 64 --autobox_add 5\n")
        elif docking_mode == 2:  # Docking with Vina
            script_file.write(f"/fred/oz241/schl/gnina -r {protein_name}.pdb -l {ligand_file}.sdf --autobox_ligand {reference_ligand} --scoring vina --cnn_scoring none -o {output_prefix}_{protein_name}_{ligand_file}.sdf --autobox_add 5")
        elif docking_mode == 3:  # Docking with Vinardo
            script_file.write(f"/fred/oz241/schl/gnina -r {protein_name}.pdb -l {ligand_file}.sdf --autobox_ligand {reference_ligand} --scoring vinardo --cnn_scoring none -o {output_prefix}_{protein_name}_{ligand_file}.sdf --autobox_add 5")
        elif docking_mode == 4:  # Docking with Autodock 4
            script_file.write(f"/fred/oz241/schl/gnina -r {protein_name}.pdb -l {ligand_file}.sdf --autobox_ligand {reference_ligand} --scoring ad4_scoring --cnn_scoring none -o {output_prefix}_{protein_name}_{ligand_file}.sdf --autobox_add 5")
        elif docking_mode == 5:  # Docking with CNN rescoring
            script_file.write(f"/fred/oz241/schl/gnina -r {protein_name}.pdb -l {ligand_file}.sdf --autobox_ligand {reference_ligand} --cnn_scoring rescore -o {output_prefix}_{protein_name}_{ligand_file}.sdf --pose_sort_order=CNNaffinity --autobox_add 5")
        script_file.write("\n")

    return output_script

def main():
    protein_name = input("Enter the protein name (pdb format, exclude suffix): ")
    reference_ligand = input("Enter the name of the reference ligand (include prefix): ")

    use_gpu = input("Do you require GPU (yes/no): ").lower() == 'yes'

    print("Select docking mode:")
    print("1. Blind Docking")
    print("2. Docking with Vina")
    print("3. Docking with Vinardo")
    print("4. Docking with Autodock 4")
    print("5. Docking with CNN rescoring")

    docking_mode = int(input("Enter the mode number: "))

    ligand_file = input("Enter the ligand file (sdf format, exclude suffix, leave empty to process all sdf files): ")

    if ligand_file:  # Process a specific sdf file
        job_name = f"docking_{protein_name}_{ligand_file}"
        slurm_script = generate_slurm_script("docking_script.sh", job_name, protein_name, ligand_file, reference_ligand, docking_mode, use_gpu)
        # Submit the SLURM job using subprocess
        subprocess.run(["sbatch", slurm_script])
        print("Docking job submitted.")
    else:  # Process all sdf files in the folder
        sdf_files = [filename for filename in os.listdir() if filename.endswith('.sdf')]
        for sdf_file in sdf_files:
            job_name = f"docking_{protein_name}_{os.path.splitext(sdf_file)[0]}"
            slurm_script = generate_slurm_script("docking_script.sh", job_name, protein_name, os.path.splitext(sdf_file)[0], reference_ligand, docking_mode, use_gpu)
            # Submit the SLURM job using subprocess
            subprocess.run(["sbatch", slurm_script])
            print(f"Docking job for {sdf_file} submitted.")

if __name__ == "__main__":
    main()

**Comment by dkoes** [comment]
This doesn't sound like a failure to me.  Only the CNN scoring uses the GPU, sampling is still all CPU - it is not unexpected for GPU utilization to be less than 100%, perhaps substantially so.

**Comment by scheah86** [comment]
Thank you for the clarification. I'll notify the supercomputer team regarding this issue. Much appreciated.
