### ISSUE TITLE
output sdf file doesn't have CNNscore/CNNaffinity

### ISSUE THREAD

**Issue by JonasLi-19** [gnina/gnina#231]
### Issue summary
I install gnina in a ubuntu20.04 system and didn't wget the latset-commit before I install gnina.
After installing the gnina, I ran the following command to dock:
`gnina -r 1a4k_pocket.pdb -l 1a4k_ligand.mol2 --autobox_ligand 1a4k_ligand.mol2 -o test.sdf`

I can see it works well and have calculated poses' score and affinity showing in the terminal, BUT the output sdf file doesn't have CNNscore/CNNaffinity written:

```
1a4k_ligand


 33 36  0  0  0  0  0  0  0  0999 V2000
   20.9929    9.1709    2.5160 N   0  0  0  0  0  0  0  0  0  0  0  0
   20.5487    9.8794    3.6077 C   0  0  0  0  0  0  0  0  0  0  0  0
...
 26 27  2  0
 29 30  1  0
 30 31  1  0
 31 33  2  0
 31 32  1  0
 23 24  1  0
 25 28  1  0
M  CHG 1  32  -1
M  END
> <minimizedAffinity>
0.00000

$$$$
...

```

**Comment by dkoes** [comment]
Are you sure your box is right?  An affinity of 0 would indicate otherwise.  The CNN scores simply don't output if they are zero.

**Comment by JonasLi-19** [comment]
I am sure the box is right because I use autobox_ligand same as the ligand!

Commandline: gnina -r 1a30_pocket.pdb -l 1a30_ligand.mol2 --autobox_ligand 1a30_ligand.mol2 -o test.sdf
Using random seed: 377909198

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |  affinity  |    CNN     |   CNN
     | (kcal/mol) | pose score | affinity
-----+------------+------------+----------
    1       -8.42       0.8277      7.483
    2       -7.92       0.7172      6.957
    3       -8.44       0.7067      7.243
    4       -7.04       0.5397      7.091
    5       -7.78       0.4669      7.091
    6       -7.35       0.3749      6.940
    7       -7.39       0.3676      6.812
    8       -7.56       0.3585      6.365
    9       -7.94       0.3460      6.681


But the output test.sdf is like:

```
...
  6  8  1  0
  6  9  1  0
  6 10  1  0
  4  5  1  0
 18 19  1  0
M  CHG 1   6   1
M  CHG 1  14  -1
M  CHG 1  22  -1
M  CHG 1  30  -1
M  END
> <minimizedAffinity>
0.00000

$$$$
1a30_ligand


 31 30  0  0  0  0  0  0  0  0999 V2000
    9.5206   26.1057    6.3275 C   0  0  0  0  0  0  0  0  0  0  0  0
    7.7742   26.8479    4.7953 C   0  0  0  0  0  0  0  0  0  0  0  0
```

**Comment by dkoes** [comment]
That is very strange.  Can you provide the source files so I can see if I can reproduce the issue?

**Comment by JonasLi-19** [comment]
[1a30.zip](https://github.com/gnina/gnina/files/13111395/1a30.zip)
this is the molecule I used. I tried to put them in Pymol and they fit well.
![图片](https://github.com/gnina/gnina/assets/54503824/4cf7fc82-f630-4dd0-9c2b-c417c4f91caa)

**Comment by dkoes** [comment]
I can't reproduce this.  If you use the pre-built executable do you get the same results?

https://github.com/gnina/gnina/releases/download/v1.0.3/gnina

**Comment by JonasLi-19** [comment]
THE FOLLOWING IS WHAT I GOT WHEN USING GNINA BUILT FROM SOURCE, and the output.sdf:             
```
             (_)            
   __ _ _ __  _ _ __   __ _ 
  / _` | '_ \| | '_ \ / _` |
 | (_| | | | | | | | | (_| |
  \__, |_| |_|_|_| |_|\__,_|
   __/ |                    
  |___/                     

gnina  master:e82ffd7   Built Oct 17 2023.
gnina is based on smina and AutoDock Vina.
Please cite appropriately.

Commandline: gnina -r 1a4k_pocket.pdb -l 1a4k_ligand.sdf --autobox_ligand 1a4k_ligand.sdf --cnn_model default2018.model --cnn_weights crossdock_default2018.caffemodel -o output.sdf
...

Using random seed: -1798352758

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

mode |  affinity  |    CNN     |   CNN
     | (kcal/mol) | pose score | affinity
-----+------------+------------+----------
    1      -11.27       0.8512      6.413
    2      -10.92       0.8122      6.436
    3       -2.03       0.7911      4.719
    4       -8.71       0.6847      6.298
    5       -3.84       0.6646      4.771
    6       -8.33       0.5193      5.984
    7       -6.52       0.5164      5.346
    8       -9.70       0.5128      6.048
    9       -7.03       0.4949      5.560
```
OUTPUT.SDF:
```
1a4k_ligand

 33 36  0  0  0  0  0  0  0  0999 V2000
   21.0170    9.2085    2.5210 N   0  0  0  0  0  0  0  0  0  0  0  0
   20.5858    9.9138    3.6199 C   0  0  0  0  0  0  0  0  0  0  0  0
  ...
 23 24  1  0
 25 28  1  0
M  CHG 1  31  -1
M  END
> <MOLECULAR_FORMULA>
C21H22N3O7

> <MOLECULAR_WEIGHT>
428.2

> <NUM_HB_ATOMS>
9

> <NUM_ROTOR>
3

> <XLOGP2>
-0.14

> <minimizedAffinity>
0.00000

$$$$
1a4k_ligand

 33 36  0  0  0  0  0  0  0  0999 V2000
   20.8371    9.1079    2.4268 N   0  0  0  0  0  0  0  0  0  0  0  0
   20.4842    9.8180    3.5503 C   0  0  0  0  0  0  0  0  0  0  0  0
   ...
 23 24  1  0
 25 28  1  0
M  CHG 1  31  -1
M  END
> <MOLECULAR_FORMULA>
C21H22N3O7

> <MOLECULAR_WEIGHT>
428.2

> <NUM_HB_ATOMS>
9

> <NUM_ROTOR>
3

> <XLOGP2>
-0.14

> <minimizedAffinity>
0.00000

```

**THE POSSIBLE REASONS I GUESS might be:**
the latest openbabel requires rapidjson's include, which might cause some bug?
I have to add the rapidjson otherwise the openbabel won't be installed:
`openbabel/include/openbabel/json.h:22:10: fatal error: rapidjson/document.h: No such file or directory
   22 | #include <rapidjson/document.h>
`
BUT I remember we do not need to download rapidjson several weeks ago, and back then my gnina works well!

(I will tell you the result of pre-built excutable of gnina_v1.3 later)

**Comment by dkoes** [comment]
If the pre-built executable works this is almost certainly an issue with your openbabel install.

**Comment by JonasLi-19** [comment]
yes, the pre-built executable works! thanks, I will try to install earlier openbabel
