### ISSUE TITLE
Not able to run gnina with receptor and ligand information

### ISSUE THREAD

**Issue by dibya035643** [gnina/gnina#233]
### Issue summary
Not able to run gnina with receptor and ligand information. Reported error:
 
An internal error occurred in /tmp/gnina/gninasrc/lib/tree.h(185). 

Please report this error at https://github.com/gnina/gnina/issues
Please remember to include the following in your problem report:
    * the EXACT error message,
    * your version of the program,
    * the type of computer system you are running it on,
	* all command line options,
	* configuration file (if used),
    * ligand file as PDBQT,
    * receptor file as PDBQT,
	* flexible side chains file as PDBQT (if used),
	* output file as PDBQT (if any),
    * input (if possible),
	* random seed the program used (this is printed when the program starts).

### Steps to reproduce
./gnina --receptor DRD2_6cm4_protein_wh.pdbqt --config DRD2_config.txt --ligand SMILE_DRD2_1.mol2 --out DRD2_1.out --log DRD2_1.log

[DRD2_config.txt](https://github.com/gnina/gnina/files/13234904/DRD2_config.txt)
[DRD2_1.log](https://github.com/gnina/gnina/files/13234906/DRD2_1.log)
The SMILE_DRD2_1.mol2 is a mol2 file uploaded as mol2.txt
[SMILE_DRD2_1.mol2.txt](https://github.com/gnina/gnina/files/13235235/SMILE_DRD2_1.mol2.txt)

the DRD2_6cm4_protein_wh.pbdqt file is the receptor file in pdb qt file uploaded as pdbqt.txt
[DRD2_6cm4_protein_wh.pdbqt.txt](https://github.com/gnina/gnina/files/13235228/DRD2_6cm4_protein_wh.pdbqt.txt)
There is no error shown for the same.

### Your system configuration
Operating system: Ubuntu 20.04.5 LTS 
Compiler: 
CUDA version (if applicable): NA
CUDNN version (if applicable): NA
Python version:  3.8.10

**Comment by dkoes** [comment]
All the coordinates of your ligand are zero.  You need to provide a valid conformer.
