### ISSUE TITLE
libmolgrid with custom typer

### ISSUE THREAD

**Issue by jacobdurrant** [gnina/gnina#240]
### Issue summary

I'm struggling to figure out how to implement a custom typer using libmolgrid. [This page](https://gnina.github.io/libmolgrid/tutorials/custom_atom_typer_example.html) shows how to make the typer, but not how to use it with molgrid.ExampleProvider

### Steps to reproduce

Please see this repository that illustrates what I want to do: https://github.com/durrantlab/molgriddebug

Specifically this file: https://github.com/durrantlab/molgriddebug/blob/main/test.ipynb

Then search for "HELP US DAVID KOES!!!"

### Your system configuration
Operating system: Ubuntu 20.04.1
Compiler: Not sure
CUDA version (if applicable): 11.4
CUDNN version (if applicable): Not sure
Python version: Python 3.9.16

**Comment by dkoes** [comment]
You need to wrap your function with `PythonCallbackVectorTyper` (or `PythonCallbackIndexTyper`) and then pass them as positional arguments to ExampleProvider:  
```python
t = molgrid.PythonCallbackVectorTyper(mytyper, 2, ["anum","valence"])
example = molgrid.ExampleProvider(t,
    default_batch_size=1
)
```
You can pass multiple typers (e.g., you might have separate receptor and ligand typers) and these will be mapped to your input structures (e.g., each example might specify two structure files where the first is always the receptor and the second the ligand).
