### ISSUE TITLE
Failed for cmake to find proper version of CUDA installation when multiple CUDA are installed

### ISSUE THREAD

**Issue by haotianteng** [gnina/gnina#257]
### Issue summary
So we are trying to install gnina in a multi-CUDA environment where CUDA is dynamically load by module, so there are multiple version of CUDA under  /opt/packages/cuda/ path:

`ls /opt/packages/cuda/`
`v11.6.0  v11.7.1  v12.0.0  v12.1.0  v12.1.1  v12.3.2  v12.4.0`

And the version is controlled by module system by setting LD_LIBRARY_PATH, PATH and CUDA_HOME:
`echo $CUDA_HOME`
`/opt/packages/cuda/v12.4.0`
`echo $LD_LIBRARY_PATH`
`/opt/packages/cuda/v12.4.0/lib64:/opt/packages/cuda/v12.4.0/nvvm/lib64:/opt/packages/cuda/v12.4.0/extras/CUPTI/lib64
`

### Steps to reproduce
`cmake ..`

CMake Error at /home/MolecularDocking/gnina/cmake-3.25.2-linux-x86_64/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find CUDA: Found unsuitable version "11.7", but required is at
  least "12.0" (found /opt/packages/cuda/v11.7.1)
Call Stack (most recent call first):
  /home/MolecularDocking/gnina/cmake-3.25.2-linux-x86_64/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:598 (_FPHSA_FAILURE_MESSAGE)
  /home/MolecularDocking/gnina/cmake-3.25.2-linux-x86_64/share/cmake-3.25/Modules/FindCUDA.cmake:1268 (find_package_handle_standard_args)
  CMakeLists.txt:36 (find_package)

### Your system configuration
Operating system: CentOS
Compiler: GCC 10.2
CUDA version (if applicable): 12.4
CUDNN version (if applicable): 
Python version: 3.9

So it seems gnina FindCUDA module look into the /opt/packages/CUDA folder and found the older version of CUDA (here 11.7.1), but actually there are multiple CUDA folders under /opt/pcakges/CUDA.

**Comment by haotianteng** [comment]
I addressed this by setting -DCUDA_TOOLKIT_ROOT_DIR during to the cmake command:
`cmkae -DCUDA_TOOLKIT_ROOT_DIR=/opt/packages/cuda/v12.4.0/ ..`

Leave here the solution for other people who may encounter the same issue

**Comment by dkoes** [comment]
Did you try doing what the error message suggested and making sure the correct nvcc is in your path?

**Comment by haotianteng** [comment]
Okay I tried several things and it finally works, not sure which one nail it down:
1. I add the 
-DCUDA_NVCC_EXECUTABLE=/opt/packages/cuda/v12.4.0/bin/
2. remove the build folder and reconfigure again
3. set CUDA_HOME environment variable

Thanks for your quick reply!
