### ISSUE TITLE
Neural net scoring without docking

### ISSUE THREAD

**Issue by AqemiArnold** [gnina/gnina#265]
Hi all, 

It is not an issue, but a question. So thank you for your time.

I was wondering wether it is possible to only score poses coming from other docking softwares (`smina`, or others...).
If so, is there any pointer example script, because I haven't found any. (If there is, I apologize in advance).

Kind regards

**Comment by RMeli** [comment]
Hello. Yes, you should be able to use the `--score_only` command line option
```
   --score_only                       score provided ligand pose
```

**Comment by RMeli** [comment]
Be aware that those poses from other docking software might not be a minimum of the Vina scoring function. You might want to maybe use `--minimize` instead, to perform a local optimization of the input pose.

**Comment by AqemiArnold** [comment]
Thanks a lot, I'll try this.

Regards
