### ISSUE TITLE
rmsd values in gnina output

### ISSUE THREAD

**Issue by Lili-Cao** [gnina/gnina#266]
### Issue summary
Hi,

Is the rmsd values in Gnina output based on the whole molecule or its for the mcs?

Thanks!
Lili

### Your system configuration
Operating system:
Compiler:
CUDA version (if applicable):
CUDNN version (if applicable):
Python version:

**Comment by dkoes** [comment]
Whole molecule, but is not symmetry corrected. Best to use rdkit or obrms to calculate RMSDs.

**Comment by Lili-Cao** [comment]
Hi again, 

Is that possible to use the cnn to score a provided pose but not running the docking process?

Thanks!
Lili

**Comment by RMeli** [comment]
Yes, you can use the `--score_only` command line option to just perform the scoring. However, if you used a different docking software to generate the pose you might want to do use `--minimize` to perform a (local) optimisation before scoring with the CNN.

**Comment by Lili-Cao** [comment]
cool. 
Thanks!
