### ISSUE TITLE
--cnn_center_x/y/z arguments

### ISSUE THREAD

**Issue by fatih4534** [gnina/gnina#267]
### Issue summary
Hi, Sir. I would like to ask about CNN center arguments. What do these coordinates correspond to?
Thanks!
Fatih
### Your system configuration
Operating system:
Compiler:
CUDA version (if applicable):
CUDNN version (if applicable):
Python version:

**Comment by RMeli** [comment]
The coordinates correspond to the center of the grid used to discretise the protein-ligand binging site (used as input of the CNN).

**Comment by dkoes** [comment]
Generally speaking, you should not set them.
