### ISSUE TITLE
The cross-docking test set

### ISSUE THREAD

**Issue by DingLuoXMU** [gnina/gnina#273]
Hi, where can I find the cross-docking test set mentioned in the GNINA paper? It's a dataset containing 7937 cross-docked complexes.

**Comment by RMeli** [comment]
* [Files for the GNINA 1.0 paper](http://bits.csb.pitt.edu/files/gnina1.0_paper/)
* [Scripts for the GNINA 1.0 paper](https://github.com/dkoes/GNINA-1.0)

The cross-docking dataset with 7937 complexes is a cleaned-up version of the protein-ligand pairs that can be found in [`pocketdiff.csv`](https://github.com/dkoes/GNINA-1.0/blob/main/data/crossdocking-flex/pocketdiff.csv). The cleanup procedure is performed in [MakeFlexGraphs.ipynb](https://github.com/dkoes/GNINA-1.0/blob/main/analysis_scripts/MakeFlexGraphs.ipynb). This is the one used for docking with flexible side-chains. 

Without the specific cleanup for flexible side chains, the dataset has 7970 complexes and is available as [`crossdocked_ds_data.tar.gz`](http://bits.csb.pitt.edu/files/gnina1.0_paper/crossdocked_ds_data.tar.gz) data set.
