### ISSUE TITLE
Runtime error (out of memory)

### ISSUE THREAD

**Issue by nomoresomethingwentwrong** [gnina/gnina#279]
### Issue summary
<img width="1288" alt="Screenshot 2024-08-07 at 01 44 23" src="https://github.com/user-attachments/assets/bb293798-d833-4773-b02a-6e238d3ae145">

This error seemed to happen when the gpu was out of memory. However, the whole system crashed a few hours after this error occured. 

### Steps to reproduce
1. Use the pre-built binary gnina v1.0.3 

### Your system configuration
Operating system: Ubuntu 20.04
Compiler: GNU
CUDA version (if applicable): 12.5
CUDNN version (if applicable): 
Python version: 3.7

**Comment by dkoes** [comment]
I am unable to release a software update that increases the amount of memory on your GPU.
