### ISSUE TITLE
No GPU detected, while GPU is available

### ISSUE THREAD

**Issue by hajnal-adam** [gnina/gnina#283]
Hi! This might be a very noob question/issue, but I'm not the most experienced user. My issue is that gnina always gives the warning:
> WARNING: No GPU detected. CNN scoring will be slow.

However GPU should be available:
> Device: virgl (AMD Radeon Graphics (renoir, LLVM 15.0.7, DRM 3.54, ...) (0x1010)
     Version: 22.3.6
     Accelerated: yes
    
What am I missing? Thanks in advance!

**Comment by dkoes** [comment]
Only NVIDIA GPUs are supported.  Although perhaps there is partial acceleration with GNINA 1.3, which uses torch. I don't know, not having access to an AMD GPU.

**Comment by hajnal-adam** [comment]
So far no luck with v1.3, but thanks for the reply!
