### ISSUE TITLE
Non-GPU setup error

### ISSUE THREAD

**Issue by what-is-what** [gnina/gnina#285]
### Issue summary
Is there any methods for installation of non-GPU system?
The source code-based and pre-built binary-based methods were all GPU-based system.
I would appreciate it if you could tell me how to install non-GPU based.

### Your system configuration
Operating system:
Compiler:
CUDA version (if applicable):
CUDNN version (if applicable):
Python version:

**Comment by dkoes** [comment]
You install on a system without a GPU the same way you install on with a GPU. However, you need to have CUDA installed.  the pre-built binary should work fine on a non-GPU system.

**Comment by what-is-what** [comment]
If my understanding is correct, even if there is no GPU, is it correct to install GNINA after installing all CUDA-related libraries?

**Comment by dkoes** [comment]
Yes, the build process does not require a GPU.
