### ISSUE TITLE
Error in cmake

### ISSUE THREAD

**Issue by xavgit** [gnina/gnina#286]
### Issue summary:
$ git clone https://github.com/gnina/gnina.git
Cloning into 'gnina'...
remote: Enumerating objects: 44047, done.
remote: Counting objects: 100% (1384/1384), done.
remote: Compressing objects: 100% (668/668), done.
remote: Total 44047 (delta 700), reused 1294 (delta 641), pack-reused 42663 (from 1)
Receiving objects: 100% (44047/44047), 246.05 MiB | 2.80 MiB/s, done.
Resolving deltas: 100% (28986/28986), done.
xxxx@xxxx-X399-DESIGNARE-EX:\~/sources$ cd gnina_1.3/
xxxx@xxxx-X399-DESIGNARE-EX:\~/sources/gnina_1.3$ mkdir build
xxxx@xxxx-X399-DESIGNARE-EX:\~/sources/gnina_1.3$ cd build/
xxxx@xxxx-X399-DESIGNARE-EX:\~/sources/gnina_1.3/build$ cmake .. 
CMake Error at CMakeLists.txt:11 (cmake_policy):
  Policy "CMP0146" is not known to this version of CMake.

-- Found CUDA: /usr/local/cuda-12.3 (found suitable version "12.3", minimum required is "12.0") 
-- Found Python3: /usr/bin/python3.10 (found version "3.10.12") found components: Interpreter Development Development.Module Development.Embed 
-- Found CUDA: /usr/local/cuda-12.3 (found version "12.3") 
-- Caffe2: CUDA detected: 12.3
-- Caffe2: CUDA nvcc is: /usr/local/cuda-12.3/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda-12.3
-- Caffe2: Header version is: 12.3
-- /usr/local/cuda-12.3/lib64/libnvrtc.so shorthash is e150bf88
-- USE_CUSPARSELT is set to 0. Compiling without cuSPARSELt support
-- Autodetected CUDA architecture(s):  7.5
-- Added CUDA NVCC flags for: -gencode;arch=compute_75,code=sm_75
-- Torch found
-- Could NOT find libmolgrid (missing:  LIBMOLGRID_INCLUDE_DIR LIBMOLGRID_LIBRARY) 
libmolgrid will be fetched from git
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found version "1.74.0") found components: program_options system iostreams timer thread serialization filesystem date_time regex unit_test_framework 
-- Found Python3: /usr/bin/python3.10 (found version "3.10.12") found components: Interpreter 
-- Found RDKit libraries at /lib
-- Found RDKit library files at /lib/libRDKitFileParsers.so;/lib/libRDKitSmilesParse.so;/lib/libRDKitSubstructMatch.so;/lib/libRDKitGraphMol.so;/lib/libRDKitRDGeometryLib.so;/lib/libRDKitRDGeneral.so;/lib/libRDKitSubgraphs.so;/lib/libRDKitDataStructs.so;/lib/libRDKitDepictor.so
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found version "1.74.0") found components: unit_test_framework system 
-- /usr/bin/python3.10
-- Configuring incomplete, errors occurred!

$ cmake --version
cmake version 3.26.4

$ dpkg --get-selections | grep cudnn
libcudnn8			install
libcudnn8-dev             install

### Your system configuration
Operating system: Ubuntu 22.04

Hi,
any suggestions to fix the errors?

Thanks.

Saverio

**Comment by RMeli** [comment]
Sorry, I've got the wrong policy. The one giving an error for you is https://cmake.org/cmake/help/latest/policy/CMP0146.html, which has been introduced in CMake 2.27. You should use the same technique used in #282 to fix the issue.
