### ISSUE TITLE
Errors during installation procedure

### ISSUE THREAD

**Issue by whitelord1994** [gnina/gnina#287]
### Issue summary
During installation according to the tutorial from readme I've got multiple instances of following error:
/mnt/c/Users/user/openbabel/build/gnina/gninasrc/../Eigen/array:8:4: error: #error The Eigen/Array header does no longer exist in Eigen3. All that functionality has moved to Eigen/Core.
    8 |   #error The Eigen/Array header does no longer exist in Eigen3. All that functionality has moved to Eigen/Core.
      |    ^~~~~
All this finishes with:
make[2]: *** [gninasrc/CMakeFiles/gninalibobj.dir/build.make:467: gninasrc/CMakeFiles/gninalibobj.dir/lib/builtinscoring.cpp.o] Error 1
make[2]: *** [gninasrc/CMakeFiles/gninalibobj.dir/build.make:495: gninasrc/CMakeFiles/gninalibobj.dir/lib/cache_gpu.cpp.o] Error 1
make[2]: *** [gninasrc/CMakeFiles/gninalibobj.dir/build.make:481: gninasrc/CMakeFiles/gninalibobj.dir/lib/cache.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:966: gninasrc/CMakeFiles/gninalibobj.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
Should I install older version of Eigen then? Or the default tutorial is now working anymore?

### Steps to reproduce
make -j8 in /mnt/c/Users/user/openbabel/build/gnina/build

### Your system configuration
Operating system: WSL 2 on Windows 10
Compiler: gcc 13.2
CUDA version (if applicable): 12.4
CUDNN version (if applicable):
Python version: 3.12

**Comment by dkoes** [comment]
The expected version of Eigen is bundled with gnina.  There isn't enough context to fully understand what is happening, but my guess is you are on a case-insensitive file system and a `#include <array>` is incorrectly pulling in `Array` in the Eigen directory.  Try removing the line `include_directories(../Eigen)` from `gninasrc/CMakeLists.txt`.

**Comment by whitelord1994** [comment]
thanks for the prompt response, i'll try a bit later

**Comment by whitelord1994** [comment]
Well, it actually worked! With like hundreds of warnings like below, but gnina --help finally gives a list of arguments, hope it will actually dock something.

```
/mnt/c/Users/user/openbabel/build/gnina/gninasrc/lib/file.h:145:27: warning: ‘std::string boost::filesystem::basename(const path&)’ is deprecated: Use path::stem() instead [-Wdeprecated-declarations]
  145 |         ext = extension(basename(name));
      |                   ~~~~~~~~^~~~~~
/usr/include/boost/filesystem/convenience.hpp:35:1: note: declared here
   35 | inline std::string basename(const path& p)
      | ^~~~~~~~
/mnt/c/Users/user/openbabel/build/gnina/gninasrc/lib/file.h:145:18: warning: ‘std::string boost::filesystem::extension(const path&)’ is deprecated: Use path::extension() instead [-Wdeprecated-declarations]
  145 |         ext = extension(basename(name));
      |         ~~~~~~~~~^~~~~~~~~~~~~~~~
/usr/local/include/openbabel3/openbabel/math/vector3.h: In member function ‘bool OpenBabel::vector3::operator!=(const OpenBabel::vector3&) const’:
/usr/local/include/openbabel3/openbabel/math/vector3.h:281:21: warning: ‘bool OpenBabel::vector3::operator==(const OpenBabel::vector3&) const’ is deprecated: Use vector3::IsApprox() instead. [-Wdeprecated-declarations]
  281 |       return ! ( (*this) == other );
      |                     ^~~~~
/usr/local/include/openbabel3/openbabel/math/vector3.h:274:1: note: declared here
  274 |     bool operator== ( const vector3& ) const;
      | ^   ~~~~
/mnt/c/Users/user/openbabel/build/gnina/./Eigen/src/Core/Functors.h: At global scope:
/mnt/c/Users/user/openbabel/build/gnina/./Eigen/src/Core/Functors.h:984:29: warning: ‘template<class _Predicate> class std::unary_negate’ is deprecated [-Wdeprecated-declarations]
  984 | struct functor_traits<std::unary_negate<T> >
      |                             ^~~~~~~~~~~~
```

**Comment by whitelord1994** [comment]
yes, the docking works, probably the changes in the file (CMakeLists.txt) should be maked, or at least the info is added to readme.
but the covalent part seems very tricky, for now resulting in positive energies
Is there any tutorial on how to prepare ligand and protein (i actually want to bind one ligand to another that is left within the protein structure)? And should i use pdbqt files like smina, or just pdb file without water and energy-minimized ligand in sdf is enough?

**Comment by whitelord1994** [comment]
my bad, UFF optimization helps a lot

**Comment by dkoes** [comment]
I think UFF has issues with phosphate groups unless they are protonated a specific way (which may not be how openbabel likes to protonate them).
