### ISSUE TITLE
Error when covalent docking: Provided ligand file format not supported with covalent docking.

### ISSUE THREAD

**Issue by lovenicole** [gnina/gnina#289]
### Issue summary
Hello,

I attempted covalent docking using Gnina in a Google Colab CPU environment, but encountered the following error:

"Usage error: Provided ligand file format not supported with covalent docking."
I would appreciate any suggestions to resolve this issue. 

### Steps to reproduce
I can provide the receptor and ligand files for reference. 
[8x6r_A_1.zip](https://github.com/user-attachments/files/17842630/8x6r_A_1.zip)
[BRD-K00010385.zip](https://github.com/user-attachments/files/17842653/BRD-K00010385.zip)

Below is the command I used:

```
gnina -r /content/drive/MyDrive/SMILES/8x6r_A_1.pdbqt -l BRD-K00010385.pdbqt --center_x 66.082 --center_y -6.131 --center_z 95.682 --size_x 20 --size_y 20 --size_z 20 --covalent_rec_atom A:12:SG --covalent_lig_atom_pattern CCC --cnn crossdock_default2018 -o BRD-K00010385.sdf --seed 0
```

### Your system configuration
Operating system: Google colab

Compiler: CPU
CUDA version (if applicable):
CUDNN version (if applicable):
Python version: Python [3.10.13]

**Comment by lovenicole** [comment]
Hi [RMeli],

Thank you so much for your detailed explanation and helpful suggestion! I sincerely appreciate your guidance, as it resolved my issue perfectly. Apologies for the delayed response, but I wanted to express my gratitude for your time and assistance.

**Comment by RMeli** [comment]
I'm grad it helped!
