### ISSUE TITLE
Gnina 1.3 covalent docking doesn't return any output or error

### ISSUE THREAD

**Issue by nitzan-simchi** [gnina/gnina#290]
### Issue summary
Hello,
When trying to run Gnina 1.3 covalent docking on several different examples using the following command line I get neither the output sdf nor any error. When checking Gnina 1.1, the same command does work.

Would appreciate any suggestions or reference to a full example where Gnina covalent docking works so I can reproduce.

### Steps to reproduce
`
./gnina -r rec.pdb -l lig.pdb --autobox_ligand lig.pdb --covalent_rec_atom A:601:FE --covalent_lig_atom_pattern '[$(n1nccc1)]' -o output.sdf.gz
`
### Your system configuration
Compiler: CPU
CUDA version (if applicable):
CUDNN version (if applicable):
Python version: 3.12

**Comment by dkoes** [comment]
Can you prove your input files?
