### ISSUE TITLE
gninagrid  bad alloc

### ISSUE THREAD

**Issue by amrhamedp** [gnina/gnina#30]
root@8681699bdf8e:/src/play/set1/14# gninagrid -r rec.pdb -l ligand.mol2 -o a --separate
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

I installed gnina inside docker image 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
gcc version 5.4.0 20160609 
CUDA version (if applicable):V9.0.176

**Comment by dkoes** [comment]
Can you provide the input files?

**Comment by amrhamedp** [comment]
https://nofile.io/f/EDwws1WApwu/14.zip

**Comment by dkoes** [comment]
This is because you aren't providing --example_grid to set a coordinate system.  The newest version of the code actually provides an informative error message as to the problem.  I have pushed an updated to the docker container (thanks to @Jsunseri  for initial debugging).

**Comment by amrhamedp** [comment]
root@484a34e91a20:/src/play/set1/14# gninagrid -r rec.pdb -l ligand.mol2  -o amr
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)


It still give error without separate

**Comment by dkoes** [comment]
Are you using the updated version?

**Comment by amrhamedp** [comment]
docker pull dkoes/gnina
Using default tag: latest
latest: Pulling from dkoes/gnina
Digest: sha256:ea1db71f76d2827f896f8d3e7cb538779e48afac465399d3f51c27f215b65a0b
Status: Image is up to date for dkoes/gnina:latest

**Comment by dkoes** [comment]
Are you using nvidia-docker?  I could not reproduce the error until I switched to using vanilla docker (so a container without a video card).  It looks like, surprisingly, cudaMallocHost throws an error if there isn't a GPU available.

**Comment by amrhamedp** [comment]
U are great....I totally forget to use nvidia-docker although i was using it last week....
I created a debug version but failed to know the reason..
Thank you very much
