### ISSUE TITLE
'parse_error'

### ISSUE THREAD

**Issue by amrhamedp** [gnina/gnina#33]
root@059b24cea53d:/amr/set1/133# gninagrid -r rec.pdb -l docked.sdf -o trial
terminate called after throwing an instance of 'parse_error'
Aborted (core dumped)

This happens with around 80 receptors/ligands

System--->nvidia-docker
files:
https://nofile.io/f/d7EWQvEY3FQ/133.zip

**Comment by dkoes** [comment]
This is an issue with the package version of openbabel.  You can (probably) work around it by converting to a pdbqt with babel and then using that:
```
root@cbc63b018d26:~# babel rec.pdb rec.pdbqt -xr
1 molecule converted
177 audit log messages 
root@cbc63b018d26:~# gninagrid -r rec.pdbqt -l docked.sdf -o test
root@cbc63b018d26:~# 
```
Or you can upgrade the version of openbabel.
