### ISSUE TITLE
Using gninatypes with gninagrid

### ISSUE THREAD

**Issue by amrhamedp** [gnina/gnina#35]
Hello,
Can you please enable using gninatypes as a file type in gninagrid?

**Comment by dkoes** [comment]
Eh, the way the code is written it needs an actual molecular data file.  Since you can't generate a gninatypes file without a molecular data file, I don't see the point.

**Comment by amrhamedp** [comment]
In affinity model using general set, you have some ligands denoted as following:
1n5r_ligand3_6.gninatypes
I am not sure what is the source of that gninatype (it is different from 1n5r_ligand_6.gninatypes). It is also supplied as an input in the types file you used in training.

**Comment by amrhamedp** [comment]
I am aware of these files. I am talking about specific case here:
diff 1n5r_ligand3_0.gninatypes 1n5r_ligand_0.gninatypes 
Binary files 1n5r_ligand3_0.gninatypes and 1n5r_ligand_0.gninatypes differ

What is the difference in the source of these particular two ligands.

**Comment by dkoes** [comment]
1n5r_ligand_0.gninatypes is the first pose from 1n5r_docked.sdf.gz
1n5r_ligand3_0.gninatypes is the first pose from 1n5r_docked_min_cnn3.sdf.gz

The gninatypes files are simple the x,y,z and atom types.  You can use `od` to see the contents.
