### ISSUE TITLE
Error while running train.py

### ISSUE THREAD

**Issue by schrodinger83** [gnina/gnina#36]
Hello I tried to install gnina but I always get this error

I already added this in bashrc and sourced it
export PYTHONPATH=/usr/local/python:$PYTHONPATH

./scripts/train.py -h
Traceback (most recent call last):
  File "./scripts/train.py", line 11, in <module>
    import caffe
  File "/usr/local/python/caffe/__init__.py", line 2, in <module>
    from ._caffe import init_log, log, set_mode_cpu, set_mode_gpu, set_device, Layer, get_solver, layer_type_list, set_random_seed, solver_count, set_solver_count, solver_rank, set_solver_rank, set_multiprocess, Layer, get_solver, has_nccl, device_synchronize
ImportError: cannot import name has_nccl

**Comment by dkoes** [comment]
That should be defined in `/usr/local/python/caffe/_caffe.so`
Are you sure you linking with the gnina-specific version of caffe and not some vanilla distribution?  Check the timestamp of _caffe.so to make sure it it was installed when you installed gnina.
