### ISSUE TITLE
How to check the ligand source file from respective gninatypes?

### ISSUE THREAD

**Issue by edervishaj** [gnina/gnina#37]
Hello,

We are trying to compare the scoring of gnina with Autodock Vina and we are working specifically with https://github.com/gnina/models/tree/master/data/csar/alltest0.types file. We need to retrieve the ligand source files because we already think we can find the receptor from the CSAR dataset.

We tried to check the contents with `od` and it is showing numbers whose meaning we do not understand like:
`0000000    164163  040637  131463  040756  146144  040570  000003  000000
0000020    041776  040641  103045  040745  025553  040603  000014  000000
0000040    130620  040632  135052  040741  121556  040603  000001  000000`

We read from another issue that gninatypes should include x, y, z and the atom but from this content we are a bit confused which is which.

Thanks in advance!

**Comment by dkoes** [comment]
Use `od -f` to view the floating point x,y,z coordinates.  The gninatypes files are preformated inputs for efficient training.  If you are re-training your own models, please be careful to clearly indicate your training protocol.  I would not recommend the CSAR dataset.

If you want to compare to our published (and some unpublished) models you can get them from https://github.com/gnina/models

**Comment by NindoK** [comment]
Hello Dkoes,

I'm trying too and I've encountered kind of the same problem. I'm having a problem to understand the ligand from these data. From the atom how can I get to the ligand name?

Thanks in advance!

**Comment by dkoes** [comment]
I'm sorry, I don't understand what you are asking or trying to do?

**Comment by NindoK** [comment]
I'm trying to compare gnina results with those of autodock vina. To compare the results i need to know both the receptor and ligand that we are using. Since the .gninatypes files have only x,y,z and atom (?), i would like to know every ligand that gnina is using when using as input a `docked_n.gninatypes` file.

I hope i have been clear and thanks a lot for helping!

**Comment by dkoes** [comment]
As I explained above, the gninatypes files are for training.  Are you training your own model?  I'm not sure why you would do this if you are only concerned with comparing.

If you are happy comparing to the default model, you run gnina with --cnn_scoring on.  If you want to use one of the other pretrained models mentioned above, you specify them with --cnn_model and --cnn_weights.

**Comment by NindoK** [comment]
Ok then maybe i understood wrong. 
What i'm trying to do is: to compare the outputs of gnina and autodock vina, using the same test file as input.

Thanks!

**Comment by edervishaj** [comment]
Hey dkoes, thank you for your work!

We are trying to compare gnina scoring with Autodock Vina scoring. While we can use the predict.py for the test datasets of CSAR, we would like to run Autodock Vina on exactly the same .gninatypes test files. But we are stuck on using the same proteins and ligans in Autodock Vina since we need the ligands' names.

Thank you again!

**Comment by dkoes** [comment]
I'm not sure what good it will do to write this for the third time, but I'll try using a bold font. **The gninatypes files are for training, not evaluation.**  Give gnina the same molecular input you are giving vina as described above.

**Comment by NindoK** [comment]
Ok perfect. I think we misunderstood completely some files.

Sorry for bothering you and thanks a lot for the help!
