### ISSUE TITLE
Gnina build fails 

### ISSUE THREAD

**Issue by ConorFWild** [gnina/gnina#38]
Excuse me, I was trying to install Gnina within a singularity container (nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04) on a HPC and experienced the following errors:

[ 43%] Built target classification
[ 43%] Built target convert_mnist_siamese_data
[ 43%] Built target pycaffe
[ 43%] Building CXX object gninasrc/CMakeFiles/gninalib.dir/lib/cnn_scorer.cpp.o
In file included from /jmain01/home/JAD001/mxs10/ccw15-mxs10/gnina/gnina/gninasrc/lib/cnn_scorer.cpp:8:0:
/jmain01/home/JAD001/mxs10/ccw15-mxs10/gnina/gnina/gninasrc/lib/cnn_scorer.h:32:23: error: 'recursive_mutex' is not a member of 'boost'
     caffe::shared_ptr<boost::recursive_mutex> mtx; //todo, enable parallel scoring
                       ^
/jmain01/home/JAD001/mxs10/ccw15-mxs10/gnina/gnina/gninasrc/lib/cnn_scorer.h:32:23: error: 'recursive_mutex' is not a member of 'boost'
/jmain01/home/JAD001/mxs10/ccw15-mxs10/gnina/gnina/gninasrc/lib/cnn_scorer.h:32:45: error: template argument 1 is invalid
     caffe::shared_ptr<boost::recursive_mutex> mtx; //todo, enable parallel scoring
                                             ^
/jmain01/home/JAD001/mxs10/ccw15-mxs10/gnina/gnina/gninasrc/lib/cnn_scorer.h: In constructor 'CNNScorer::CNNScorer()':
/jmain01/home/JAD001/mxs10/ccw15-mxs10/gnina/gnina/gninasrc/lib/cnn_scorer.h:42:39: error: 'recursive_mutex' in namespace 'boost' does not name a type
         : mgrid(NULL), mtx(new boost::recursive_mutex), current_center(NAN,NAN,NAN) {
                                       ^
/jmain01/home/JAD001/mxs10/ccw15-mxs10/gnina/gnina/gninasrc/lib/cnn_scorer.cpp: In constructor 'CNNScorer::CNNScorer(const cnn_options&)':
/jmain01/home/JAD001/mxs10/ccw15-mxs10/gnina/gnina/gninasrc/lib/cnn_scorer.cpp:27:50: error: 'recursive_mutex' in namespace 'boost' does not name a type
     : mgrid(NULL), cnnopts(opts), mtx(new boost::recursive_mutex), current_center(NAN,NAN,NAN) {
                                                  ^
/jmain01/home/JAD001/mxs10/ccw15-mxs10/gnina/gnina/gninasrc/lib/cnn_scorer.cpp: In member function 'void CNNScorer::lrp(const model&, const string&, bool)':
/jmain01/home/JAD001/mxs10/ccw15-mxs10/gnina/gnina/gninasrc/lib/cnn_scorer.cpp:159:21: error: 'recursive_mutex' is not a member of 'boost'
   boost::lock_guard<boost::recursive_mutex> guard(*mtx);
                     ^
/jmain01/home/JAD001/mxs10/ccw15-mxs10/gnina/gnina/gninasrc/lib/cnn_scorer.cpp:159:21: error: 'recursive_mutex' is not a member of 'boost'
/jmain01/home/JAD001/mxs10/ccw15-mxs10/gnina/gnina/gninasrc/lib/cnn_scorer.cpp:159:43: error: template argument 1 is invalid
   boost::lock_guard<boost::recursive_mutex> guard(*mtx);
                                           ^
/jmain01/home/JAD001/mxs10/ccw15-mxs10/gnina/gnina/gninasrc/lib/cnn_scorer.cpp:159:52: error: invalid type argument of unary '*' (have 'int')
   boost::lock_guard<boost::recursive_mutex> guard(*mtx);
                                                    ^
/jmain01/home/JAD001/mxs10/ccw15-mxs10/gnina/gnina/gninasrc/lib/cnn_scorer.cpp: In member function 'void CNNScorer::gradient_setup(const model&, const string&, const string&, const string&)':
/jmain01/home/JAD001/mxs10/ccw15-mxs10/gnina/gnina/gninasrc/lib/cnn_scorer.cpp:184:21: error: 'recursive_mutex' is not a member of 'boost'
   boost::lock_guard<boost::recursive_mutex> guard(*mtx);
                     ^
/jmain01/home/JAD001/mxs10/ccw15-mxs10/gnina/gnina/gninasrc/lib/cnn_scorer.cpp:184:21: error: 'recursive_mutex' is not a member of 'boost'
/jmain01/home/JAD001/mxs10/ccw15-mxs10/gnina/gnina/gninasrc/lib/cnn_scorer.cpp:184:43: error: template argument 1 is invalid
   boost::lock_guard<boost::recursive_mutex> guard(*mtx);
                                           ^
/jmain01/home/JAD001/mxs10/ccw15-mxs10/gnina/gnina/gninasrc/lib/cnn_scorer.cpp:184:52: error: invalid type argument of unary '*' (have 'int')
   boost::lock_guard<boost::recursive_mutex> guard(*mtx);
                                                    ^
/jmain01/home/JAD001/mxs10/ccw15-mxs10/gnina/gnina/gninasrc/lib/cnn_scorer.cpp: In member function 'float CNNScorer::score(model&, bool, float&, float&)':
/jmain01/home/JAD001/mxs10/ccw15-mxs10/gnina/gnina/gninasrc/lib/cnn_scorer.cpp:299:21: error: 'recursive_mutex' is not a member of 'boost'
   boost::lock_guard<boost::recursive_mutex> guard(*mtx);
                     ^
/jmain01/home/JAD001/mxs10/ccw15-mxs10/gnina/gnina/gninasrc/lib/cnn_scorer.cpp:299:21: error: 'recursive_mutex' is not a member of 'boost'
/jmain01/home/JAD001/mxs10/ccw15-mxs10/gnina/gnina/gninasrc/lib/cnn_scorer.cpp:299:43: error: template argument 1 is invalid
   boost::lock_guard<boost::recursive_mutex> guard(*mtx);
                                           ^
/jmain01/home/JAD001/mxs10/ccw15-mxs10/gnina/gnina/gninasrc/lib/cnn_scorer.cpp:299:52: error: invalid type argument of unary '*' (have 'int')
   boost::lock_guard<boost::recursive_mutex> guard(*mtx);
                                                    ^
gninasrc/CMakeFiles/gninalib.dir/build.make:13672: recipe for target 'gninasrc/CMakeFiles/gninalib.dir/lib/cnn_scorer.cpp.o' failed
make[2]: *** [gninasrc/CMakeFiles/gninalib.dir/lib/cnn_scorer.cpp.o] Error 1
CMakeFiles/Makefile2:1180: recipe for target 'gninasrc/CMakeFiles/gninalib.dir/all' failed
make[1]: *** [gninasrc/CMakeFiles/gninalib.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

The Initial output was:

-- CUDA detected: 9.0
-- Found cuDNN: ver. 7.2.1 found (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Added CUDA NVCC flags for: sm_60
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   thread
--   filesystem
--   iostreams
--   timer
--   chrono
--   date_time
--   atomic
--   regex
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Found PROTOBUF Compiler: /usr/bin/protoc
-- CUDA detected: 9.0
-- Found cuDNN: ver. 7.2.1 found (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Added CUDA NVCC flags for: sm_60
-- Found Atlas (include: /usr/include library: /usr/lib/libatlas.so lapack: /usr/lib/liblapack.so
-- NumPy ver. 1.11.0 found (include: /usr/lib/python2.7/dist-packages/numpy/core/include)
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   python
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)

-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version           :   1.0.0
--   Git               :   df65209
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -Wno-deprecated-declarations -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -Wno-deprecated-declarations -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release

--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   ON
--   CPU_ONLY          :   OFF
--   USE_OPENCV        :   0
--   USE_LEVELDB       :   0
--   USE_LMDB          :   0
--   USE_NCCL          :   OFF
--   ALLOW_LMDB_NOLOCK :   OFF

-- Dependencies:
--   BLAS              :   Yes (Atlas)
--   Boost             :   Yes (ver. 1.58)
--   glog              :   Yes
--   gflags            :   Yes
--   OpenBabel         :   Yes
--   protobuf          :   Yes (ver. 2.6.1)
--   CUDA              :   Yes (ver. 9.0)

-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_60
--   cuDNN             :   Yes (ver. 7.2.1)

-- Python:

--   Interpreter       :   /usr/bin/python2.7 (ver. 2.7.12)
--   Libraries         :   /usr/lib/x86_64-linux-gnu/libpython2.7.so (ver 2.7.12)
--   NumPy             :   /usr/lib/python2.7/dist-packages/numpy/core/include (ver 1.11.0)
-- Documentaion:
--   Doxygen           :   No
--   config_file       :

-- Install:

--   Install path      :   /usr/local
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   program_options
--   system
--   iostreams
--   timer
--   thread
--   serialization
--   filesystem
--   date_time
--   regex
--   unit_test_framework
--   chrono
--   atomic
-- Found RDKit libraries at /usr/lib
-- Found RDKit library files at /usr/lib/libFileParsers.so;/usr/lib/libSmilesParse.so;/usr/lib/libGraphMol.so;/usr/lib/libRDGeometryLib.so;/usr/lib/libRDGeneral.so;/usr/lib/libSubgraphs.so;/usr/lib/libDataStructs.so;/usr/lib/libDepictor.so
-- Configuring done
-- Generating done
-- Build files have been written to: /jmain01/home/JAD001/mxs10/ccw15-mxs10/gnina/gnina/build

Any ideas on why it might not be recognising the recursive_mutex?

This issue does not seem to happen with a version we downloaded a few months ago (in particular the build: Feb 14, 2018, "Merge branch 'master'" ). All the dependencies suggested in the read me were installed as per instructions for Ubuntu 16.04.

Thanks, Conor

**Comment by dkoes** [comment]
I just switched to using recursive_mutex instead of a regular mutex.  No idea why it would break your build.  If you haven't already, try building from a clean checkout to make sure the problem isn't some stale object files.
You can also try adding `#include "boost/thread.hpp"` to cnn_scorer.h

**Comment by ConorFWild** [comment]
Hey, this seems to have fixed the issue on our side. Installation works as expected now.

Thanks, Conor
