### ISSUE TITLE
ubuntu16/anaconda

### ISSUE THREAD

**Issue by schrodinger83** [gnina/gnina#41]
### Issue summary
I can't install gnina on top of anaconda.I can successfully using normal python but when shifting to anaconda , i encounter so many errors regarding protobuff and other google libs. I am not sure how to install it under anaconda environment and what are the correct and compatible libs to be installed via conda

### Your system configuration
Operating system: ubuntu 16
Compiler:
CUDA version (if applicable):9.2
CUDNN version (if applicable):
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):python anaconda 2.7

**Comment by dkoes** [comment]
Is "don't use anaconda" not an acceptable workaround?
