### ISSUE TITLE
gninavis generated pdbqt files

### ISSUE THREAD

**Issue by amrhamedp** [gnina/gnina#43]
### Issue summary
gninavis will cause the ligand to be deformed when it generats pdbqt file. Most likely this has to do with openbabel but i am not sure how to solve it 

### Your system configuration
Operating system: Redhat 7
Compiler:gcc
CUDA version (if applicable): 9.2
CUDNN version (if applicable):
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):2.7

Note:This installation is done on redhat directly and not via docker

**Comment by dkoes** [comment]
Example?

**Comment by dkoes** [comment]
Closing due to lack of response.
