### ISSUE TITLE
Access to trained gnina models

### ISSUE THREAD

**Issue by gregfriedland** [gnina/gnina#50]
### Issue summary

Sorry if this is the wrong forum for this, I wasn't sure where to post it.

Are there already trained models (e.g. the ones referenced in http://bits.csb.pitt.edu/files/gnina2018_poster.pdf) checked into git or available elsewhere I could use for exploring gnina without training it myself?

Thanks.

**Comment by Jsunseri** [comment]
There are multiple repositories related to gnina, ranging from the program source to trained models and helper scripts. The parent URL for all of them is https://github.com/gnina , and the models repo is https://github.com/gnina/models .

**Comment by dkoes** [comment]
There are some models here:
https://github.com/gnina/models
However, trained models are conspicuously absent from the acs2018 directory.  I don't think we ever got around to training full models (i.e. models trained on the whole set as opposed to a crosss-validation split). @francoep is furiously working on training these models for cross-docking and will push the trained models when he's done.

The default2017 is the default model that is baked into gnina.  Would you like the other models trained on cross-validation splits, or would prefer to wait for fully trained models?

**Comment by gregfriedland** [comment]
Thanks, I hadn't seen that repo. Yes, I'd prefer to wait for the fully trained models when those become available.

**Comment by dkoes** [comment]
Okay, I'll assume the available default2017 model is fine for now and close the issue.

**Comment by gregfriedland** [comment]
Thanks. I'll track https://github.com/gnina/models for updates.
