### ISSUE TITLE
How BVLC version caffe can solve 3D model

### ISSUE THREAD

**Issue by mystao** [gnina/gnina#52]
hello ,
there is a question about BLVC version caffe ,it's just can process 2D images,  was caffe conv_layer.cpp  reconstructed or other method  used to processing ligand and protein space poses?    I just can coding python ,so Look forward to your reply.

**Comment by dkoes** [comment]
We have our own custom version of caffe that implemented 3d convolutions based off of this pull request: https://github.com/BVLC/caffe/pull/2049
