### ISSUE TITLE
An make error occured

### ISSUE THREAD

**Issue by mystao** [gnina/gnina#53]
### Issue summary

![image](https://user-images.githubusercontent.com/29221718/56969532-ed7aea00-6b97-11e9-8c80-0d2e0aa4469c.png)

../lib/libcaffe.so.1.0.0：对‘boost::filesystem::path::operator/=(boost::filesystem::path const&)’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::python::converter::detail::arg_to_python_base::arg_to_python_base(void const volatile*, boost::python::converter::registration const&)’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::iostreams::zlib::sync_flush’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::iostreams::detail::zlib_base::xinflate(int)’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::iostreams::zlib::deflated’未定义的引用
collect2: error: ld returned 1 exit status
caffe/tools/CMakeFiles/extract_features.dir/build.make:121: recipe for target 'caffe/tools/extract_features' failed
make[2]: *** [caffe/tools/extract_features] Error 1
CMakeFiles/Makefile2:497: recipe for target 'caffe/tools/CMakeFiles/extract_features.dir/all' failed
make[1]: *** [caffe/tools/CMakeFiles/extract_features.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

### Your system configuration
Operating system:ubuntu 16.04.1
Compiler:  gcc 5.4.0
CUDA version (if applicable):10.1
CUDNN version (if applicable): 7.3.1
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):

**Comment by dkoes** [comment]
Please provide the full error message.  What version of boost?

**Comment by mystao** [comment]
Thanks for your quickly reply, boost version is 1.5.4 

[  1%] Built target caffeproto
[ 39%] Built target caffe
[ 39%] Linking CXX executable extract_features
../lib/libcaffe.so.1.0.0：对‘boost::thread::start_thread_noexcept()’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::python::throw_error_already_set()’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::python::import(boost::python::str)’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::thread::detach()’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::detail::thread_data_base::~thread_data_base()’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::iostreams::detail::gzip_footer::reset()’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::iostreams::detail::gzip_header::process(char)’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::filesystem::path::replace_extension(boost::filesystem::path const&)’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::iostreams::detail::gzip_header::reset()’未定义的引用
../lib/libcaffe.so.1.0.0：对‘typeinfo for boost::python::error_already_set’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::python::error_already_set::~error_already_set()’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::thread::native_handle()’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::iostreams::detail::gzip_footer::process(char)’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::iostreams::detail::zlib_base::before(char const*&, char const*, char*&, char*)’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::iostreams::zlib_error::check(int)’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::python::detail::str_base::str_base(char const*)’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::iostreams::zlib::default_compression’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::thread::interrupt()’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::this_thread::interruption_point()’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::python::api::getattr(boost::python::api::object const&, char const*)’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::iostreams::detail::zlib_base::do_init(boost::iostreams::zlib_params const&, bool, void* (*)(void*, unsigned int, unsigned int), void (*)(void*, void*), void*)’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::python::converter::rvalue_from_python_stage1(_object*, boost::python::converter::registration const&)’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::iostreams::zlib::stream_end’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::thread::interruption_requested() const’未定义的引用
../lib/libcaffe.so.1.0.0：对‘vtable for boost::python::error_already_set’未定义的引用
../lib/libcaffe.so.1.0.0：对‘vtable for boost::detail::thread_data_base’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::iostreams::detail::zlib_base::zlib_base()’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::detail::get_current_thread_data()’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::thread::joinable() const’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::iostreams::detail::zlib_base::~zlib_base()’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::python::converter::registry::lookup(boost::python::type_info)’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::iostreams::detail::zlib_base::after(char const*&, char*&, bool)’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::iostreams::zlib::default_strategy’未定义的引用
../lib/libcaffe.so.1.0.0：对‘typeinfo for boost::detail::thread_data_base’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::python::converter::registry::lookup_shared_ptr(boost::python::type_info)’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::detail::get_tss_data(void const*)’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::iostreams::zlib::okay’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::python::converter::rvalue_from_python_stage2(_object*, boost::python::converter::rvalue_from_python_stage1_data&, boost::python::converter::registration const&)’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::thread::join_noexcept()’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::filesystem::path::stem() const’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::detail::set_tss_data(void const*, void (*)(void (*)(void*), void*), void (*)(void*), void*, bool)’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::iostreams::detail::zlib_base::reset(bool, bool)’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::filesystem::path::operator/=(boost::filesystem::path const&)’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::python::converter::detail::arg_to_python_base::arg_to_python_base(void const volatile*, boost::python::converter::registration const&)’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::iostreams::zlib::sync_flush’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::iostreams::detail::zlib_base::xinflate(int)’未定义的引用
../lib/libcaffe.so.1.0.0：对‘boost::iostreams::zlib::deflated’未定义的引用
collect2: error: ld returned 1 exit status
caffe/tools/CMakeFiles/extract_features.dir/build.make:121: recipe for target 'caffe/tools/extract_features' failed
make[2]: *** [caffe/tools/extract_features] Error 1
CMakeFiles/Makefile2:497: recipe for target 'caffe/tools/CMakeFiles/extract_features.dir/all' failed
make[1]: *** [caffe/tools/CMakeFiles/extract_features.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by dkoes** [comment]
Do you mean 1.54?  The default boost version in Ubuntu 16.04 should be 1.58.  Can you try that?

**Comment by mystao** [comment]
thanks a lot ,it's  boost version problem ,now it's work  with boost 1.58
