### ISSUE TITLE
An error happened.

### ISSUE THREAD

**Issue by mystao** [gnina/gnina#54]
Hi,
I want test gnina cnn scroing result , "Could not open ligmap.old" error hanppend, but I'm sure this file in path "../soft/models/refmodel3/ligmap.old" ,should I set  more parameter  to do this test ?thanks ,and I run the command as follows : 

gnina --cpu 4 --gpu --receptor protein.mol2 --ligand mols-1.sdf --cnn_model /workspace/soft/models/refmodel3/refmodel3.model --cnn_weights /workspace/soft/models/refmodel3/weights/pdbbind_cnnmin1_100000.caffemodel --cnn_center_x 31.944 --cnn_center_y -13.308 --cnn_center_z 4.06928  --cnn_scoring  --out gnina_cnn.sdf --num_modes 4 --energy_range 99 --exhaustiveness 4 --autobox_ligand bindingsite.xyz --autobox_add 2 --seed 42

![image](https://user-images.githubusercontent.com/29221718/57191540-8ecbbc80-6f59-11e9-8574-4152cecb225c.png)

**Comment by dkoes** [comment]
That particular model uses a different collection of atom types, specified in the ligmap file, than the default.  `ligmap.old` is available here: https://github.com/gnina/models/blob/master/refmodel3/ligmap.old
Put it in the current directory or change the model file to specify an absolute path.
