### ISSUE TITLE
why gnina cnn_scoring take so long time ?

### ISSUE THREAD

**Issue by mystao** [gnina/gnina#55]
Hi,
I do  a gnina cnn_scoring test , only one ligand molecular take 15 hours  and  gpu with high utilization rate when using cnn_scoring,I can't understand Why does gnina need such a large amount of calculation only one ligand? how  can I get dock poses quickly ? and I using one gtx 1080 gpu ,command as follows:
gnina --cpu 4 --gpu --receptor protein.mol2 --ligand mols-1.sdf  --cnn_model ../soft/models/refmodel3/refmodel3.model --cnn_weights ../soft/models/refmodel3/weights/pdbbind_cnnmin1_100000.caffemodel --cnn_center_x 31.944 --cnn_center_y -13.308 --cnn_center_z 4.06928 --cnn_scoring  --out gnina_cnn.sdf --num_modes 4 --energy_range 99 --exhaustiveness 4 --autobox_ligand bindingsite.xyz --autobox_add 2 --seed 42

thanks.

**Comment by dkoes** [comment]
You are doing a full docking which involves thousands of scoring evaluations and isn't recommended (the CNN hasn't been trained for this task).  You are better off docking with the default Vina scoring function and then scoring (--score_only) and/or refining (--minimize) with --cnn_scoring.  You can enable CNN refinement during docking with --cnn_refinement
