### ISSUE TITLE
Problem with latest development version of OpenBabel

### ISSUE THREAD

**Issue by RMeli** [gnina/gnina#58]
### Issue summary

The latest version of OpenBabel is incompatible with `PDBQTUtilities.cpp`; `OBAtom` member functions changed name (see OpenBabel [PR #1975](https://github.com/openbabel/openbabel/pull/1975)). This leads to the following error:
```
$HOME/Documents/git/gnina/gninasrc/lib/PDBQTUtilities.cpp: In function 'bool IsRotBond_PDBQT(OpenBabel::OBBond*, unsigned int)':
/biggin/b195/lina3015/Documents/git/gnina/gninasrc/lib/PDBQTUtilities.cpp:123:36: error: 'class OpenBabel::OBAtom' has no member named 'GetHvyValence'
   if (((the_bond->GetBeginAtom())->GetHvyValence() == 1)
                                    ^
$HOME/Documents/git/gnina/gninasrc/lib/PDBQTUtilities.cpp:124:37: error: 'class OpenBabel::OBAtom' has no member named 'GetHvyValence'
       || ((the_bond->GetEndAtom())->GetHvyValence() == 1)) {
                                     ^
```

### Steps to reproduce

Install the latest version of OpenBabel (with a CMake fix, see [PR 1988](https://github.com/openbabel/openbabel/pull/1988)):
```
apt purge --auto-remove libopenbabel-dev
git clone https://github.com/RMeli/openbabel.git
cd openbabel && git checkout fix/cmake
cd .. && mkdir obuild && cd obuild
cmake ../openbabel -DWITH_JSON:BOOLEAN=FALSE
make
make -j
make install
```
then compile `gnina`.

### Steps to Fix and Discussion

This is quick to fix by changing `GetHvyValence()` to `GetHvyDegree()` (I already have a PR ready), but will break for people using older development versions of the library. However, a development version of OpenBabel is needed (since the latest version 2.4.1 is missing `elements.h`, which appeared later according to [Issue #1941](https://github.com/openbabel/openbabel/issues/1941)) and chances are new users will just pull the latest version and incur in this problem.

### Your system configuration
Operating system: Ubuntu 16.04
Compiler: GNU 5.4.0
CUDA version (if applicable): 9.0
CUDNN version (if applicable): 7

**Comment by dkoes** [comment]
Sorry, I hadn't gotten around to pushing this fix.  Feel free to submit pull requests for things like this.
