### ISSUE TITLE
where to place the gnina/scripts 

### ISSUE THREAD

**Issue by aaronlyt** [gnina/gnina#66]
I place gnina/scripts  outside of the directory of gnina/(at the same directory level)，I got the ModuleNotFoundError: No module named 'caffe'), is the place i placed wrong?

**Comment by dkoes** [comment]
No, you don't have the caffe python library in your PYTHONPATH.

**Comment by aaronlyt** [comment]
Yes, I have not install it(as i saw caffe in the gnina), then which vesion it need?

**Comment by dkoes** [comment]
You need to build and install gnina.  Only our custom version of caffe will work.  Alternatively, depending what you are doing, you can build and install libmolgrid.

**Comment by aaronlyt** [comment]
i had build and install gnina

**Comment by dkoes** [comment]
As stated in the scripts README, you need to set your PYTHONPATH to include caffe python modules
`export PYTHONPATH=/usr/local/python:$PYTHONPATH`

**Comment by aaronlyt** [comment]
Thans for response, sorry for make stupid actions.
