### ISSUE TITLE
libmolgrid::CoordinateSet’ has no member named ‘coord error

### ISSUE THREAD

**Issue by aaronlyt** [gnina/gnina#67]
## infomation
open bable from : https://github.com/openbabel/openbabel.git

from github not from libopenbabel-dev because it have some error when make gnina
### error info
gnina_repos/gnina/caffe/src/caffe/layers/molgrid_data_layer.cpp: In member function ‘double caffe::MolGridDataLayer<Dtype>::mol_info::ligandRadius() const’:
/home/lyt/workspace/molecular_gen/gnina_repos/gnina/caffe/src/caffe/layers/molgrid_data_layer.cpp:43:28: error: ‘const struct libmolgrid::CoordinateSet’ has no member named ‘coord’; did you mean ‘coords’?
     vec pos(orig_lig_atoms.coord[i][0],orig_lig_atoms.coord[i][1],orig_lig_atoms.coord[i][2]);
                            ^~~~~
                            coords

how to fix this? Thank you

**Comment by dkoes** [comment]
your libmolgrid and gnina source code aren't both up to date.  If you first checked out gnina, it automatically cloned the libmolgrid repository.  If you want to build libmolgrid separately, your life might be simpler if you built gnina refering to your standalone libmolgrid installation.

**Comment by aaronlyt** [comment]
Then i re-clone the gnina, and install as the instruction, get another error:
molecular_gen/gnina/gnina/build/libmolgrid-prefix/src/libmolgrid/include/libmolgrid/atom_typer.h:13:10: fatal error: openbabel/elements.h: 没有那个文件或目录
 #include <openbabel/elements.h>
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by dkoes** [comment]
You need the latest (master branch) version of openbabel to build libmolgrid

**Comment by aaronlyt** [comment]
After I install openbabel from re-clone the openbabel, still that problem
molecular_gen/gnina/gnina/build/libmolgrid-prefix/src/libmolgrid/include/libmolgrid/coordinateset.h:14:10: fatal error: openbabel/mol.h: 没有那个文件或目录
 #include <openbabel/mol.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by dkoes** [comment]
if it can’t find the openbabel headers you need to fix the configuration so it knows where they are

**Comment by aaronlyt** [comment]
Thanks the problem solve, but what about the problem: /usr/include/c++/7/bits/locale_classes.h:333:37: error: ‘_GLIBCXX_NUM_CATEGORIES’ was not declared in this scope
     enum { _S_categories_size = 6 + _GLIBCXX_NUM_CATEGORIES };

**Comment by dkoes** [comment]
No idea.  I am building on Ubuntu 18.04 with the default toolchain without problems.

**Comment by aaronlyt** [comment]
Ok, still thanks very much, is it the problem of gcc?

**Comment by dkoes** [comment]
Or the associated libraries.  I have not seen this error and it doesn't show up when I build in a default ubuntu docker container.  If you can explain how to reproduce it starting from vanilla ubuntu, I can look into it.

**Comment by aaronlyt** [comment]
Ok, I will try again

**Comment by aaronlyt** [comment]
I re-install correctly, however,  when I import cafffe, i got error:
ImportError: /usr/local/python/caffe/_caffe.so: undefined symbol: _ZN5caffe5LayerIfE18Backward_relevanceERKSt6vectorIPNS_4BlobIfEESaIS5_EERKS2_IbSaIbEES9_

as i search from the web, it is the python version problem(my python vesion is python3.6),
then i changed the PYTHON_LIBRARIES ?= boost_python-py36 python3.6m in file caffe/Makefile, 

however it did not work, Do you  have any advices, Thanks

**Comment by dkoes** [comment]
It looks like there is a mismatch between headers and libraries somewhere.  Do you have multiple versions of caffe installed?
