### ISSUE TITLE
molgridlayer top data structure questions 

### ISSUE THREAD

**Issue by aaronlyt** [gnina/gnina#68]
### Issue summary

Two implementation in molgrid_data_layer.cpp confused me, will you give me some hint, Thans!

#### void MolGridDataLayer<Dtype>::forward

**where do you have assign the values of the top[0]??**

https://github.com/gnina/gnina/blob/master/caffe/src/caffe/layers/molgrid_data_layer.cpp
code line number: 787
```
  Dtype *top_data = NULL;
  if(gpu)
    top_data = top[0]->mutable_gpu_data();
  else
    top_data = top[0]->mutable_cpu_data();
```

#### MolGridDataLayer<Dtype>::set_grid_minfo function
**As i understand, recgrid and liggrid are the true input to the next layer, however recgrid and liggrid are local variable, how do they pass on to the next layer**

code line number: 720
```
  if (gpu)
  {
    Grid<Dtype, 4, true> recgrid(data, numReceptorTypes, dim, dim, dim);
    gmaker.forward(minfo.grid_center, rec_atoms, recgrid);
    if(!ignore_ligand) {
      // Grid, first the data, after the dimension
      Grid<Dtype, 4, true> liggrid(data+numgridpoints*numReceptorTypes, \
        numchannels-numReceptorTypes, dim, dim, dim);
      gmaker.forward(minfo.grid_center, lig_atoms, liggrid);
    }
  }
```

**Comment by dkoes** [comment]
liggrid and recgrid are views into the underlying memory (data).  Running forward with them sets this memory.

**Comment by aaronlyt** [comment]
Sorry, I still can not understand, will you point clearly, also what about the first questions?

**Comment by dkoes** [comment]
A caffe layer takes as input the bottom layer and provides as output the top layer.  A data layer, like the molgridlayer, has no bottom.  The forward pass is setting the top values.  That is the point of this code.  To write values into the memory pointed to by top.  Which is the same memory pointed to by data. Which is the same memory pointed to be recgrid and liggrid.

**Comment by aaronlyt** [comment]
Thanks for your response, i see this, will you show me the code, which part of the code make the effect "write values into the memory pointed to by top. Which is the same memory pointed to by data. Which is the same memory pointed to be recgrid and liggrid."

**Comment by dkoes** [comment]
gmaker.forward

**Comment by aaronlyt** [comment]
I just see it set Grid<Dtype, 4, false>& out structure, however, it is a local variable, i still can not see how does it related with the top[0] data

**Comment by dkoes** [comment]
Perhaps stepping through the code in the debugger would be more informative.  I don't know how to better answer your question than I already have.  There is no `out` in the code snippet you provided, but if there was, it would be pointing to the same memory as everything else.  Having a local copy of a pointer to change what memory it is pointing to.

**Comment by aaronlyt** [comment]
er,em. i see one copy data layer code from stackoverflow, it is clear for me
```
import sys, os
sys.path.insert(0, os.environ['CAFFE_ROOT']+'/python')
import caffe
class myInputLayer(caffe.Layer):
  def setup(self,bottom,top):
    # read parameters from `self.param_str`
    ...
  def reshape(self,bottom,top):
    # no "bottom"s for input layer
    if len(bottom)>0:
      raise Exception('cannot have bottoms for input layer')
    # make sure you have the right number of "top"s
    if len(top)!= ...
       raise ...
    top[0].reshape( ... ) # reshape the outputs to the proper sizes

  def forward(self,bottom,top): 
    # do your magic here... feed **one** batch to `top`
    top[0].data[...] = one_batch_of_data


  def backward(self, top, propagate_down, bottom):
    # no back-prop for input layers
    pass

```
