### ISSUE TITLE
OpenBabel version check for GetHvyValence/GetHvyDegree

### ISSUE THREAD

**Issue by mattragoza** [gnina/gnina#70]
https://github.com/gnina/gnina/blob/a3d260931360c17a20c6d2797ec58c41794a85d0/gninasrc/lib/atom_constants.h#L32-L39

I now don't think this check fixed the problem referenced in #63 as I am using version 2.4.90 on bridges and I get this build error:

```
/home/mtragoza/gnina/gninasrc/lib/atom_constants.h:35:24: error: ‘class OpenBabel::OBAtom’ has no member named ‘GetHvyDegree’; did you mean ‘GetHvyValence’?
 # define GET_HVY(a) a->GetHvyDegree()
                        ^
```
I think newer versions of OpenBabel use GetHvyValence rather than GetHvyDegree, though I don't know what exact version made the switch.

**Comment by dkoes** [comment]
GetHvyDegree is the newer version.  The change was made 3 months ago:
https://github.com/openbabel/openbabel/commit/e949134dc3851b4e2fd741695443b6bef80c2354

**Comment by mattragoza** [comment]
Ah ok, they just didn't update the version number when they changed the interface. I'll pull the most recent openbabel and rebuild.
