### ISSUE TITLE
Question about data input

### ISSUE THREAD

**Issue by injuryholmes** [gnina/gnina#71]
### Issue summary

When run command: gnina --minimize -r s.pdb -l ligand.sdf --cnn_soring
I was very confused about the input "s.pdb". I got the following options:
1. original protein (co-crystal structure), containing both pockets and ligands.
2. clean protein file, without the ligand structure.
3. site file, which refers a certain pocket of a given protein(since one protein may have many pockets).

And is there any pre-process steps required, after download the original pdb file from http://www.rcsb.org/ to get the separated clean protein structure and the ligand part.

Many thanks!

**Comment by dkoes** [comment]
`-r` is short for `-receptor`  This should be the receptor file without the ligand in it.  It is up to you whether waters, ions, or other molecules should be considered part of the fixed, rigid, receptor.

Minimization finds the locally optimum configuration of the provided ligand.  It needs to be pre-positioned in the desired binding site and realistic pose.  If you want to do docking, omit `-minimize` and specify the box to dock into, possibly by using the `--autoox_ligand` option to specify a bound ligand that defines a box.

**Comment by injuryholmes** [comment]
And I have another question. I was running the docking with command: 
gnina -r s.pdb -l l.sdf --autobox_ligand ll.pdb
It takes me about 2-3 hours without a result(i.e. no stdout).
p.s. our env has a GPU 1080 Ti, and we use about 580M GPU memory. And it use 8 core CPU when running docking.
Is it usual to take so long to run docking ? Or I'm using the wrong command?

Many thanks!

**Comment by dkoes** [comment]
That should not happen.  You should get information immediately printed to stdout.  Separately, you need `-o` or no output files will be generated.

If you provide your input files I can see if I can reproduce the problem.

**Comment by injuryholmes** [comment]
parameter "par.mc.num_steps" is calculated to be around 14000 if another parameter "num_mc_steps" is not explicitly set, thus it is so big which takes long time to calculate.    
Is is necessary to use par.mc.num_steps at that scale, or we can manually set it to a much smaller number to increase the speed?

Many thanks!

**Comment by dkoes** [comment]
If it is still taking hours without generating output for a single structure, there is some other problem.  You should be getting a progress bar and a normal sized ligand should only take a few minutes. 

You can always reduce sampling to make things faster, but then you will be sampling less.  I wouldn't recommend it.

**Comment by injuryholmes** [comment]
I promise this is my last question.
I still can't find out any reason that slow down my program, so I upload the file to google drive 
https://drive.google.com/drive/folders/15SOwmuVGx3KPfneaXwEe0ghFE0WTfqCh?usp=sharing
with a site.pdb and a ligand.sdf
Could you please run with the following command 
gnina -r site.pdb -l ligand.sdf --cnn_scoring --autobox_ligand ligand.sdf --gpu
how long does it take you to run? And could you please tell me your hardware specs?

Many thanks!

**Comment by Jsunseri** [comment]
Docking with the CNN is extremely slow - every step requires a forward and backward pass through the network. This is one of the reasons gnina prints at startup "IMPORTANT: Use of CNN scoring while docking is not recommended. CNN scoring is best used with --minimize or --score_only".

**Comment by dkoes** [comment]
Ah, yes.  Full cnn scoring will be very slow, but you had not specified you were doing that in your previous messages.  You should still get a progress bar though.
