### ISSUE TITLE
Error during compling gnina

### ISSUE THREAD

**Issue by bellstwohearted** [gnina/gnina#83]
Hi,

Centos7, CUDA-9.0, etc.
I fixed the following problem during the compilation of by upgrading the gcc version to 6.0.1:

`[ 14%] Building CUDA object src/CMakeFiles/libmolgrid_shared.dir/grid_maker.cu.o`

When the compilation continues, another error came about at 67%:
[ 63%] Built target molgrid
Scanning dependencies of target test_gridmaker_cu 
[ 65%] Building CUDA object test/CMakeFiles/test_gridmaker_cu.dir/test_gridmaker.cu.o 
[ 67%] Linking CXX executable ../bin/test_gridmaker_cu
/data/program/conda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: warning: libz.so.1, needed by /lib64/libopenbabel.so, not found (try using -rpath or -rpath-link)
/data/program/conda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: CMakeFiles/test_gridmaker_cu.dir/test_gridmaker.cu.o: relocation R_X86_64_32 against '.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/data/program/conda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../lib64/libmolgrid.a(grid_maker.cu.o): relocation R_X86_64_32S against symbol '_ZTVN6thrust6system12system_errorE' can not be used when making a PIE object; recompile with -fPIC
/data/program/conda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../lib64/libmolgrid.a(coordinateset.cu.o): relocation R_X86_64_32 against symbol '_ZN10libmolgrid20sum_vector_types_gpuENS_4GridIfLm2ELb1EEENS0_IfLm1ELb1EEE' can not be used when making a PIE object; recompile with -fPIC
/data/program/conda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../lib64/libmolgrid.a(transform.cu.o): relocation R_X86_64_32 against symbol '_ZN10libmolgrid26transform_translate_kernelIfEEvj6float3NS_4GridIT_Lm2ELb1EEES4_' can not be used when making a PIE object; recompile with -fPIC
/data/program/conda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: final link failed: nonrepresentable section on output
collect2: error: ld returned 1 exit status
make[5]: *** [bin/test_gridmaker_cu] Error 1
make[4]: *** [test/CMakeFiles/test_gridmaker_cu.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [libmolgrid-prefix/src/libmolgrid-stamp/libmolgrid-build] Error 2
make[1]: *** [CMakeFiles/libmolgrid.dir/all] Error 2
make: *** [all] Error 2

So, what results in this problem??  Thank you.

**Comment by dkoes** [comment]
By default I build both shared and static versions of the library.  If you don't have static versions of boost and openbabel installed this will be problematic.  Feel free to comment out the `libmoldgrid_static` lines in `src/CMakeLists.txt` although a pull request that properly implements BUILD_SHARED etc configuration would be greatly appreciated.

**Comment by bellstwohearted** [comment]
> dd
> 
> By default I build both shared and static versions of the library. If you don't have static versions of boost and openbabel installed this will be problematic. Feel free to comment out the `libmoldgrid_static` lines in `src/CMakeLists.txt` although a pull request that properly implements BUILD_SHARED etc configuration would be greatly appreciated.

**Comment by dkoes** [comment]
I've pushed cmake changes to support BUILD_SHARED and BUILD_STATIC options to libmolgrid (so you can set BUILD_STATIC=OFF)

**Comment by bellstwohearted** [comment]
I have downloaded the lastest version of cmake file and set `BUILD_STATIC=OFF`, but it seems not to change anything during the compilation???


> 
> 
> I've pushed cmake changes to support BUILD_SHARED and BUILD_STATIC options to libmolgrid (so you can set BUILD_STATIC=OFF)
