### ISSUE TITLE
training performance

### ISSUE THREAD

**Issue by ghost** [gnina/gnina#89]
Dear Dr. Koes,

I have implemented the training on the refmodel3 using the train.py script and obtained the same results as reported in your publication. With one GPU it takes about 11s for 40 iterations.

Again, I want to test how the framework performs on DUD-E target PUR2. I use docked (with Smina) structure for each ligand and generated .gninatypes file for each ligand. Then I did the similar thing: the ligands are put in a single folder, and then split into traing and testing randomly (0.8:0.2), I can see the following output:

```
I1104 11:14:08.481962 13687 solver.cpp:352] Iteration 0, Testing net (#1)
I1104 11:14:20.100967 13687 sgd_solver.cpp:99] Gradient clipping: scaling down gradients (L2 norm 10.878 > 10) by scale factor 0.919283

Iteration 40
Train time: 11.914718
Eval test time: 1.151939
Test AUC: 0.961171
Test loss: 0.934658
Eval train time: 4.759745
Train AUC: 0.962875
Train loss: 0.743320
Loop time: 17.827261 (1:13:58.988101 left)
Memory usage: 0.695gb (746708992)
Best test AUC/RMSD: 0.961171 inf   Best train loss: 0.743320

Iteration 80
Train time: 11.716022
Eval test time: 1.129195
Test AUC: 0.998048
Test loss: 0.108145
Eval train time: 4.739851
Train AUC: 0.991603
Train loss: 0.091265
Loop time: 17.586117 (1:13:11.258961 left)
Memory usage: 0.697gb (748298240)
Best test AUC/RMSD: 0.998048 inf   Best train loss: 0.091265

Iteration 120
Train time: 11.722106
Eval test time: 1.123328
Test AUC: 1.000000
Test loss: 0.046416
Eval train time: 4.852293
Train AUC: 0.997313
Train loss: 0.038289
Loop time: 17.698747 (1:12:52.898324 left)
Memory usage: 0.697gb (748834816)
Best test AUC/RMSD: 1.000000 inf   Best train loss: 0.038289
```

Do you think everything is going in good order? I am currently testing other DUD-E :
I am wondering that when generating .gninatypes files for the ligands, which model is used? I can see from the docked ligand file, there are 10 models, and when gninatyper process finished, there seems to be only one model is used. Is the top ranked one is used (e.g., model 1), or gninatyper will select the exactly right model? Attach you will see an example for DUDE target PUR2.

[PUR2.zip](https://github.com/gnina/gnina/files/3803746/PUR2.zip)

**Comment by dkoes** [comment]
Training structure-based machine learning models on DUDE is a bad idea.  See:
https://chemrxiv.org/articles/Hidden_Bias_in_the_DUD-E_Dataset_Leads_to_Misleading_Performance_of_Deep_Learning_in_Structure-Based_Virtual_Screening/7886165

The structures are of unknown quality and there is a lot of ligand-only signal in DUDe.  

gninatyper should generate files for all poses in an sdf - not sure why you are seeing only one.

**Comment by bellstwohearted** [comment]
Thank you very much. I will choose other high quality datasets to perform a training and virtual screening. 

I have also generated multiple gninatypes files from sdf files. Not sure why cannot do so from pdbqt files, but I don’t think it will be a problem.



> Training structure-based machine learning models on DUDE is a bad idea. See:
> https://chemrxiv.org/articles/Hidden_Bias_in_the_DUD-E_Dataset_Leads_to_Misleading_Performance_of_Deep_Learning_in_Structure-Based_Virtual_Screening/7886165
> 
> The structures are of unknown quality and there is a lot of ligand-only signal in DUDe.
> 
> gninatyper should generate files for all poses in an sdf - not sure why you are seeing only one.
