### ISSUE TITLE
Linking with "openbabel-NOTFOUND"

### ISSUE THREAD

**Issue by alanbchristie** [gnina/gnina#93]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Steps to reproduce

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.

### Your system configuration
Operating system:
Compiler:
CUDA version (if applicable):
CUDNN version (if applicable):
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):

**Comment by dkoes** [comment]
What is the issue?  You need openbabel 3.0 to be installed and found by cmake to build gnina.

**Comment by alanbchristie** [comment]
Apologies @dkoes, I navigated to the issues and didn't realise I'd actually create one. I've taken the issue up on the caffe-user list although over night...

...it turns out that the moral of the story is "don't try and be clever and change the installation locations" - I've now just let the tools install in the default locations and decided to let cmake figure it all out and that's got me past the current sticking point.

Let's close and even delete this issue.
